### ISSUE TITLE
edwin please accept my invitation for downr1n-gui

### ISSUE THREAD

**Issue by Aditya20110** [edwin170/downr1n#10]
title

**Comment by Aditya20110** [comment]
Discord link expired

**Comment by edwin170** [comment]
hi bro, forget that cause i don't know python, good luck doing it

**Comment by Aditya20110** [comment]
uckermark is with me

**Comment by edwin170** [comment]
> uckermark is with me

that is good but i told you that i don't want to contribute it cause i don't know python
