### ISSUE TITLE
Active file is missing

### ISSUE THREAD

**Issue by qkzhu** [edwin170/downr1n#103]
Device: iPhone 6s
ipsw: 14.6
The Phone iOS version is 13.6.1 and I try to install iOS 14.6, and I got the following error:
```
[!] Active file does not exist! Please use SSH to create it
    /mnt6/active should contain the name of the UUID in /mnt6
    When done, type reboot in the SSH session, then rerun the script
    ssh root@localhost -p 2222
```

I can connect to iPhone but I am not sure how to generate SSH, please help if anyone knows.

the full log is here:
```
➜  downr1n git:(main) ✗ ./downr1n.sh boot
[*] Command ran: ./downr1n.sh boot
downr1n | Version 3.0
Created by edwin, thanks palera1, and all people creator of path file boot

[*] Waiting for devices
[*] Detected ramdisk mode device
[*] Rebooting device in SSH Ramdisk
./downr1n.sh: line 371: 57421 Terminated: 15          "$dir"/iproxy 2222 22 > /dev/null
[*] Waiting for device in recovery mode
[*] Waiting for devices
[*] Detected recovery mode device
[*] Getting device info...
Detected cpid, your cpid is 0x8003
Detected model, your model is n71map
Detected deviceid, your deviceid is iPhone8,1
[*] To get into DFU mode, you will be guided through 2 steps:
[*] Press any key when ready for DFU mode
Get ready (0)
Release power button, but keep holding home button (9)
Release power button, but keep holding home button (0)
[*] Device entered DFU!
./downr1n.sh: line 696: [: ipsw/14.6.ipsw: binary operator expected
Choose an IPSW by entering its number:
1. ipsw/13.6.1.ipsw
2. ipsw/14.6.ipsw
3. ipsw/14.7.1.ipsw
Enter your choice: 2
[*] We are gonna use ipsw/14.6.ipsw
[*] Creating ramdisk
[-] Ramdisk is already created so SKIPPING ...
[*] Booting ramdisk
[/] We couldn't get the ipsw curl. we will proceed with -k option with curl
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8003 CPRV:01 CPFM:03 SCEP:01 BDID:04 ECID:0009253428078226 IBFL:1C SRTG:[iBoot-2234.0.0.2.22]
Found the USB handle.
Stage: RESET
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8003 CPRV:01 CPFM:03 SCEP:01 BDID:04 ECID:0009253428078226 IBFL:1C SRTG:[iBoot-2234.0.0.2.22]
Found the USB handle.
Stage: SETUP
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8003 CPRV:01 CPFM:03 SCEP:01 BDID:04 ECID:0009253428078226 IBFL:1C SRTG:[iBoot-2234.0.0.2.22]
Found the USB handle.
Stage: PATCH
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8003 CPRV:01 CPFM:03 SCEP:01 BDID:04 ECID:0009253428078226 IBFL:1C SRTG:[iBoot-2234.0.0.2.22] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Waiting for the ramdisk to finish booting
[*] Mounting filesystems ...
seputil: Gigalocker file (/mnt7/77BCCC6C-6835-5BA6-A64D-8F0D276AEFB9.gl) exists
seputil: Gigalocker initialization completed
sepi digest (20 bytes): 06c0517128a2ca7bb3546fe9adb335baddcd71b8
sepi nonce (20 bytes): bfc1ef59842175c293bc326cd8afe83c398e3238
rsep digest (20 bytes): adb0c7f4d2d77b42ed9bf6077e15eddedf5e1ec8
rsep nonce (20 bytes): bfc1ef59842175c293bc326cd8afe83c398e3238
[!] Active file does not exist! Please use SSH to create it
    /mnt6/active should contain the name of the UUID in /mnt6
    When done, type reboot in the SSH session, then rerun the script
    ssh root@localhost -p 2222
```

**Comment by edwin170** [comment]
> Device: iPhone 6s ipsw: 14.6 The Phone iOS version is 13.6.1 and I try to install iOS 14.6, and I got the following error:
> 
> ```
> [!] Active file does not exist! Please use SSH to create it
>     /mnt6/active should contain the name of the UUID in /mnt6
>     When done, type reboot in the SSH session, then rerun the script
>     ssh root@localhost -p 2222
> ```
> 
> I can connect to iPhone but I am not sure how to generate SSH, please help if anyone knows.
> 
> the full log is here:
> 
> ```
> ➜  downr1n git:(main) ✗ ./downr1n.sh boot
> [*] Command ran: ./downr1n.sh boot
> downr1n | Version 3.0
> Created by edwin, thanks palera1, and all people creator of path file boot
> 
> [*] Waiting for devices
> [*] Detected ramdisk mode device
> [*] Rebooting device in SSH Ramdisk
> ./downr1n.sh: line 371: 57421 Terminated: 15          "$dir"/iproxy 2222 22 > /dev/null
> [*] Waiting for device in recovery mode
> [*] Waiting for devices
> [*] Detected recovery mode device
> [*] Getting device info...
> Detected cpid, your cpid is 0x8003
> Detected model, your model is n71map
> Detected deviceid, your deviceid is iPhone8,1
> [*] To get into DFU mode, you will be guided through 2 steps:
> [*] Press any key when ready for DFU mode
> Get ready (0)
> Release power button, but keep holding home button (9)
> Release power button, but keep holding home button (0)
> [*] Device entered DFU!
> ./downr1n.sh: line 696: [: ipsw/14.6.ipsw: binary operator expected
> Choose an IPSW by entering its number:
> 1. ipsw/13.6.1.ipsw
> 2. ipsw/14.6.ipsw
> 3. ipsw/14.7.1.ipsw
> Enter your choice: 2
> [*] We are gonna use ipsw/14.6.ipsw
> [*] Creating ramdisk
> [-] Ramdisk is already created so SKIPPING ...
> [*] Booting ramdisk
> [/] We couldn't get the ipsw curl. we will proceed with -k option with curl
> usb_timeout: 5
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8003 CPRV:01 CPFM:03 SCEP:01 BDID:04 ECID:0009253428078226 IBFL:1C SRTG:[iBoot-2234.0.0.2.22]
> Found the USB handle.
> Stage: RESET
> ret: true
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8003 CPRV:01 CPFM:03 SCEP:01 BDID:04 ECID:0009253428078226 IBFL:1C SRTG:[iBoot-2234.0.0.2.22]
> Found the USB handle.
> Stage: SETUP
> ret: true
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8003 CPRV:01 CPFM:03 SCEP:01 BDID:04 ECID:0009253428078226 IBFL:1C SRTG:[iBoot-2234.0.0.2.22]
> Found the USB handle.
> Stage: PATCH
> ret: true
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID:8003 CPRV:01 CPFM:03 SCEP:01 BDID:04 ECID:0009253428078226 IBFL:1C SRTG:[iBoot-2234.0.0.2.22] PWND:[gaster]
> Found the USB handle.
> Now you can boot untrusted images.
> usb_timeout: 5
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> Found the USB handle.
> [==================================================] 100.0%
> [==================================================] 100.0%
> [==================================================] 100.0%
> [==================================================] 100.0%
> [==================================================] 100.0%
> [==================================================] 100.0%
> [==================================================] 100.0%
> [*] Waiting for the ramdisk to finish booting
> [*] Mounting filesystems ...
> seputil: Gigalocker file (/mnt7/77BCCC6C-6835-5BA6-A64D-8F0D276AEFB9.gl) exists
> seputil: Gigalocker initialization completed
> sepi digest (20 bytes): 06c0517128a2ca7bb3546fe9adb335baddcd71b8
> sepi nonce (20 bytes): bfc1ef59842175c293bc326cd8afe83c398e3238
> rsep digest (20 bytes): adb0c7f4d2d77b42ed9bf6077e15eddedf5e1ec8
> rsep nonce (20 bytes): bfc1ef59842175c293bc326cd8afe83c398e3238
> [!] Active file does not exist! Please use SSH to create it
>     /mnt6/active should contain the name of the UUID in /mnt6
>     When done, type reboot in the SSH session, then rerun the script
>     ssh root@localhost -p 2222
> ```

it needs some modifications to make it work, just restore to latest version and then downgrade
