### ISSUE TITLE
iPhone 16.7.5 to 14.8 - Restoration Failed - Can you Guide ?

### ISSUE THREAD

**Issue by subu1979** [edwin170/downr1n#108]
Not sure what's the issue. Can you guide ?

[iphone8_16_14_8_failed.log](https://github.com/edwin170/downr1n/files/14492074/iphone8_16_14_8_failed.log)

[iphone8_16_14_8_failed 2.log](https://github.com/edwin170/downr1n/files/14492214/iphone8_16_14_8_failed.2.log)

**Comment by edwin170** [comment]
try restoring to latest iOS and try it again
