### ISSUE TITLE
TypeError: function missing required argument 'initial_buffer_values' (pos 2)

### ISSUE THREAD

**Issue by trandinhgiabao2612** [edwin170/downr1n#111]
![image](https://github.com/edwin170/downr1n/assets/108709755/53908d18-a037-4832-adf9-13f9d3f1b58c)
How can I fix it?

**Comment by edwin170** [comment]
python3 -m pip uninstall pylzss lzss, and execute downr1n again

**Comment by trandinhgiabao2612** [comment]
![image](https://github.com/edwin170/downr1n/assets/108709755/d8b6f872-e6c2-492c-8526-2e19ec15aeff)
it whave one error :/

**Comment by edwin170** [comment]
> ![image](https://private-user-images.githubusercontent.com/108709755/312225048-d8b6f872-e6c2-492c-8526-2e19ec15aeff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzUxMDMsIm5iZiI6MTcxMDI3NDgwMywicGF0aCI6Ii8xMDg3MDk3NTUvMzEyMjI1MDQ4LWQ4YjZmODcyLWU2YzItNDkyYy04NTI2LTJlMTllYzE1YWVmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQyMDIwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTk5NmIxYzllMGI1MTk1ZThkYTVhYTk1OTJhNTYxMGVkNTdlODhiNmVmMTc5MmI3YmVhNjc3MGFjNmJkYzA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ATXiJINHdwOhCoSpveb2GDx0AVlXnajtRSyl0-ZzIUY) it work but this have one error :/

sudo apt install zip unzip
