### ISSUE TITLE
Support for iOS 16 Version Downgrades

### ISSUE THREAD

**Issue by TheDoctor200** [edwin170/downr1n#112]
I would love to downgrade my iPhone 8 with iOS 16.7.5 to 16.6.1 without blobs. Would be cool if this tool gets that feature to downgrade to iOS 16 versions

Thanks!

**Comment by TheDoctor200** [comment]
@edwin170 is it possible to downgrade my iPhone 8 to iOS 16.6 with this? Has the enhancement been added?

**Comment by edwin170** [comment]
> @edwin170 is it possible to downgrade my iPhone 8 to iOS 16.6 with this? Has the enhancement been added?

sorry it didn't, and it won't
