### ISSUE TITLE
downgrade help ipad pro 9.7

### ISSUE THREAD

**Issue by Ran-Xing** [edwin170/downr1n#116]
I have an iPad Pro 9.7 WiFi a9x
I want to downgrade to 14.x, now 16.7.7
I can accept no fingerprint, jailbreak, device boot,
Are there any relevant tutorials? I have been following it for half a year

**Comment by edwin170** [comment]
1: Download the IPSW file and place it in the ipsw/ directory.

2: execute: ./downr1n.sh --downgrade 14.3.

Example: ./downr1n.sh --downgrade 14.3

**Comment by Ran-Xing** [comment]
not ok,I've tried this before

**Comment by edwin170** [comment]
> Downgrade failed, I tried before

it doesn't help, can you say what was the error because it failed. also git pull and try again there was a fix for some stuff
