### ISSUE TITLE
Unable to Activate

### ISSUE THREAD

**Issue by Checkm8ra1n** [edwin170/downr1n#117]
![IMG_2477](https://github.com/edwin170/downr1n/assets/110713827/80b4683d-ddca-4a19-bd66-852091710e7c)
I've downgraded my iPad 6th gen Wifi from ios 17.4.1 to 15.5, but unable to activate error. I've used MacOS Sonoma (I have also Windows if need it)

**Comment by edwin170** [comment]
> ![IMG_2477](https://private-user-images.githubusercontent.com/110713827/339564012-80b4683d-ddca-4a19-bd66-852091710e7c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzODEyOTYsIm5iZiI6MTcxODM4MDk5NiwicGF0aCI6Ii8xMTA3MTM4MjcvMzM5NTY0MDEyLTgwYjQ2ODNkLWRkY2EtNGExOS1iZDY2LTg1MjA5MTcxMGU3Yy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxNjAzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTViYTc5NGY1MzkxNWQ0MjU4MDVjYzA5NjNkZWFjN2I4NzhmM2FkMWFmMGM3Y2JiOTkyZDhiNjExZGI4ZTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tAnR_TkXr7OUWgvLQLEKNQXvqO2A3Kw2hkxC5MSoh-0) I've downgraded my iPad 6th gen Wifi from ios 17.4.1 to 15.5, but unable to activate error. I've used MacOS Sonoma (I have also Windows if need it)

you need to --jailbreak with downr1n and then use bypassra1n to jump setup
