### ISSUE TITLE
prints this message in loops: "[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true"

### ISSUE THREAD

**Issue by cutypie2351** [edwin170/downr1n#118]
*] Creating ramdisk
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true

....

what can i do? its printing that on loops and i dont know what to do. please help

**Comment by edwin170** [comment]
> *] Creating ramdisk usb_timeout: 5 [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: RESET ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: SPRAY ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: SETUP ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true
> 
> ....
> 
> what can i do? its printing that on loops and i dont know what to do. please help

if it was downgraded sucessfully with futurerestore, that error is because false dfu mode, if your pc is amd gaster has sucess low rate so you will have to try it again until get it like 5 times, if not it could be just bad usb, probably try a good cable lighning to usb
