### ISSUE TITLE
No version specified for pyliblzfse. Installing the latest version on fedora

### ISSUE THREAD

**Issue by idkk2456t** [edwin170/downr1n#119]
i am trying to downgrade an iphone 6s from ios 15.8.2 to ios 13.2 and it keeps saying No version specified for pyliblzfse. Installing the latest version. and then proceds to install and then fails

> No version specified for pyliblzfse. Installing the latest version.
Collecting pyliblzfse
  Using cached pyliblzfse-0.4.1.tar.gz (47 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: pyliblzfse
  Building wheel for pyliblzfse (pyproject.toml): started
  Building wheel for pyliblzfse (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  

>   × Building wheel for pyliblzfse (pyproject.toml) did not run successfully.

  │ exit code: 1
  ╰─> [89 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'liblzfse' extension
      creating build
      creating build/temp.linux-x86_64-cpython-312
      creating build/temp.linux-x86_64-cpython-312/lzfse
      creating build/temp.linux-x86_64-cpython-312/lzfse/src
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fPIC -Ilzfse/src -I/usr/include/python3.12 -c lzfse/src/lzfse_decode.c -o build/temp.linux-x86_64-cpython-312/lzfse/src/lzfse_decode.o -std=c99
      In file included from lzfse/src/lzfse_internal.h:30,
                       from lzfse/src/lzfse_decode.c:25:
      lzfse/src/lzfse_fse.h: In function ‘fse_check_freq’:
      lzfse/src/lzfse_fse.h:564:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
        564 |   for (int i = 0; i < table_size; i++) {
            |                     ^
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fPIC -Ilzfse/src -I/usr/include/python3.12 -c lzfse/src/lzfse_decode_base.c -o build/temp.linux-x86_64-cpython-312/lzfse/src/lzfse_decode_base.o -std=c99
      In file included from lzfse/src/lzfse_internal.h:30,
                       from lzfse/src/lzfse_decode_base.c:22:
      lzfse/src/lzfse_fse.h: In function ‘fse_check_freq’:
      lzfse/src/lzfse_fse.h:564:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
        564 |   for (int i = 0; i < table_size; i++) {
            |                     ^
      lzfse/src/lzfse_decode_base.c: In function ‘lzfse_decode_lmd’:
      lzfse/src/lzfse_decode_base.c:240:30: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int32_t’ {aka ‘int’} [-Wsign-compare]
        240 |         for (size_t i = 0; i < M; i++)
            |                              ^
      lzfse/src/lzfse_decode_base.c:256:30: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int32_t’ {aka ‘int’} [-Wsign-compare]
        256 |         for (size_t i = 0; i < L; i++)
            |                              ^
      lzfse/src/lzfse_decode_base.c:268:30: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘ptrdiff_t’ {aka ‘long int’} [-Wsign-compare]
        268 |         for (size_t i = 0; i < remaining_bytes; i++)
            |                              ^
      lzfse/src/lzfse_decode_base.c:280:30: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int32_t’ {aka ‘int’} [-Wsign-compare]
        280 |         for (size_t i = 0; i < M; i++)
            |                              ^
      lzfse/src/lzfse_decode_base.c:294:30: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘ptrdiff_t’ {aka ‘long int’} [-Wsign-compare]
        294 |         for (size_t i = 0; i < remaining_bytes; i++)
            |                              ^
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fPIC -Ilzfse/src -I/usr/include/python3.12 -c lzfse/src/lzfse_encode.c -o build/temp.linux-x86_64-cpython-312/lzfse/src/lzfse_encode.o -std=c99
      In file included from lzfse/src/lzfse_internal.h:30,
                       from lzfse/src/lzfse_encode.c:25:
      lzfse/src/lzfse_fse.h: In function ‘fse_check_freq’:
      lzfse/src/lzfse_fse.h:564:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
        564 |   for (int i = 0; i < table_size; i++) {
            |                     ^
      lzfse/src/lzfse_encode.c: In function ‘lzfse_encode_buffer_with_scratch’:
      lzfse/src/lzfse_encode.c:94:23: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘lzfse_offset’ {aka ‘long int’} [-Wsign-compare]
         94 |       while (src_size >= encoder_block_size) {
            |                       ^~
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fPIC -Ilzfse/src -I/usr/include/python3.12 -c lzfse/src/lzfse_encode_base.c -o build/temp.linux-x86_64-cpython-312/lzfse/src/lzfse_encode_base.o -std=c99
      In file included from lzfse/src/lzfse_internal.h:30,
                       from lzfse/src/lzfse_encode_base.c:24:
      lzfse/src/lzfse_fse.h: In function ‘fse_check_freq’:
      lzfse/src/lzfse_fse.h:564:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
        564 |   for (int i = 0; i < table_size; i++) {
            |                     ^
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fPIC -Ilzfse/src -I/usr/include/python3.12 -c lzfse/src/lzfse_fse.c -o build/temp.linux-x86_64-cpython-312/lzfse/src/lzfse_fse.o -std=c99
      In file included from lzfse/src/lzfse_internal.h:30,
                       from lzfse/src/lzfse_fse.c:22:
      lzfse/src/lzfse_fse.h: In function ‘fse_check_freq’:
      lzfse/src/lzfse_fse.h:564:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
        564 |   for (int i = 0; i < table_size; i++) {
            |                     ^
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fPIC -Ilzfse/src -I/usr/include/python3.12 -c lzfse/src/lzvn_decode_base.c -o build/temp.linux-x86_64-cpython-312/lzfse/src/lzvn_decode_base.o -std=c99
      In file included from lzfse/src/lzfse_internal.h:30,
                       from lzfse/src/lzvn_decode_base.h:29,
                       from lzfse/src/lzvn_decode_base.c:24:
      lzfse/src/lzfse_fse.h: In function ‘fse_check_freq’:
      lzfse/src/lzfse_fse.h:564:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
        564 |   for (int i = 0; i < table_size; i++) {
            |                     ^
      lzfse/src/lzvn_decode_base.c: In function ‘lzvn_decode’:
      lzfse/src/lzvn_decode_base.c:431:9: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘long int’ [-Wsign-compare]
        431 |   if (D > dst_ptr - state->dst_begin || D == 0)
            |         ^
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fPIC -Ilzfse/src -I/usr/include/python3.12 -c lzfse/src/lzvn_encode_base.c -o build/temp.linux-x86_64-cpython-312/lzfse/src/lzvn_encode_base.o -std=c99
      In file included from lzfse/src/lzfse_internal.h:30,
                       from lzfse/src/lzvn_encode_base.h:27,
                       from lzfse/src/lzvn_encode_base.c:24:
      lzfse/src/lzfse_fse.h: In function ‘fse_check_freq’:
      lzfse/src/lzfse_fse.h:564:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
        564 |   for (int i = 0; i < table_size; i++) {
            |                     ^
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fPIC -Ilzfse/src -I/usr/include/python3.12 -c pylzfse.c -o build/temp.linux-x86_64-cpython-312/pylzfse.o -std=c99
      pylzfse.c:28:10: fatal error: Python.h: No such file or directory
         28 | #include <Python.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  

> note: This error originates from a subprocess, and is likely not a problem with pip.

  ERROR: Failed building wheel for pyliblzfse
Failed to build pyliblzfse
ERROR: Could not build wheels for pyliblzfse, which is required to install pyproject.toml-based 

here is the error and i tried everything any solution is helpful

**Comment by idkk2456t** [comment]
thank you for answering but i already have python3 installed

**Comment by edwin170** [comment]
otection -fexceptions -fcf-protection -fexceptions -fcf-protection -fPIC -Ilzfse/src -I/usr/include/python3.12 -c pylzfse.c -o build/temp.linux-x86_64-cpython-312/pylzfse.o -std=c99
pylzfse.c:28:10: fatal error: Python.h: No such file or directory
28 | #include <Python.h>
| ^~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for pyliblzfse
Failed to build pyliblzfse
ERROR: Could not build wheels for pyliblzfse, which is required to install pyproject.toml-based







just reading this says that python.h is needed iirc
