### ISSUE TITLE
Error on setting up Ramdisk on iPhone 7

### ISSUE THREAD

**Issue by saulcheeseman** [edwin170/downr1n#121]
No idea why this is happening, never had it happen before:

`download succeeded
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:0C ECID:000D784C383110A6 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[-] An error occurred
`

**Comment by saulcheeseman** [comment]
Fixed, had to update my iOS

**Comment by edwin170** [comment]
mmh thx for share it
