### ISSUE TITLE
need help with pongoOS

### ISSUE THREAD

**Issue by UnCor3** [edwin170/downr1n#123]
Hey I will be downgrading from iOS 15 to 14.8 to use ProjectSandbox Linux but how do I boot to pongoOS with checkra1n with a tethered iOS ? Would there be a problem ? If so is there a workaround for this ? I don't think `--jailbreak` flag is what I need in this situation

**Comment by edwin170** [comment]
> Hey I will be downgrading from iOS 15 to 14.8 to use ProjectSandbox Linux but how do I boot to pongoOS with checkra1n with a tethered iOS ? Would there be a problem ? If so is there a workaround for this ? I don't think `--jailbreak` flag is what I need in this situation

downr1n --jailbreakd doesn't boot pongoOS, sadly you won't be able to use projectSandbox with downr1n
