### ISSUE TITLE
Futurerestore fail：Unable to restore device

### ISSUE THREAD

**Issue by MW-S** [edwin170/downr1n#127]
Target ：IOS 13.3

Running Environment:
1. Real machine Ubuntu 22.04
2. iPhone se IOS 15.8.3

Detail Message：
The first run error instruction：`./downr1n.sh --downgrade 13.3`

```
Press ENTER to continue with futurerestore, your device will start to restoring <-
Version: v2.0.0(22a5d89bdec6e1c441012d63822184c93530b7e5-321)
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
libipatcher version: 0.91-cb10d973d0af78cc55020d4cf1187c28fad0f2a0-RELEASE
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes
futurerestore: failed with exception:
[exception]:
what=did not init

code=16252982
line=248
file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp
commit count=321
commit sha  =22a5d89bdec6e1c441012d63822184c93530b7e5
if futurerestore failed you can try execute the command below
if futurerestore didn't finish succesfully please try to run (with sudo or without) this command: /home/ubuntu/py/downr1n/binaries/Linux/futurerestore -t blobs/iPhone8,4-13.3.shsh2 --use-pwndfbaseband ipsw/iPhone_4.0_64bit_13.3_17C54_Restore.ipsw
if futurerestore restore sucess, you can boot using  --boot
```

The second run error instruction：`/home/ubuntu/py/downr1n/binaries/Linux/futurerestore -t blobs/iPhone8,4-13.3.shsh2 --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --latest-baseband` ipsw/iPhone_4.0_64bit_13.3_17C54_Restore.ipsw
```
ERROR: Unable to successfully restore device
Checkpoint 1608 complete with code 0
ReverseProxy[Conn]: (status=6) Disconnected (out: 10893 / in: 150690)
ReverseProxy[Conn]: (status=2) Terminated
ReverseProxy[Conn]: (status=6) Disconnected (out: 1497 / in: 2781)
ReverseProxy[Conn]: (status=2) Terminated
ReverseProxy[Conn]: (status=6) Disconnected (out: 10930 / in: 154618)
ReverseProxy[Conn]: (status=2) Terminated
ReverseProxy[Ctrl]: (status=2) Terminated
Cleaning up...
[exception]:
what=ERROR: Unable to restore device

code=98238518
line=1499
file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp
commit count=321
commit sha  =22a5d89bdec6e1c441012d63822184c93530b7e5
Done: restoring failed!
```

**Comment by MW-S** [comment]
Current iPhone is DFU Mode！

**Comment by MW-S** [comment]
I don't know if this information is useful：
```
root@ubuntu-R425D-R525D:/home/ubuntu/py/downr1n# python3 wikiproxy.py 
INFO:     Started server process [14752]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not str
Call stack:
  File "/home/ubuntu/py/downr1n/wikiproxy.py", line 181, in <module>
    uvicorn.run(app='__main__:app', host='127.0.0.1', port='8888')
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 84, in _serve
    await self.startup(sockets=sockets)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 179, in startup
    self._log_started_message(listeners)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/server.py", line 214, in _log_started_message
    logger.info(
Message: 'Uvicorn running on %s://%s:%d (Press CTRL+C to quit)'
Arguments: ('http', '127.0.0.1', '8888')
```

**Comment by edwin170** [comment]
> Target ：IOS 13.3
> 
> Running Environment:
> 
> 1. Real machine Ubuntu 22.04
> 2. iPhone se IOS 15.8.3
> 
> Detail Message： The first run error instruction：`./downr1n.sh --downgrade 13.3`
> 
> ```
> Press ENTER to continue with futurerestore, your device will start to restoring <-
> Version: v2.0.0(22a5d89bdec6e1c441012d63822184c93530b7e5-321)
> img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
> libipatcher version: 0.91-cb10d973d0af78cc55020d4cf1187c28fad0f2a0-RELEASE
> Odysseus for 32-bit support: yes
> Odysseus for 64-bit support: yes
> futurerestore: failed with exception:
> [exception]:
> what=did not init
> 
> code=16252982
> line=248
> file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp
> commit count=321
> commit sha  =22a5d89bdec6e1c441012d63822184c93530b7e5
> if futurerestore failed you can try execute the command below
> if futurerestore didn't finish succesfully please try to run (with sudo or without) this command: /home/ubuntu/py/downr1n/binaries/Linux/futurerestore -t blobs/iPhone8,4-13.3.shsh2 --use-pwndfbaseband ipsw/iPhone_4.0_64bit_13.3_17C54_Restore.ipsw
> if futurerestore restore sucess, you can boot using  --boot
> ```
> 
> The second run error instruction：`/home/ubuntu/py/downr1n/binaries/Linux/futurerestore -t blobs/iPhone8,4-13.3.shsh2 --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --latest-baseband` ipsw/iPhone_4.0_64bit_13.3_17C54_Restore.ipsw
> 
> ```
> ERROR: Unable to successfully restore device
> Checkpoint 1608 complete with code 0
> ReverseProxy[Conn]: (status=6) Disconnected (out: 10893 / in: 150690)
> ReverseProxy[Conn]: (status=2) Terminated
> ReverseProxy[Conn]: (status=6) Disconnected (out: 1497 / in: 2781)
> ReverseProxy[Conn]: (status=2) Terminated
> ReverseProxy[Conn]: (status=6) Disconnected (out: 10930 / in: 154618)
> ReverseProxy[Conn]: (status=2) Terminated
> ReverseProxy[Ctrl]: (status=2) Terminated
> Cleaning up...
> [exception]:
> what=ERROR: Unable to restore device
> 
> code=98238518
> line=1499
> file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp
> commit count=321
> commit sha  =22a5d89bdec6e1c441012d63822184c93530b7e5
> Done: restoring failed!
> ```

you only can downgrade from 15 to 13.4 upper

**Comment by MW-S** [comment]
> > Target ：IOS 13.3
> > Running Environment:
> > 
> > 1. Real machine Ubuntu 22.04
> > 2. iPhone se IOS 15.8.3
> > 
> > Detail Message： The first run error instruction：`./downr1n.sh --downgrade 13.3`
> > ```
> > Press ENTER to continue with futurerestore, your device will start to restoring <-
> > Version: v2.0.0(22a5d89bdec6e1c441012d63822184c93530b7e5-321)
> > img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
> > libipatcher version: 0.91-cb10d973d0af78cc55020d4cf1187c28fad0f2a0-RELEASE
> > Odysseus for 32-bit support: yes
> > Odysseus for 64-bit support: yes
> > futurerestore: failed with exception:
> > [exception]:
> > what=did not init
> > 
> > code=16252982
> > line=248
> > file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp
> > commit count=321
> > commit sha  =22a5d89bdec6e1c441012d63822184c93530b7e5
> > if futurerestore failed you can try execute the command below
> > if futurerestore didn't finish succesfully please try to run (with sudo or without) this command: /home/ubuntu/py/downr1n/binaries/Linux/futurerestore -t blobs/iPhone8,4-13.3.shsh2 --use-pwndfbaseband ipsw/iPhone_4.0_64bit_13.3_17C54_Restore.ipsw
> > if futurerestore restore sucess, you can boot using  --boot
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The second run error instruction：`/home/ubuntu/py/downr1n/binaries/Linux/futurerestore -t blobs/iPhone8,4-13.3.shsh2 --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --latest-baseband` ipsw/iPhone_4.0_64bit_13.3_17C54_Restore.ipsw
> > ```
> > ERROR: Unable to successfully restore device
> > Checkpoint 1608 complete with code 0
> > ReverseProxy[Conn]: (status=6) Disconnected (out: 10893 / in: 150690)
> > ReverseProxy[Conn]: (status=2) Terminated
> > ReverseProxy[Conn]: (status=6) Disconnected (out: 1497 / in: 2781)
> > ReverseProxy[Conn]: (status=2) Terminated
> > ReverseProxy[Conn]: (status=6) Disconnected (out: 10930 / in: 154618)
> > ReverseProxy[Conn]: (status=2) Terminated
> > ReverseProxy[Ctrl]: (status=2) Terminated
> > Cleaning up...
> > [exception]:
> > what=ERROR: Unable to restore device
> > 
> > code=98238518
> > line=1499
> > file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp
> > commit count=321
> > commit sha  =22a5d89bdec6e1c441012d63822184c93530b7e5
> > Done: restoring failed!
> > ```
> 
> you only can downgrade from 15 to 13.4 upper

IOS 13.4 is OK！ 
Thank you！
```
Status: Restore Finished
ReverseProxy[Ctrl]: (status=2) Terminated
Cleaning up...
Done: restoring succeeded!
```
