### ISSUE TITLE
Stuck in Pwning device

### ISSUE THREAD

**Issue by MW-S** [edwin170/downr1n#128]
Futurerestore is success， but Stucking boot。

Showing Loop Message in First excute ：

```
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8000
Found the USB handle.
Stage: PATCH
ret: false
```

Execute` binaries/Linux/gaster pwn` show same message：

```
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8000
Found the USB handle.
Stage: PATCH
ret: false
```

Now：
```
root@ubuntu-R425D-R525D:/home/ubuntu/py/downr1n# ./downr1n.sh --boot
[*] Command ran: sudo ./downr1n.sh --boot
[08:36:30.613][3] usbmuxd v1.1.1 starting up
[08:36:30.614][3] Using libusb 1.0.25
[08:36:30.619][3] Initialization complete
[+] pyimg4 version 0.8 is already installed.
[+] pylzss version 0.3.4 is already installed.
[-] No version specified for pyliblzfse. Installing the latest version.
Requirement already satisfied: pyliblzfse in /usr/local/lib/python3.9/dist-packages (0.4.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
downr1n | Version 3.0
Created by edwin, thanks palera1n, and all people creator of path file boot

[*] Waiting for devices
[*] Detected DFU mode device
[*] Waiting for devices
[*] Detected DFU mode device
[*] Getting device info...
Detected cpid, your cpid is 0x8000
Detected model, your model is n69uap
Detected deviceid, your deviceid is iPhone8,4
[*] Pwning device
```

**Comment by dualra1n** [comment]
It's in false dfu, sooo what you must do is read this messege:



First: execute sudo ./binaries/$(uname)/gaster pwn, if that start to loop (like never finish) Force reboot when the loop stop please press home button (or volume down) and stop gaster by pressing ctrl + c in your computer and after 10 second execute the command again

**Comment by MW-S** [comment]
> It's in false dfu, sooo what you must do is read this messege:
> 
> First: execute sudo ./binaries/$(uname)/gaster pwn, if that start to loop (like never finish) Force reboot when the loop stop please press home button (or volume down) and stop gaster by pressing ctrl + c in your computer and after 10 second execute the command again

ok，thank you！

**Comment by dualra1n** [comment]
> > It's in false dfu, sooo what you must do is read this messege:
> 
> > 
> 
> > First: execute sudo ./binaries/$(uname)/gaster pwn, if that start to loop (like never finish) Force reboot when the loop stop please press home button (or volume down) and stop gaster by pressing ctrl + c in your computer and after 10 second execute the command again
> 
> 
> 
> ok，thank you！

Sooo did it work ?

**Comment by MW-S** [comment]
> > > It's in false dfu, sooo what you must do is read this messege:
> > 
> > 
> > > 
> > 
> > 
> > > First: execute sudo ./binaries/$(uname)/gaster pwn, if that start to loop (like never finish) Force reboot when the loop stop please press home button (or volume down) and stop gaster by pressing ctrl + c in your computer and after 10 second execute the command again
> > 
> > 
> > ok，thank you！
> 
> Sooo did it work ?

Of course, I have successfully downgraded to ios13.4! 
But touch ID does not work;
I want to try downgrading to ios 14 to see if touch ID can work

**Comment by dualra1n** [comment]
Glad to hear it worked, yep in the readme says that "on iOS 13 Touch ID doesn't work" however iOS 14 and upper it works nice
