### ISSUE TITLE
no such option: --break-system-packages.

### ISSUE THREAD

**Issue by igjnaj** [edwin170/downr1n#129]
[-] No version specified for pyliblzfse. Installing the latest version.

Usage:   
  /usr/bin/python3 -m pip install [options] <requirement specifier> [package-index-options] ...
  /usr/bin/python3 -m pip install [options] -r <requirements file> [package-index-options] ...
  /usr/bin/python3 -m pip install [options] [-e] <vcs project url> ...
  /usr/bin/python3 -m pip install [options] [-e] <local project path> ...
  /usr/bin/python3 -m pip install [options] <archive url/path> ...

no such option: --break-system-packages

OS : Ubuntu 22.04

**Comment by dualra1n** [comment]
> [-] No version specified for pyliblzfse. Installing the latest version.
> 
> Usage: /usr/bin/python3 -m pip install [options] [package-index-options] ... /usr/bin/python3 -m pip install [options] -r [package-index-options] ... /usr/bin/python3 -m pip install [options] [-e] ... /usr/bin/python3 -m pip install [options] [-e] ... /usr/bin/python3 -m pip install [options] <archive url/path> ...
> 
> no such option: --break-system-packages
> 
> OS : Ubuntu 22.04

fixed!
