### ISSUE TITLE
stuck on creating ramdisk

### ISSUE THREAD

**Issue by ludzzo** [edwin170/downr1n#13]
after extracting the files from the ipsw (14.5) and inflating them , it says " creating ramdisk " but its stuck there for hours . how do i fix this?

anyway im using this on an iphone 12mini(the small version) that has iOS 16.3.1 or 16.4 i dont actually remember , and im trying to downgrade it to 14.5

**Comment by Aditya20110** [comment]
bro are u okay,this only works on iphone X and lower.
