### ISSUE TITLE
downr1n feature compatibility

### ISSUE THREAD

**Issue by imnltsa** [edwin170/downr1n#131]
This is moreso a question, but on downr1n devices, are you able to...
- Use a VPN by configuration provided by an app. Example photo:

![](https://sp-ao.shortpixel.ai/client/to_auto,q_lossy,ret_img,w_1340/https://s23429.pcdn.co/wp-content/uploads/2015/11/expressvpn-ios-10.0.0-add-vpn-configurations-tap-allow.png)
> [!IMPORTANT]
> (Pressing 'Allow' opens the Settings app and then reopens the VPN application. No VPN configurations are added.)

- View iCloud keychain passwords from the Settings app
- Use [Sidecar](https://support.apple.com/en-us/102597) on a supported device ***wirelessly***

Though different, I am using the [ios15tether](https://github.com/imnltsa/ios15tether) guide I had written, which uses your forks for tools like [Kernel64Patcher](https://github.com/edwin170/Kernel64Patcher/raw/master/Kernel64Patcher_Darwin), so I assume the same problems would arise for both ios15tether and downr1n.

**Comment by edwin170** [comment]
yes. you should be able to set new vpn, however if you use bypassr1n i think you won't be able, and if you downgraded from ios 16 or 17 iirc

**Comment by imnltsa** [comment]
> yes. you should be able to set new vpn, however if you use bypassr1n i think you won't be able, and if you downgraded from ios 16 or 17 iirc 

I use legitimate activation tickets (albeit from 17 on a 15 device), so nothing is bypassed. Do you think this still plays a role?

Sorry for bugging, I figured you'd be the person to know about this the most; I use things like your firmware validation bypass for iOS 15, so I figured it's somewhat similar.

**Comment by edwin170** [comment]
> > yes. you should be able to set new vpn, however if you use bypassr1n i think you won't be able, and if you downgraded from ios 16 or 17 iirc
> 
> I use legitimate activation tickets (albeit from 17 on a 15 device), so nothing is bypassed. Do you think this still plays a role?
> 
> Sorry for bugging, I figured you'd be the person to know about this the most; I use things like your firmware validation bypass for iOS 15, so I figured it's somewhat similar.
> 
> PS, have you tried viewing keychain passwords? I believe it needs SEP working. I'm not sure why Sidecar doesn't work wirelessly, though, since stuff like WiFi and Bluetooth work (device doesn't support cellular).

i think the sep of ios 16 just doesn't like downgrades ios, soo for that reason we can't activate our devices as normal, or use sidecar, "> I use legitimate activation tickets (albeit from 17 on a 15 device), so nothing is bypassed. Do you think this still plays a role?" soo vpn thingy must work well

**Comment by edwin170** [comment]
do you have discord or telegram ?
