### ISSUE TITLE
A10 stuck in dfu(maybe in pwned dfu).At the start "pwning device"

### ISSUE THREAD

**Issue by Denisboi** [edwin170/downr1n#2]
I have a macos, also it doesn't work on linux. What the terminal says: 
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID:0x1227
CPID:0x8010
Found the USB handle.
Stage: PATCH
ret:true
It doesn't end.I entered:"sudo ./downr1n.sh --downgrade 14.2" (with dualra1n the same)

**Comment by dualra1n** [comment]
If future restore finish to restore it, just force reboot and try --boot

**Comment by dualra1n** [comment]
Remember that that has a black screen that is called dfu false and you must force reboot every time that you see it

**Comment by Denisboi** [comment]
@dualra1n I have already tried force reboot.
Before this was during Futurerestore:
"did the futurerestore gave you a error like error: unable to send ibss component: unable to upload data to device, write (yes) to try again write (no) to exit yes" If I write yes, he asks to transfer the phone to dfu, and then he writes exactly the same. if  I select no, the script(futurerestore) closes. 
Yes, I  already restored the iPhone through 3utools (I have opencore, dualboot with Windows) However, this is my 3rd time trying to downgrade to 14.2 via downr1n.

**Comment by dualra1n** [comment]
> @dualra1n I have already tried force reboot.
> 
> Before this was during Futurerestore:
> 
> "did the futurerestore gave you a error like error: unable to send ibss component: unable to upload data to device, write (yes) to try again write (no) to exit yes" If I write yes, he asks to transfer the phone to dfu, and then he writes exactly the same. if  I select no, the script(futurerestore) closes. 
> 
> Yes, I  already restored the iPhone through 3utools (I have opencore, dualboot with Windows) However, this is my 3rd time trying to downgrade to 14.2 via downr1n.

If you are trying to downgrade a iPhone 8 or 8+ you need to choose a iOS 14.3 above

**Comment by dualra1n** [comment]
> @dualra1n I have already tried force reboot.
> 
> Before this was during Futurerestore:
> 
> "did the futurerestore gave you a error like error: unable to send ibss component: unable to upload data to device, write (yes) to try again write (no) to exit yes" If I write yes, he asks to transfer the phone to dfu, and then he writes exactly the same. if  I select no, the script(futurerestore) closes. 
> 
> Yes, I  already restored the iPhone through 3utools (I have opencore, dualboot with Windows) However, this is my 3rd time trying to downgrade to 14.2 via downr1n.

Try with iOS 14.3 or 14.8

**Comment by Denisboi** [comment]
@dualra1n But as I remember, a month ago I was able to    dualboot 14.2 through dualra1n. Is there a difference between ipsw for gsm model and global?

**Comment by dualra1n** [comment]
> @dualra1n But as I remember, a month ago I was able to    dualboot 14.2 through dualra1n. Is there a difference between ipsw for gsm model and global?

Probably when you downgrade

**Comment by dualra1n** [comment]
> @dualra1n But as I remember, a month ago I was able to dualboot 14.2 through dualra1n. Is there a difference between ipsw for gsm model and global?

sorry, i read bad, ah yes there is a ipsw different for gsm and global

**Comment by Denisboi** [comment]
@dualra1n It seems that the problem is due to the battery, a month ago when I installed 14.2 I had a different battery.

**Comment by Denisboi** [comment]
@dualra1n I removed the "pwn" and "reset" functions, instead I write commands in another window, the download is still, however, it stops at 5.3% after "connected to iphone 9,3 model d101ap, CPID 0x8010, bdid 0x0c
[================================] 100.0%Command completed succefuly
[===                                                                ] 5.3%"

**Comment by Denisboi** [comment]
@dualra1n It turned out 🤯, I just thought that when you press the power off and volume down button, you need to turn off the button after 4 seconds, and not after 8 seconds.

**Comment by Denisboi** [comment]
@dualra1n It turned out 🤯, I just thought that when you press the power off and volume down button, you need to turn off the button after 4 seconds, and not after 8 seconds

**Comment by edwin170** [comment]
> @dualra1n It turned out exploding_head, I just thought that when you press the power off and volume down button, you need to turn off the button after 4 seconds, and not after 8 seconds

i think after 4 when the script say it

**Comment by Aditya20110** [comment]
Better use palera1n dfu helper
