### ISSUE TITLE
No tethered booting.

### ISSUE THREAD

**Issue by JordanEJ** [edwin170/downr1n#20]
I am wanting to use this do downgrade my iPhone from 15.7.3 to 15.7.1. Do I have to boot my phone with a computer every time I want to start it, or can I just start it like normal? (Un-jailbroken)

**Comment by edwin170** [comment]
> I am wanting to use this do downgrade my iPhone from 15.7.3 to 15.7.1. Do I have to boot my phone with a computer every time I want to start it, or can I just start it like normal? (Un-jailbroken)

this is tethered, but you can use [dualra1n](https://github.com/dualra1n/dualra1n) it is semi-tethered which means that when you power off your device that will come back to the original ios.
