### ISSUE TITLE
How do i un downgrade

### ISSUE THREAD

**Issue by ieatbeansbruh** [edwin170/downr1n#21]
I figured out it was a tethered boot after i downgraded and now i want to remove the downgrade

**Comment by Aditya20110** [comment]
—restorerootfs

**Comment by dualra1n** [comment]
> I figured out it was a tethered boot after i downgraded and now i want to remove the downgrade

Using iTunes or 3utools you can restore your idevice and the iPhone will be restored

**Comment by Aditya20110** [comment]
My bad xd I thought u we’re talking about dualra1n

**Comment by Ijustplaymc** [comment]
restore with itunes or a compiled version of idevicerestore
