### ISSUE TITLE
Unable to boot device after restoring

### ISSUE THREAD

**Issue by whoeevee** [edwin170/downr1n#24]
I'm trying to downgrade iPhone 7 to 14.8
futurerestore completes successfully, but when I run `./downr1n.sh --boot` I get this:

```
[*] Pwning device
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: RESET
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SPRAY
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SETUP
ret: true
...
```

There are hundreds of `[IOKit] Waiting for the USB handle...` lines. 
Additionally, while executing device cyclically appears and disappears in Finder. It doesn't react to button combinations at all, so I can't re-enter DFU or perform force restart.

I used `./palera1n --dfuhelper` to exit DFU, it just prints `<Info>: Waiting for devices`, finishes and nothing happens. 
Sometimes it shows `<Error>: libirecovery error: -3 (Unable to connect to device)`.

I tried to downgrade multiple times, run `./downr1n.sh --boot` on another PC with Linux - behaviour the same. However, in this state,  I can restore and update device using Finder.

**Comment by dualra1n** [comment]
> I'm trying to downgrade iPhone 7 to 14.8
> 
> futurerestore completes successfully, but when I run `./downr1n.sh --boot` I get this:
> 
> 
> 
> ```
> 
> [*] Pwning device
> 
> usb_timeout: 5
> 
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> 
> CPID: 0x8010
> 
> Found the USB handle.
> 
> Stage: RESET
> 
> ret: true
> 
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> 
> CPID: 0x8010
> 
> Found the USB handle.
> 
> Stage: SPRAY
> 
> ret: true
> 
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> 
> CPID: 0x8010
> 
> Found the USB handle.
> 
> Stage: SETUP
> 
> ret: true
> 
> ...
> 
> ```
> 
> 
> 
> There are hundreds of `[IOKit] Waiting for the USB handle...` lines. 
> 
> Additionally, while executing device cyclically appears and disappears in Finder. It doesn't react to button combinations at all, so I can't re-enter DFU or perform force restart.
> 
> 
> 
> I used `./palera1n --dfuhelper` to exit DFU, it just prints `<Info>: Waiting for devices`, finishes and nothing happens. 
> 
> Sometimes it shows `<Error>: libirecovery error: -3 (Unable to connect to device)`.
> 
> 
> 
> I tried to downgrade multiple times, run `./downr1n.sh --boot` on another PC with Linux - behaviour the same. However, in this state,  I can restore and update device using Finder.

First: execute sudo ./binaries/$(uname)/gaster pwn, if that start to loop (like never finish) Force reboot when the loop stop please press home button (or volume down) and stop gaster by pressing ctrl + c in your computer and after 10 second execute the command again. Remember before you run --boot you must be sure that you are in the real dfu mode

**Comment by inkhog** [comment]
it fits me well. very nice of you

**Comment by edwin170** [comment]
> > > I'm trying to downgrade iPhone 7 to 14.8
> > > futurerestore completes successfully, but when I run `./downr1n.sh --boot` I get this:
> > > ```
> > > 
> > > [*] Pwning device
> > > 
> > > usb_timeout: 5
> > > 
> > > [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> > > 
> > > CPID: 0x8010
> > > 
> > > Found the USB handle.
> > > 
> > > Stage: RESET
> > > 
> > > ret: true
> > > 
> > > [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> > > 
> > > CPID: 0x8010
> > > 
> > > Found the USB handle.
> > > 
> > > Stage: SPRAY
> > > 
> > > ret: true
> > > 
> > > [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> > > 
> > > CPID: 0x8010
> > > 
> > > Found the USB handle.
> > > 
> > > Stage: SETUP
> > > 
> > > ret: true
> > > 
> > > ...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > There are hundreds of `[IOKit] Waiting for the USB handle...` lines.
> > > Additionally, while executing device cyclically appears and disappears in Finder. It doesn't react to button combinations at all, so I can't re-enter DFU or perform force restart.
> > > I used `./palera1n --dfuhelper` to exit DFU, it just prints `<Info>: Waiting for devices`, finishes and nothing happens.
> > > Sometimes it shows `<Error>: libirecovery error: -3 (Unable to connect to device)`.
> > > I tried to downgrade multiple times, run `./downr1n.sh --boot` on another PC with Linux - behaviour the same. However, in this state,  I can restore and update device using Finder.
> > 
> > 
> > First: execute sudo ./binaries/$(uname)/gaster pwn, if that start to loop (like never finish) Force reboot when the loop stop please press home button (or volume down) and stop gaster by pressing ctrl + c in your computer and after 10 second execute the command again. Remember before you run --boot you must be sure that you are in the real dfu mode
> 
> It works. Thanks!

that's cool :)
