### ISSUE TITLE
Any way to install Unc0ver Jailbreak after the downgrade?

### ISSUE THREAD

**Issue by pedrocacintra** [edwin170/downr1n#27]
Is it possible to downgrade and then JB with Unc0ver?

 If not i could pay for a solution that allowed that, I really need to downgrade my IOS 15.7.5 to 14.2 Unc0ver to install a particular tweak. My telegram is @pedrocintraa

**Comment by edwin170** [comment]
> Is it possible to downgrade and then JB with Unc0ver?
> 
> If not i could pay for a solution that allowed that, I really need to downgrade my IOS 15.7.5 to 14.2 Unc0ver to install a particular tweak. My telegram is @pedrocintraa

you can't jailbreak with unc0ver however you can using taurine or the dualra1n-loader one. using taurine probably you can.

**Comment by pedrocacintra** [comment]
The tweak I need only woks with Unc0ver unfortunately, know any possible solutions?

**Comment by pedrocacintra** [comment]
It's a tweak to replace the Iphone camera with a video, I read on Reddit that it just worked with unc0ver. 
The reddit discussion: https://www.reddit.com/r/jailbreak/comments/xc6hda/question_would_it_be_possible_to_get_something/

Here's the link for the download: https://github.com/wordgege/iPhone-VCAM/tree/master/release. 

There's also a similar one in BigBoss, but from what ive read i just the same thing repackaged: https://www.ios-repo-updates.com/repository/bigboss/package/com.xnxj.fakecamera/. 

If you can find me any solution to allow to use it I can pay you 50$. The only thing I need is that it is on ios 14.x, cause the app I want to use it with only supports IOS 14 and upwards.

**Comment by edwin170** [comment]
> It's a tweak to replace the Iphone camera with a video, I read on Reddit that it just worked with unc0ver. The reddit discussion: https://www.reddit.com/r/jailbreak/comments/xc6hda/question_would_it_be_possible_to_get_something/
> 
> Here's the link for the download: https://github.com/wordgege/iPhone-VCAM/tree/master/release.
> 
> There's also a similar one in BigBoss, but from what ive read i just the same thing repackaged: https://www.ios-repo-updates.com/repository/bigboss/package/com.xnxj.fakecamera/.
> 
> If you can find me any solution to allow to use it I can pay you 50$. The only thing I need is that it is on ios 14.x, cause the app I want to use it with only supports IOS 14 and upwards.

ahhh didn't work on the dualboot using dualra1n-loader sadly

**Comment by pedrocacintra** [comment]
Thanks a lot for the help anyway!

**Comment by edwin170** [comment]
> Thanks a lot for the help anyway!

you're wellcome
