### ISSUE TITLE
Stuck on creating ramdisk

### ISSUE THREAD

**Issue by MkmSys** [edwin170/downr1n#29]
iPhone 6s, IOS 15.7.5 have jailbreak, rootless
![IMG20230712221816](https://github.com/edwin170/downr1n/assets/120376858/356741de-bc7d-40c1-a2e8-2c0e94e13840)

**Comment by edwin170** [comment]
> iPhone 6s, IOS 15.7.5 have jailbreak, rootless ![IMG20230712221816](https://user-images.githubusercontent.com/120376858/253019529-356741de-bc7d-40c1-a2e8-2c0e94e13840.jpg)


maybe it is because the internet or the usb
