### ISSUE TITLE
What about ios 16 , will it even work in future?

### ISSUE THREAD

**Issue by aditya11110** [edwin170/downr1n#3]
Title!

**Comment by dualra1n** [comment]
Mmm idk, I don't have a a11 to test it on iOS 16 but you can try it

**Comment by aditya11110** [comment]
Ok,

**Comment by aditya11110** [comment]
I have iphone x 10,3 ios 16.3 i will try it btw add me in contributers bcz i made tutorial and i also tested!

**Comment by edwin170** [comment]
> I have iphone x 10,3 ios 16.3 i will try it btw add me in contributers bcz i made tutorial and i also tested!

i wont put anything about tutorials on this proyects. and yes you can try it on your iphone good luck
