### ISSUE TITLE
Error: Futurerestore is outdated! Please download the latest futurerestore!

### ISSUE THREAD

**Issue by promisfx2222** [edwin170/downr1n#30]
tranthanhtu@tranthanhtu-VivoBook-15-ASUS-Laptop-X507MA-X507MA:~/Desktop/downr1n$ ./binaries/Linux/futurerestore -t blobs/iPhone9,2-14.3.shsh --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --latest-baseband ipsw/iPhone_5.5_P3_14.3_18C66_Restore.ipsw
Version: v2.0.0-test(ca45da2fb075ccf2921bbc04d5aef74e3e71b743-304)
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-DEBUG
libipatcher version: 0.88-1e855d70c84419014e363bdbcaead7b145fe3e1f-DEBUG
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes
Checking for updates...
Error: Futurerestore is outdated! Please download the latest futurerestore! exitting...

**Comment by dualra1n** [comment]
> tranthanhtu@tranthanhtu-VivoBook-15-ASUS-Laptop-X507MA-X507MA:~/Desktop/downr1n$ ./binaries/Linux/futurerestore -t blobs/iPhone9,2-14.3.shsh --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --latest-baseband ipsw/iPhone_5.5_P3_14.3_18C66_Restore.ipsw Version: v2.0.0-test(ca45da2fb075ccf2921bbc04d5aef74e3e71b743-304) img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-DEBUG libipatcher version: 0.88-1e855d70c84419014e363bdbcaead7b145fe3e1f-DEBUG Odysseus for 32-bit support: yes Odysseus for 64-bit support: yes Checking for updates... Error: Futurerestore is outdated! Please download the latest futurerestore! exitting...

hello i updated the futurerestore but i don't have a device to test it rn, could you please try with the dev brach?. if you want to try it please do this command, command1: git checkout dev (use sudo if needed), command2: ./downr1n.sh --downgrade (vers).

**Comment by promisfx2222** [comment]
tranthanhtu@tranthanhtu-VivoBook-15-ASUS-Laptop-X507MA-X507MA:~/downr1n$ '/home/tranthanhtu/downr1n/binaries/Linux/futurerestore' -t blobs/iPhone9,2-14.3.shsh --use-pwndfu --latest-sep --latest-baseband ipsw/iPhone_5.5_P3_14.3_18C66_Restore.ipsw
Version: v2.0.0-test(50e1b49d4e3b7896f7668644345c664beaaeb063-305)
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
libipatcher version: 0.88-1e855d70c84419014e363bdbcaead7b145fe3e1f-RELEASE
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes
Checking for updates...
Futurerestore is up to date!
[INFO] 64-bit device detected
futurerestore init done
futurerestore: failed with exception:
[exception]:
what=failed to load APTicket at blobs/iPhone9,2-14.3.shsh

code=28114998
line=429
file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp
commit count=305
commit sha  =50e1b49d4e3b7896f7668644345c664beaaeb063

**Comment by promisfx2222** [comment]
If i Press ENTER to continue <-
Version: v2.0.0-test(50e1b49d4e3b7896f7668644345c664beaaeb063-305)
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
libipatcher version: 0.88-1e855d70c84419014e363bdbcaead7b145fe3e1f-RELEASE
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes
Checking for updates...
Futurerestore is up to date!
futurerestore: failed with exception:
[exception]:
what=can't init, no device found

code=20840493
line=318
file=/tmp/Builder/repos/futurerestore/src/main.cpp
commit count=305
commit sha  =50e1b49d4e3b7896f7668644345c664beaaeb063

I have this error! Thanks

**Comment by promisfx2222** [comment]
Checking if Baseband is being signed...
Sending TSS request attempt 1... response successfully received
Baseband is being signed!
Downloading the latest firmware components...
Finished downloading the latest firmware components!
Found device in DFU mode
requesting to get into pwnRecovery later
Found device in DFU mode
Identified device as d11ap, iPhone9,2
Extracting BuildManifest from iPSW
Product version: 14.3
Product build: 18C66 Major: 18
Device supports Image4: true
checking if the APTicket is valid for this restore...
Verified ECID in APTicket matches the device's ECID
checking if the APTicket is valid for this restore...
Verified ECID in APTicket matches the device's ECID
[IMG4TOOL] checking buildidentity 0:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 1:
[IMG4TOOL] checking buildidentity matches board ... YES
[IMG4TOOL] checking buildidentity has all required hashes:
[IMG4TOOL] checking hash for "AOP"                     OK (untrusted)
[IMG4TOOL] checking hash for "Ap,SystemVolumeCanonicalMetadata"BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "AppleLogo"               BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BasebandFirmware"        IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "BatteryCharging0"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryCharging1"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryFull"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryLow0"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryLow1"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryPlugin"           BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "DeviceTree"              BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Homer"                   OK (untrusted)
[IMG4TOOL] checking hash for "KernelCache"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "LLB"                     BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Liquid"                  BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "OS"                      BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RecoveryMode"            BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreDeviceTree"       BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreKernelCache"      BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreLogo"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreRamDisk"          BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreSEP"              BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreTrustCache"       BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "SE,Bootloader"           IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "SE,Firmware"             IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "SE,MigrationOS"          IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "SE,OS"                   IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "SEP"                     BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "StaticTrustCache"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "SystemVolume"            BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "ftap"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "ftsp"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "iBEC"                    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "iBSS"                    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "iBoot"                   BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "rfta"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "rfts"                    IGN (no digest in BuildManifest)

failed verification with error:
[exception]:
what=verification failed!
code=84279308
line=1286
file=img4tool.cpp
commit count=197
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f
[IMG4TOOL] checking buildidentity 2:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 3:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 4:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 5:
[IMG4TOOL] checking buildidentity matches board ... YES
[IMG4TOOL] checking buildidentity has all required hashes:
[IMG4TOOL] checking hash for "AOP"                     OK (untrusted)
[IMG4TOOL] checking hash for "Ap,SystemVolumeCanonicalMetadata"BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "AppleLogo"               BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BasebandFirmware"        IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "BatteryCharging0"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryCharging1"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryFull"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryLow0"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryLow1"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryPlugin"           BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "DeviceTree"              BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Homer"                   OK (untrusted)
[IMG4TOOL] checking hash for "KernelCache"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "LLB"                     BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Liquid"                  BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "OS"                      BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RecoveryMode"            BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreDeviceTree"       BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreKernelCache"      BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreLogo"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreRamDisk"          BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreSEP"              BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreTrustCache"       BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "SE,Bootloader"           IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "SE,Firmware"             IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "SE,MigrationOS"          IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "SE,OS"                   IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "SEP"                     BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "StaticTrustCache"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "SystemVolume"            BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "ftap"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "ftsp"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "iBEC"                    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "iBSS"                    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "iBoot"                   BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "rfta"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "rfts"                    IGN (no digest in BuildManifest)

failed verification with error:
[exception]:
what=verification failed!
code=84279308
line=1286
file=img4tool.cpp
commit count=197
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f
[IMG4TOOL] checking buildidentity 6:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 7:
[IMG4TOOL] checking buildidentity matches board ... NO
[WARNING] NOT VALIDATING SHSH BLOBS IM4M!
[Error] BuildIdentity selected for restore does not match APTicket

BuildIdentity selected for restore:
BuildNumber : 18C66
BuildTrain : AzulC
DeviceClass : d11ap
FDRSupport : YES
MobileDeviceMinVersion : 1253
RestoreBehavior : Erase
Variant : Customer Erase Install (IPSW)

BuildIdentity is valid for the APTicket:
IM4M is not valid for any restore within the Buildmanifest
This APTicket can't be used for restoring this firmware
[WARNING] NOT VALIDATING SHSH BLOBS!
Variant: Customer Erase Install (IPSW)
This restore will erase all device data.
Device found in DFU Mode.
Getting firmware keys for: d11ap
Cleaning up...
[exception]:
what=getting keys failed with error: 14745615 (failed to get FirmwareJson from Server). Are keys publicly available?
code=41680950
line=636
file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp
commit count=305
commit sha  =50e1b49d4e3b7896f7668644345c664beaaeb063
Done: restoring failed!

I have this error! Thanks guy

**Comment by dualra1n** [comment]
> Checking if Baseband is being signed... Sending TSS request attempt 1... response successfully received Baseband is being signed! Downloading the latest firmware components... Finished downloading the latest firmware components! Found device in DFU mode requesting to get into pwnRecovery later Found device in DFU mode Identified device as d11ap, iPhone9,2 Extracting BuildManifest from iPSW Product version: 14.3 Product build: 18C66 Major: 18 Device supports Image4: true checking if the APTicket is valid for this restore... Verified ECID in APTicket matches the device's ECID checking if the APTicket is valid for this restore... Verified ECID in APTicket matches the device's ECID [IMG4TOOL] checking buildidentity 0: [IMG4TOOL] checking buildidentity matches board ... NO [IMG4TOOL] checking buildidentity 1: [IMG4TOOL] checking buildidentity matches board ... YES [IMG4TOOL] checking buildidentity has all required hashes: [IMG4TOOL] checking hash for "AOP" OK (untrusted) [IMG4TOOL] checking hash for "Ap,SystemVolumeCanonicalMetadata"BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "AppleLogo" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BasebandFirmware" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "BatteryCharging0" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryCharging1" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryFull" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryLow0" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryLow1" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryPlugin" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "DeviceTree" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "Homer" OK (untrusted) [IMG4TOOL] checking hash for "KernelCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "LLB" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "Liquid" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "OS" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RecoveryMode" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreDeviceTree" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreKernelCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreLogo" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreRamDisk" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreSEP" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreTrustCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "SE,Bootloader" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "SE,Firmware" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "SE,MigrationOS" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "SE,OS" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "SEP" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "StaticTrustCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "SystemVolume" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "ftap" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "ftsp" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "iBEC" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "iBSS" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "iBoot" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "rfta" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "rfts" IGN (no digest in BuildManifest)
> 
> failed verification with error: [exception]: what=verification failed! code=84279308 line=1286 file=img4tool.cpp commit count=197 commit sha =aca6cf005c94caf135023263cbb5c61a0081804f [IMG4TOOL] checking buildidentity 2: [IMG4TOOL] checking buildidentity matches board ... NO [IMG4TOOL] checking buildidentity 3: [IMG4TOOL] checking buildidentity matches board ... NO [IMG4TOOL] checking buildidentity 4: [IMG4TOOL] checking buildidentity matches board ... NO [IMG4TOOL] checking buildidentity 5: [IMG4TOOL] checking buildidentity matches board ... YES [IMG4TOOL] checking buildidentity has all required hashes: [IMG4TOOL] checking hash for "AOP" OK (untrusted) [IMG4TOOL] checking hash for "Ap,SystemVolumeCanonicalMetadata"BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "AppleLogo" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BasebandFirmware" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "BatteryCharging0" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryCharging1" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryFull" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryLow0" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryLow1" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryPlugin" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "DeviceTree" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "Homer" OK (untrusted) [IMG4TOOL] checking hash for "KernelCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "LLB" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "Liquid" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "OS" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RecoveryMode" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreDeviceTree" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreKernelCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreLogo" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreRamDisk" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreSEP" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreTrustCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "SE,Bootloader" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "SE,Firmware" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "SE,MigrationOS" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "SE,OS" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "SEP" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "StaticTrustCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "SystemVolume" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "ftap" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "ftsp" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "iBEC" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "iBSS" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "iBoot" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "rfta" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "rfts" IGN (no digest in BuildManifest)
> 
> failed verification with error: [exception]: what=verification failed! code=84279308 line=1286 file=img4tool.cpp commit count=197 commit sha =aca6cf005c94caf135023263cbb5c61a0081804f [IMG4TOOL] checking buildidentity 6: [IMG4TOOL] checking buildidentity matches board ... NO [IMG4TOOL] checking buildidentity 7: [IMG4TOOL] checking buildidentity matches board ... NO [WARNING] NOT VALIDATING SHSH BLOBS IM4M! [Error] BuildIdentity selected for restore does not match APTicket
> 
> BuildIdentity selected for restore: BuildNumber : 18C66 BuildTrain : AzulC DeviceClass : d11ap FDRSupport : YES MobileDeviceMinVersion : 1253 RestoreBehavior : Erase Variant : Customer Erase Install (IPSW)
> 
> BuildIdentity is valid for the APTicket: IM4M is not valid for any restore within the Buildmanifest This APTicket can't be used for restoring this firmware [WARNING] NOT VALIDATING SHSH BLOBS! Variant: Customer Erase Install (IPSW) This restore will erase all device data. Device found in DFU Mode. Getting firmware keys for: d11ap Cleaning up... [exception]: what=getting keys failed with error: 14745615 (failed to get FirmwareJson from Server). Are keys publicly available? code=41680950 line=636 file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp commit count=305 commit sha =50e1b49d4e3b7896f7668644345c664beaaeb063 Done: restoring failed!
> 
> I have this error! Thanks guy

alright great, you are very near. execute this command: git pull. after that execute this command to install all modules requeried for wikiproxy.py: python3 -m pip install fastapi aiohttp ujson wikitextparser uvicorn pyimg4. after this you can try again and this will work

**Comment by promisfx2222** [comment]
Working! Thanks guys

**Comment by dualra1n** [comment]
> Working! Thanks guys

so did you get downgrade ?
