### ISSUE TITLE
Stuck in [libusb]

### ISSUE THREAD

**Issue by promisfx2222** [edwin170/downr1n#35]
![image](https://github.com/edwin170/downr1n/assets/139648283/d5a3f502-cdb3-4482-9998-21f0a1119c94)

I try to install this ''python3 -m pip install pyliblzfse'' but not working THANKS

**Comment by promisfx2222** [comment]
I try ''sudo python3 -m pip install pyliblzfse'' and it's working THANKS GUY

**Comment by promisfx2222** [comment]
tranthanhtu@tranthanhtu-VivoBook-15-ASUS-Laptop-X507MA-X507MA:~/Desktop/downr1n$ sudo ./downr1n.sh --downgrade 14.3
[*] Command ran: sudo ./downr1n.sh --downgrade 14.3
[17:11:28.665][3] usbmuxd v1.1.1 starting up
[17:11:28.665][3] Using libusb 1.0.25
[17:11:28.672][3] Initialization complete
[17:11:28.673][3] Connecting to new device on location 0x10015 as ID 1
[17:11:28.673][3] Connected to v2.0 device 1 on location 0x10015 with serial number ramdisk tool Sep 18 2022 20:14:43
[17:11:28.693][2] device_control_input: Got unhandled payload type 5
downr1n | Version 1.0
Created by edwin, thanks sunst0rm, and all people creator of path file boot

[*] Waiting for devices
[*] Detected ramdisk mode device
[*] Rebooting device in SSH Ramdisk
[17:12:04.940][3] Removed device 1 on location 0x10015
[*] Waiting for device in recovery mode
[*] Getting device info...
0x8010
d11ap
iPhone9,2
[*] To get into DFU mode, you will be guided through 2 steps:
[*] Press any key when ready for DFU mode
Get ready (0)
Release side button, but keep holding volume down (9)
Release side button, but keep holding volume down (2)
[*] Device entered DFU!
[*] Continuing...
extracting ipsw, hang on please ...
Archive:  ipsw/iPhone_5.5_P3_14.3_18C66_Restore.ipsw
'ipsw/extracted//BuildManifest.plist' -> 'work/BuildManifest.plist'
now the IPSW is extracted
[*] Creating ramdisk
[-] Ramdisk is already created so SKIPPING ...
[*] Booting ramdisk
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Waiting for the ramdisk to finish booting
libusb: warning [op_get_configuration] device unconfigured
libusb: error [op_get_active_config_descriptor] device unconfigured
[17:13:22.720][3] Could not get old configuration descriptor for device 1-28: LIBUSB_ERROR_NOT_FOUND
[17:13:22.738][3] Connecting to new device on location 0x1001c as ID 2
[17:13:22.828][3] Connected to v2.0 device 2 on location 0x1001c with serial number ramdisk tool Sep 18 2022 20:14:43
[17:13:22.829][2] device_control_input: Got unhandled payload type 5
[17:13:23.096][2] device_control_input: Got unhandled payload type 5
Error connecting to device: No error information
seputil: Gigalocker file (/mnt7/743709FC-C851-5EE9-B116-F761419495D1.gl) exists
seputil: Gigalocker initialization completed
sepi digest (48 bytes): 451bbdb5e0197205ff007e7982b0eba164843974ed18f53bd75dfa3d3647b4d96719de1abc44d667f080522320ababb7
sepi nonce (20 bytes): b2d753f3be5ef5ce43a84df12f094423cf009924
rsep digest (48 bytes): 2cab42198c0eb04d805bc4842139fd2853eaf6aa44bc6936da1b9bcc6ebffdd1edb84fb3f081d9208dac7718ff7a3dcd
rsep nonce (20 bytes): b2d753f3be5ef5ce43a84df12f094423cf009924
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
Compiled with plist: YES
Saved IM4M to work/IM4M
Dumpped SHSH
[*] Patching kernel ...
Reading work/kernelcache...
[NOTE] Image4 payload data is LZFSE compressed, decompressing...
Extracted Image4 payload data to: work/kcache.raw
sending incremental file list
kcache.raw

sent 90 bytes  received 44.632 bytes  9.938,22 bytes/sec
total size is 40.566.812  speedup is 907,09
sending incremental file list
Kernel15patcher.ios

sent 35.598 bytes  received 35 bytes  71.266,00 bytes/sec
total size is 128.736  speedup is 3,61
./downr1n.sh: line 794: [: too many arguments
receiving incremental file list
kcache.patched

sent 43 bytes  received 15.030.522 bytes  4.294.447,14 bytes/sec
total size is 40.566.784  speedup is 2,70
[17:14:32.945][3] Removed device 2 on location 0x1001c
[*] To get into DFU mode, you will be guided through 2 steps:
[*] Press any key when ready for DFU mode
Get ready (0)
Release side button, but keep holding volume down (9)
Release side button, but keep holding volume down (3)
[*] Device entered DFU!
[* ]Patchimg some boot files...
trst
[*] Finished moving the boot files to work
usb_timeout: 5
usb_abort_timeout_min: 0
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.

![image](https://github.com/edwin170/downr1n/assets/139648283/6de577e1-7098-4b66-887f-8ecd23034a22)

stuck in here

**Comment by edwin170** [comment]
> tranthanhtu@tranthanhtu-VivoBook-15-ASUS-Laptop-X507MA-X507MA:~/Desktop/downr1n$ sudo ./downr1n.sh --downgrade 14.3 [*] Command ran: sudo ./downr1n.sh --downgrade 14.3 [17:11:28.665][3] usbmuxd v1.1.1 starting up [17:11:28.665][3] Using libusb 1.0.25 [17:11:28.672][3] Initialization complete [17:11:28.673][3] Connecting to new device on location 0x10015 as ID 1 [17:11:28.673][3] Connected to v2.0 device 1 on location 0x10015 with serial number ramdisk tool Sep 18 2022 20:14:43 [17:11:28.693][2] device_control_input: Got unhandled payload type 5 downr1n | Version 1.0 Created by edwin, thanks sunst0rm, and all people creator of path file boot
> 
> [_] Waiting for devices [_] Detected ramdisk mode device [_] Rebooting device in SSH Ramdisk [17:12:04.940][3] Removed device 1 on location 0x10015 [_] Waiting for device in recovery mode [_] Getting device info... 0x8010 d11ap iPhone9,2 [_] To get into DFU mode, you will be guided through 2 steps: [_] Press any key when ready for DFU mode Get ready (0) Release side button, but keep holding volume down (9) Release side button, but keep holding volume down (2) [_] Device entered DFU! [_] Continuing... extracting ipsw, hang on please ... Archive: ipsw/iPhone_5.5_P3_14.3_18C66_Restore.ipsw 'ipsw/extracted//BuildManifest.plist' -> 'work/BuildManifest.plist' now the IPSW is extracted [_] Creating ramdisk [-] Ramdisk is already created so SKIPPING ... [_] Booting ramdisk usb_timeout: 5 [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: RESET ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: SPRAY ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: SETUP ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Now you can boot untrusted images. usb_timeout: 5 [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 Found the USB handle. [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [_] Waiting for the ramdisk to finish booting libusb: warning [op_get_configuration] device unconfigured libusb: error [op_get_active_config_descriptor] device unconfigured [17:13:22.720][3] Could not get old configuration descriptor for device 1-28: LIBUSB_ERROR_NOT_FOUND [17:13:22.738][3] Connecting to new device on location 0x1001c as ID 2 [17:13:22.828][3] Connected to v2.0 device 2 on location 0x1001c with serial number ramdisk tool Sep 18 2022 20:14:43 [17:13:22.829][2] device_control_input: Got unhandled payload type 5 [17:13:23.096][2] device_control_input: Got unhandled payload type 5 Error connecting to device: No error information seputil: Gigalocker file (/mnt7/743709FC-C851-5EE9-B116-F761419495D1.gl) exists seputil: Gigalocker initialization completed sepi digest (48 bytes): 451bbdb5e0197205ff007e7982b0eba164843974ed18f53bd75dfa3d3647b4d96719de1abc44d667f080522320ababb7 sepi nonce (20 bytes): b2d753f3be5ef5ce43a84df12f094423cf009924 rsep digest (48 bytes): 2cab42198c0eb04d805bc4842139fd2853eaf6aa44bc6936da1b9bcc6ebffdd1edb84fb3f081d9208dac7718ff7a3dcd rsep nonce (20 bytes): b2d753f3be5ef5ce43a84df12f094423cf009924 img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE Compiled with plist: YES Saved IM4M to work/IM4M Dumpped SHSH [*] Patching kernel ... Reading work/kernelcache... [NOTE] Image4 payload data is LZFSE compressed, decompressing... Extracted Image4 payload data to: work/kcache.raw sending incremental file list kcache.raw
> 
> sent 90 bytes received 44.632 bytes 9.938,22 bytes/sec total size is 40.566.812 speedup is 907,09 sending incremental file list Kernel15patcher.ios
> 
> sent 35.598 bytes received 35 bytes 71.266,00 bytes/sec total size is 128.736 speedup is 3,61 ./downr1n.sh: line 794: [: too many arguments receiving incremental file list kcache.patched
> 
> sent 43 bytes received 15.030.522 bytes 4.294.447,14 bytes/sec total size is 40.566.784 speedup is 2,70 [17:14:32.945][3] Removed device 2 on location 0x1001c [_] To get into DFU mode, you will be guided through 2 steps: [_] Press any key when ready for DFU mode Get ready (0) Release side button, but keep holding volume down (9) Release side button, but keep holding volume down (3) [_] Device entered DFU! [_ ]Patchimg some boot files... trst [*] Finished moving the boot files to work usb_timeout: 5 usb_abort_timeout_min: 0 [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: RESET ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: SETUP ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: SPRAY ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Now you can boot untrusted images. [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 Found the USB handle.
> 
> ![image](https://user-images.githubusercontent.com/139648283/263987385-6de577e1-7098-4b66-887f-8ecd23034a22.png)
> 
> stuck in here

if you try that again does it always stuck there ?

**Comment by promisfx2222** [comment]
I try 5 times and it's not working 5 times stuck in libusb

**Comment by edwin170** [comment]
> I try 5 times and it's not working 5 times stuck in libusb

git pull and try it again
