### ISSUE TITLE
stuck at pylzss not installed

### ISSUE THREAD

**Issue by jasonj0820** [edwin170/downr1n#39]
Hi, when it is near the end and almost starting to boot up, the message appeared: 
"[*] Patching kernel ...
Reading work/kernelcache...
[NOTE] Image4 payload data is LZSS compressed, decompressing...
RuntimeError: pylzss not installed, cannot use LZSS compression" 

I tried install pylzss manually and update python but no dice.

**Comment by jasonj0820** [comment]
also this: "libusb: warning [op_get_configuration] device unconfigured
libusb: error [op_get_active_config_descriptor] device unconfigured
[17:39:29.664][3] Could not get old configuration descriptor for device 1-12: LIBUSB_ERROR_NOT_FOUND
[17:39:29.666][3] Connecting to new device on location 0x1000c as ID 2
[17:39:29.768][3] Connected to v2.0 device 2 on location 0x1000c with serial number ramdisk tool Sep 18 2022 20:14:43
[17:39:29.769][2] device_control_input: Got unhandled payload type 5
[17:39:30.092][2] device_control_input: Got unhandled payload type 5
Error connecting to device: No error information
seputil: Gigalocker file (/mnt7/9AD9337E-2FED-517A-8218-72ED70655D64.gl) exists
seputil: Gigalocker initialization completed
sepi digest (20 bytes): 20402a449340e9e619921e6b2fab74abb8bb2fdd
sepi nonce (20 bytes): 96376e5d4855ac9d21c2752a1ed320333109b500
rsep digest (20 bytes): 17aea80c5aca463d7a7296027afd32c81a2eb60b
rsep nonce (20 bytes): 96376e5d4855ac9d21c2752a1ed320333109b500
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
Compiled with plist: YES
Saved IM4M to work/IM4M
Dumpped SHSH
[*] Patching kernel ...
Reading work/kernelcache...
[NOTE] Image4 payload data is LZSS compressed, decompressing...
RuntimeError: pylzss not installed, cannot use LZSS compression"

**Comment by jasonj0820** [comment]
nvm it works now

**Comment by Abkfc** [comment]
how do you fix it
