### ISSUE TITLE
I don't get it. Can you not downgrade to iOS 16 or iOS 16 isn't supported at all?

### ISSUE THREAD

**Issue by Section3622-153** [edwin170/downr1n#40]
I think the latter. But could someone explain it lmao. For example I have my iPhone 8 Plus on iOS 16.6 jailbroken with palera1n. If I decide to completely reset using itunes and then can I use this guide to downgrade to iOS 14 or iOS 15?

**Comment by edwin170** [comment]
> I think the latter. But could someone explain it lmao. For example I have my iPhone 8 Plus on iOS 16.6 jailbroken with palera1n. If I decide to completely reset using itunes and then can I use this guide to downgrade to iOS 14 or iOS 15?

I tried on my iPad on iOS 16.6 and it worked somehow idk, you can try reset using iTunes and then use downr1n to downgrade, I am not sure if it gonna works but you can try that, remember if you have data on your iOS please don't give a try because you are gonna break the iOS

**Comment by Section3622-153** [comment]
Is breaking the iOS definite? Also what services will be broken? Such as iCloud or iMessage?

**Comment by dualra1n** [comment]
> Is breaking the iOS definite? Also what services will be broken? Such as iCloud or iMessage?

If you are on iOS 15 and then you downgrade the downgrade won't break any apple service, if you are on ios 16 when you downgrade it will break the setup which is where you set the iCloud so you will have to bypass it by using tools to bypass iCloud, if the downgrade fails, the ios 16 will be broken so you must restore with iTunes to restore (so it won't break it definitive) (definitive = forever) I understand that for definitive

**Comment by Section3622-153** [comment]
So all I would need to do is a iCloud bypass?

**Comment by Section3622-153** [comment]
Have restored, did get an error for a python module not being installed halfway thru so I installed that. Currently resetting using itunes again then hopefully it will downgrade when I do use the script.

**Comment by anvarkhamidov** [comment]
@Section3622-153 Could you downgrade successfully from iOS 16 to 15? if yes? then could you give details and instructions please?

**Comment by Section3622-153** [comment]
Nope it didn't work tried everything: sudo, the dualbooting as well. Best bet is to just stay on the version you're on and wait for a more stable tool.
