### ISSUE TITLE
stuck on "$dir"/gaster decrypt work/"$(awk "/""${model}""/{x=1}x&&/iBSS[.]/{print;exit}" work/BuildManifest.plist | grep '<string>' |cut -d\> -f2 |cut -d\< -f1 | sed 's/Firmware[/]dfu[/]//')" work/iBSS.dec 

### ISSUE THREAD

**Issue by lgtoroe** [edwin170/downr1n#42]
./downr1n.sh --downgrade 14.8

line 904
"$dir"/gaster decrypt work/"$(awk "/""${model}""/{x=1}x&&/iBSS[.]/{print;exit}" work/BuildManifest.plist | grep '<string>' |cut -d\> -f2 |cut -d\< -f1 | sed 's/Firmware[/]dfu[/]//')" work/iBSS.dec 

result 

Get ready (0)
Release power button, but keep holding home button (9)
Release power button, but keep holding home button (2)
[*] Device entered DFU!
[* ]Patchimg some boot files...
trst
[*] Finished moving the boot files to work
[*] Pwning device
usb_timeout: 5
usb_abort_timeout_min: 0
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8000
Found the USB handle.
Stage: RESET
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8000
Found the USB handle.
Stage: SETUP
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8000
Found the USB handle.
Stage: SPRAY
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8000
Found the USB handle.
Stage: PATCH
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8000
Found the USB handle.
Now you can boot untrusted images.
[*] Resetting DFU state
usb_timeout: 5
usb_abort_timeout_min: 0
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
usb_timeout: 5
usb_abort_timeout_min: 0
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8000
Found the USB handle.
Now you can boot untrusted images.
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.

SO: Catalina 10.15.7

please help me ! 

some weird 

sent 96 bytes  received 1146 bytes  828.00 bytes/sec
total size is 128736  speedup is 103.65
./downr1n.sh: line 833: [: too many arguments  <-- here 
receiving file list ... done
kcache.patched

line 833

 if [ ! $(remote_cmd "/mnt1/private/var/root/kpf15.ios /mnt1/System/Library/Caches/com.apple.kernelcaches/kcache.raw /mnt1/System/Library/Caches/com.apple.kernelcaches/kcache.patched") ]; then
        echo "you have the kernelpath already installed "
    fi

**Comment by edwin170** [comment]
what exactly is the error, can you just take a screenshot where it get stuck please

**Comment by lgtoroe** [comment]
moment of crash ....

https://s3.bg.simios.live/ss/2.jpeg

message comment

https://s3.bg.simios.live/ss/1.jpeg

iPhone  6S

**Comment by edwin170** [comment]
sooo yeah, downr1n decrypt somehow is broken, so I will need to check it out when I get time, sorry for it didn't work and I will check it soon thx

**Comment by edwin170** [comment]
> moment of crash ....
> 
> https://s3.bg.simios.live/ss/2.jpeg
> 
> message comment
> 
> https://s3.bg.simios.live/ss/1.jpeg
> 
> iPhone 6S

please git pull, and try it again

**Comment by edwin170** [comment]
> ./downr1n.sh --downgrade 14.8
> 
> line 904 "$dir"/gaster decrypt work/"$(awk "/""${model}""/{x=1}x&&/iBSS[.]/{print;exit}" work/BuildManifest.plist | grep '' |cut -d> -f2 |cut -d< -f1 | sed 's/Firmware[/]dfu[/]//')" work/iBSS.dec
> 
> result
> 
> Get ready (0) Release power button, but keep holding home button (9) Release power button, but keep holding home button (2) [_] Device entered DFU! [_ ]Patchimg some boot files... trst [_] Finished moving the boot files to work [_] Pwning device usb_timeout: 5 usb_abort_timeout_min: 0 [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8000 Found the USB handle. Stage: RESET ret: true [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8000 Found the USB handle. Stage: SETUP ret: true [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8000 Found the USB handle. Stage: SPRAY ret: true [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8000 Found the USB handle. Stage: PATCH ret: true [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8000 Found the USB handle. Now you can boot untrusted images. [*] Resetting DFU state usb_timeout: 5 usb_abort_timeout_min: 0 [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 Found the USB handle. usb_timeout: 5 usb_abort_timeout_min: 0 [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8000 Found the USB handle. Now you can boot untrusted images. [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 Found the USB handle.
> 
> SO: Catalina 10.15.7
> 
> please help me !
> 
> some weird
> 
> sent 96 bytes received 1146 bytes 828.00 bytes/sec total size is 128736 speedup is 103.65 ./downr1n.sh: line 833: [: too many arguments <-- here receiving file list ... done kcache.patched
> 
> line 833
> 
> if [ ! $(remote_cmd "/mnt1/private/var/root/kpf15.ios /mnt1/System/Library/Caches/com.apple.kernelcaches/kcache.raw /mnt1/System/Library/Caches/com.apple.kernelcaches/kcache.patched") ]; then echo "you have the kernelpath already installed " fi

alright, git pull, please try again
