### ISSUE TITLE
A8X Support

### ISSUE THREAD

**Issue by shMatrix** [edwin170/downr1n#43]
Hi,
First of all thank you for the great tool for downgrading.

I would like to know if A8X (iPad Air2) devices are supported? AS I know A8X is a checkm8 device, but when I'm trying to downgrade after entering DFU mode I get "unable connect to the device" error message.

**Comment by dualra1n** [comment]
Mmh try out it on dfu mode and then start the script again, a8 and a8x I wouldn't recommend downgrade, it is known that they have deep sleep problems and sometimes they even can't wake up until the battery is discharged, i think you should use dualra1n.

**Comment by shMatrix** [comment]
Ok, I managed to fix that and the script started to work, but now it stuck on 

```
Compiled with plist: YES
Saved IM4M to work/IM4M
Dumpped SHSH
[*] Patching kernel ...
Reading work/kernelcache...
[NOTE] Image4 payload data is LZSS compressed, decompressing...
```

I'm trying to downgrade from 15.7.8. Tried two IOS 14.1 and 14.8 versions.  Both of them stuck on 
_[NOTE] Image4 payload data is LZSS compressed, decompressing..._

**Comment by dualra1n** [comment]
> Ok, I managed to fix that and the script started to work, but now it stuck on 
> 
> 
> 
> ```
> 
> Compiled with plist: YES
> 
> Saved IM4M to work/IM4M
> 
> Dumpped SHSH
> 
> [*] Patching kernel ...
> 
> Reading work/kernelcache...
> 
> [NOTE] Image4 payload data is LZSS compressed, decompressing...
> 
> ```
> 
> 
> 
> I'm trying to downgrade from 15.7.8. Tried two IOS 14.1 and 14.8 versions.  Both of them stuck on 
> 
> _[NOTE] Image4 payload data is LZSS compressed, decompressing..._

https://github.com/dualra1n/dualra1n/issues/74

**Comment by shMatrix** [comment]
Hi, thank you for the link.
But finally I downgraded the python and new errors appeared.

`../Linux/PlistBuddy: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29&apos; not found (required by ../Linux/PlistBuddy)
../Linux/PlistBuddy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33&apos; not found (required by ../Linux/PlistBuddy)
../Linux/PlistBuddy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34&apos; not found (required by ../Linux/PlistBuddy)
Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
init pzb: https://updates.cdn-apple.com/2022SummerFCS/fullrestores/012-41685/A12D2F85-A629-49EF-B5F7-FDF71C040564/iPad_64bit_TouchID_15.6_19G71_Restore.ipsw
init done
Error: file Firmware/.trustcache does not exist, or is a directory
[-] An error occurred`

and at the beginning there was usbmux argument error, is incorrect

I guess the script was updated recently?

**Comment by edwin170** [comment]
> Hi, thank you for the link. But finally I downgraded the python and new errors appeared.
> 
> `../Linux/PlistBuddy: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ../Linux/PlistBuddy) ../Linux/PlistBuddy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33&apos; not found (required by ../Linux/PlistBuddy) ../Linux/PlistBuddy: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ../Linux/PlistBuddy) Version: 3fc8c093f4660f6c6e07c0c9214618733da01ffc - 36 libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8 init pzb: https://updates.cdn-apple.com/2022SummerFCS/fullrestores/012-41685/A12D2F85-A629-49EF-B5F7-FDF71C040564/iPad_64bit_TouchID_15.6_19G71_Restore.ipsw init done Error: file Firmware/.trustcache does not exist, or is a directory [-] An error occurred`
> 
> and at the beginning there was usbmux argument error, is incorrect
> 
> I guess the script was updated recently?

what linux distro are you using ?

**Comment by shMatrix** [comment]
Ubuntu 20.04.6

**Comment by edwin170** [comment]
> Ubuntu 20.04.6

please git pull and try it again
