### ISSUE TITLE
to fix futurerestore ipsw not found

### ISSUE THREAD

**Issue by Ijustplaymc** [edwin170/downr1n#46]
In your latest commit (https://github.com/edwin170/downr1n/commit/9de56c3eaa130872f81e4d9180398dc6fc185e10)
You tried to fix ipsw
path was wrong, this works for linux
replace ipsw/*.ipsw with ./ipsw/*.ipsw

restoring works now (too lazy to make pr)

also it wont detect ipsw

**Comment by edwin170** [comment]
> In your latest commit ([9de56c3](https://github.com/edwin170/downr1n/commit/9de56c3eaa130872f81e4d9180398dc6fc185e10)) You tried to fix ipsw path was wrong, this works for linux replace ipsw/_.ipsw with ./ipsw/_.ipsw
> 
> restoring works now (too lazy to make pr)
> 
> also it wont detect ipsw

the problem was only on future restore ?

**Comment by edwin170** [comment]
> In your latest commit ([9de56c3](https://github.com/edwin170/downr1n/commit/9de56c3eaa130872f81e4d9180398dc6fc185e10)) You tried to fix ipsw path was wrong, this works for linux replace ipsw/_.ipsw with ./ipsw/_.ipsw
> 
> restoring works now (too lazy to make pr)
> 
> also it wont detect ipsw

nvm I fixed, thank you
