### ISSUE TITLE
future restore fails

### ISSUE THREAD

**Issue by shMatrix** [edwin170/downr1n#52]
Once future restore starts restoring and after red yellow green display blinking I'm getting next error:

```
Personalizing IMG4 component iBoot...
Personalizing IMG4 component RestoreSEP...
Personalizing IMG4 component SEP...
Sending NORData now...
Done sending NORData
Checkpoint 1545 complete with code 0
Checkpoint 1683 complete with code 0
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Checkpoint 1637 complete with code 0
Checkpoint 1556 complete with code 0
Checkpoint 1686 complete with code 0
Checkpoint 1620 complete with code 0
Checkpoint 1687 complete with code 0
Checkpoint 1557 complete with code 0
About to send FDR Trust data...
Sending FDR Trust data now...
Done sending FDR Trust Data
Checkpoint 1558 complete with code 0
Checkpoint 1559 complete with code 0
Checkpoint 1560 complete with code 0
Checking for uncollected logs (44)
Checkpoint 1561 complete with code 0
Checking for uncollected logs (44)
ERROR: Could not read data (-256). Aborting.
ReverseProxy[Ctrl]: (status=2) Terminated
Cleaning up...
[exception]:
what=ERROR: Unable to restore device

code=92995638
line=1419
file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp
commit count=308
commit sha  =9554c0068dc50e141872ced5da2bd95baa595805
Done: restoring failed!

if nothing works just try to run (with sudo or without) this command: /home/user/downr1n/binaries/Linux/futurerestore -t blobs/iPad5,3-14.3.shsh2 --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --no-baseband ipsw/iPad_64bit_TouchID_14.3_18C66_Restore.ipsw
if futurerestore restore sucess, you can boot using  --boot
```

Tried this command. With sudo getting:

```
Futurerestore is up to date!
[INFO] 64-bit device detected
futurerestore init done
reading signing ticket blobs/iPad5,3-14.3.shsh2 is done
User specified to use latest signed SEP
Segmentation fault 
```

Without sudo same as initially. 

Trying to downgrade ipad air 2 from 15.7.8 to 14.1 (14.3 tried as well, same errors)
Ubuntu 22.04.03, default python 3.10

**Comment by edwin170** [comment]
> Once future restore starts restoring and after red yellow green display blinking I'm getting next error:
> 
> ```
> Personalizing IMG4 component iBoot...
> Personalizing IMG4 component RestoreSEP...
> Personalizing IMG4 component SEP...
> Sending NORData now...
> Done sending NORData
> Checkpoint 1545 complete with code 0
> Checkpoint 1683 complete with code 0
> Unmounting filesystems (29)
> Unmounting filesystems (29)
> Unmounting filesystems (29)
> Unmounting filesystems (29)
> Unmounting filesystems (29)
> Checkpoint 1637 complete with code 0
> Checkpoint 1556 complete with code 0
> Checkpoint 1686 complete with code 0
> Checkpoint 1620 complete with code 0
> Checkpoint 1687 complete with code 0
> Checkpoint 1557 complete with code 0
> About to send FDR Trust data...
> Sending FDR Trust data now...
> Done sending FDR Trust Data
> Checkpoint 1558 complete with code 0
> Checkpoint 1559 complete with code 0
> Checkpoint 1560 complete with code 0
> Checking for uncollected logs (44)
> Checkpoint 1561 complete with code 0
> Checking for uncollected logs (44)
> ERROR: Could not read data (-256). Aborting.
> ReverseProxy[Ctrl]: (status=2) Terminated
> Cleaning up...
> [exception]:
> what=ERROR: Unable to restore device
> 
> code=92995638
> line=1419
> file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp
> commit count=308
> commit sha  =9554c0068dc50e141872ced5da2bd95baa595805
> Done: restoring failed!
> 
> if nothing works just try to run (with sudo or without) this command: /home/user/downr1n/binaries/Linux/futurerestore -t blobs/iPad5,3-14.3.shsh2 --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --no-baseband ipsw/iPad_64bit_TouchID_14.3_18C66_Restore.ipsw
> if futurerestore restore sucess, you can boot using  --boot
> ```
> 
> Tried this command. With sudo getting:
> 
> ```
> Futurerestore is up to date!
> [INFO] 64-bit device detected
> futurerestore init done
> reading signing ticket blobs/iPad5,3-14.3.shsh2 is done
> User specified to use latest signed SEP
> Segmentation fault 
> ```
> 
> Without sudo same as initially.
> 
> Trying to downgrade ipad air 2 from 15.7.8 to 14.1 (14.3 tried as well, same errors) Ubuntu 22.04.03, default python 3.10

restore your iPad using iTunes and try again

**Comment by shMatrix** [comment]
> restore your iPad using iTunes and try again

It helped thanks.
Future restore succeeded and I got message to use --boot for booting device.
But unfortunately it stuck here after executing the command:

```
[*] Waiting for devices
[*] Detected DFU mode device
[*] Waiting for devices
[*] Detected DFU mode device
[*] Getting device info...
Detected cpid, your cpid is 0x7001
Detected model, your model is j81ap
Detected deviceid, your deviceid is iPad5,3
[*] Continuing...
[*] Creating ramdisk
[-] Ramdisk is already created so SKIPPING ...
[*] Booting ramdisk
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x7001
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
[==                                                ] 2.5%[*] Waiting for the ramdisk to finish booting
bind(): Address in use
Error creating socket for listen port 2222: Address in use
```

Tried fixboot, localboot, fsboot, same error. The device has black screen and doesn't react on any buttons.

**Comment by shMatrix** [comment]
couple of force rebooting (power+home button) helped
Thank you!
