### ISSUE TITLE
A8X deep sleep 

### ISSUE THREAD

**Issue by shMatrix** [edwin170/downr1n#54]
Any chances to fix deep sleep for A8X devices?
In my case it goes deep sleep right away after screen is locked and I have to wait while it's fully discharged.

**Comment by edwin170** [comment]
If you want to fix recovery mode, try copying the firmware/all_flash/* from an IPSW of the version you are or were on before the downgrade to the IPSW for the iOS that you want to downgrade. This should restore recovery mode. remember after future restore success restore it to the original ipsw

**Comment by edwin170** [comment]
and remember that when you do jailbreak, activate the local boot

**Comment by shMatrix** [comment]
Nothing helped. How to restore device at all?
Itunes DFU Mode gives me 4014 error.
  ./downr1n.sh stuck on 
`[*] Waiting for the ramdisk to finish booting`
May be the device is still not fully discharged. Don't know how to verify this.

**Comment by edwin170** [comment]
> Nothing helped. How to restore device at all? Itunes DFU Mode gives me 4014 error. ./downr1n.sh stuck on `[*] Waiting for the ramdisk to finish booting` May be the device is still not fully discharged. Don't know how to verify this.

please force reboot and put it on the real dfu mode and then try boot or restore with itune if you want it.

**Comment by shMatrix** [comment]
I force rebooted the device, put to real DFU (power+home button 10~sec, release power button and hold ~10sec)
then executed ./binaries/Linux/gaster pwn
got this:
```
ser@user-Latitude-E5470:~/downr1n/binaries/Linux$ sudo ./gaster pwn
usb_timeout: 5
usb_abort_timeout_min: 0
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x7001
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x7001
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x7001
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x7001
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x7001
Found the USB handle.
Now you can boot untrusted images.
```
and tried to restore via Itunes. Itunes gives same error 4014
`Unexpected device state 'DFU' expected 'Recovery' (Probably forced into DFU mode externally)`

**Comment by shMatrix** [comment]
Yeah, but it's not booting.
The script is stopping on:
`[*] Waiting for the ramdisk to finish booting`
Instead of turning on the screen and starting to boot, I see in the background that the device disappears for a couple of minutes in device manager, and then is detected again in DFU mode.  Meanwhile the script continues showing:
`[*] Waiting for the ramdisk to finish booting`
and nothing happens next. 
I was told that after downgrade A8X device can get deep sleep and only fully discharging can get the device out of it. Maybe this is the case? Anyway, could you please help me to restore device?

**Comment by edwin170** [comment]
> Yeah, but it's not booting.
> The script is stopping on:
> `[*] Waiting for the ramdisk to finish booting`
> Instead of turning on the screen and starting to boot, I see in the background that the device disappears for a couple of minutes in device manager, and then is detected again in DFU mode. Meanwhile the script continues showing:
> `[*] Waiting for the ramdisk to finish booting`
> and nothing happens next.
> I was told that after downgrade A8X device can get deep sleep and only fully discharging can get the device out of it. Maybe this is the case? Anyway, could you please help me to restore device?

let it discharger complete like 2 days and after that restore using iTunes
