### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [edwin170/downr1n#55]
Attempting to downgrade my iPhone 7 (currently on iOS 15.6.1) to 14.3 using a hackintosh running macOS Sonoma, and I just get the following

```
[*] Command ran: ./downr1n.sh --downgrade 14.3
Cloning into 'ramdisk'...
[*] Downloading futurerestore please wait...
Archive:  futurerestore-macOS-RELEASE.zip
  inflating: futurerestore-macOS-v2.0.0-test-Build_308-RELEASE.tar.xz  
x futurerestore
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by Be1epok** [comment]
Download and use git repository
ex (on linux) : git clone --recursive https://github.com/edwin170/downr1n

**Comment by edwin170** [comment]
> Download and use git repository
> ex (on linux) : git clone --recursive https://github.com/edwin170/downr1n

yeah good answer

**Comment by edwin170** [comment]
> Attempting to downgrade my iPhone 7 (currently on iOS 15.6.1) to 14.3 using a hackintosh running macOS Sonoma, and I just get the following
> 
> ```
> [*] Command ran: ./downr1n.sh --downgrade 14.3
> Cloning into 'ramdisk'...
> [*] Downloading futurerestore please wait...
> Archive:  futurerestore-macOS-RELEASE.zip
>   inflating: futurerestore-macOS-v2.0.0-test-Build_308-RELEASE.tar.xz  
> x futurerestore
> fatal: not a git repository (or any of the parent directories): .git
> ```

instead of downloading please git clone it, you can use the command that the person sent before

**Comment by Lost-Entrepreneur439** [comment]
it worked, my iphone is now on ios 14.3, thanks. :)

**Comment by edwin170** [comment]
great enjoy it
