### ISSUE TITLE
stuck on 'Found the USB handle' and gives an error with kernel patch './downr1n.sh: line 910: [: too many arguments'

### ISSUE THREAD

**Issue by Be1epok** [edwin170/downr1n#56]
anton@anton-desktop:/media/anton/Ubuntu For Gays/bruh/winra1n3/downr1n$ sudo ./downr1n.sh --downgrade 14.8
[*] Command ran: sudo ./downr1n.sh --downgrade 14.8
[19:55:50.943][3] usbmuxd v1.1.1 starting up
[19:55:50.943][3] Using libusb 1.0.25
[19:55:50.944][3] Initialization complete
downr1n | Version 3.0
Created by edwin, thanks palera1, and all people creator of path file boot

[*] Waiting for devices
libusb: warning [op_get_configuration] device unconfigured
libusb: error [op_get_active_config_descriptor] device unconfigured
[19:56:58.974][3] Could not get old configuration descriptor for device 1-28: LIBUSB_ERROR_NOT_FOUND
[19:56:58.981][3] Connecting to new device on location 0x1001c as ID 1
[19:56:59.131][3] Connected to v2.0 device 1 on location 0x1001c with serial number 8345a4f14650cec6fbce5974747b7d6b481f5391
[*] Detected normal mode device
/media/anton/Ubuntu For Gays/bruh/winra1n3/downr1n/binaries/Linux/ideviceinfo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
/media/anton/Ubuntu For Gays/bruh/winra1n3/downr1n/binaries/Linux/ideviceinfo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
Hello,  on 14.8!
[*] Switching device into recovery mode...
/media/anton/Ubuntu For Gays/bruh/winra1n3/downr1n/binaries/Linux/ideviceinfo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
/media/anton/Ubuntu For Gays/bruh/winra1n3/downr1n/binaries/Linux/ideviceenterrecovery: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
[/] if your device can't enter into recovery mode please try to force reboot and put it on recovery mode
[*] Waiting for device in recovery mode
[19:57:06.284][3] Removed device 1 on location 0x1001c
[*] Waiting for devices
[*] Detected recovery mode device
[*] Getting device info...
Detected cpid, your cpid is 0x8010
Detected model, your model is d101ap
Detected deviceid, your deviceid is iPhone9,3
[*] To get into DFU mode, you will be guided through 2 steps:
[*] Press any key when ready for DFU mode
Get ready (0)
Release side button, but keep holding volume down (9)
Release side button, but keep holding volume down (2)
[*] Device entered DFU!
[*] Continuing...
[*] Extracting ipsw, hang on please ...
'ipsw/extracted//BuildManifest.plist' -> 'work/BuildManifest.plist'
[*] Got extract the IPSW successfully
[*] Creating ramdisk
[-] Ramdisk is already created so SKIPPING ...
[*] Booting ramdisk
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Waiting for the ramdisk to finish booting
libusb: warning [op_get_configuration] device unconfigured
libusb: error [op_get_active_config_descriptor] device unconfigured
[19:58:46.915][3] Could not get old configuration descriptor for device 1-40: LIBUSB_ERROR_NOT_FOUND
[19:58:46.920][3] Connecting to new device on location 0x10028 as ID 2
[19:58:47.021][3] Connected to v2.0 device 2 on location 0x10028 with serial number ramdisk tool Sep 18 2022 20:14:43
[19:58:47.022][2] device_control_input: Got unhandled payload type 5
[19:58:47.123][2] device_control_input: Got unhandled payload type 5
Error connecting to device: No error information
[*] Mounting filesystems ...
seputil: Gigalocker file (/mnt7/2AB1A94C-88B7-58C1-807C-0A0A23F155F7.gl) exists
seputil: Gigalocker initialization completed
sepi digest (48 bytes): 904cdb98a0e58d32e0c13173fd46fa361d8a8f37d41782d2a16c64924a868f28862163b90c28a820a7413999ad31fc4e
sepi nonce (20 bytes): eff6b5c4d7ce5ddddceaf5405542b92774bf5d6b
rsep digest (48 bytes): 85172acdedc54e6736148729b60022624c47ec5fc5822ff75af1d88fadfd346a488670b454aa3c0134f67164b5cdba2c
rsep nonce (20 bytes): eff6b5c4d7ce5ddddceaf5405542b92774bf5d6b
[*] Dumpped SHSH
[*] Patching kernel ...
./downr1n.sh: строка 910: [: слишком много аргументов
[*] kernel patched with kpf
Reboot into recovery mode ...
[19:59:57.431][3] Removed device 2 on location 0x10028
[*] To get into DFU mode, you will be guided through 2 steps:
[*] Press any key when ready for DFU mode
Get ready (0)
Release side button, but keep holding volume down (9)
Release side button, but keep holding volume down (2)
[*] Device entered DFU!
[* ]Patching some boot files...
[*] Finished moving the boot files to work
[*] Decrypthing ibss and iboot
usb_timeout: 5
usb_abort_timeout_min: 0
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.

**Comment by edwin170** [comment]
amd ? and what macOS version or linux distro are you using ?

**Comment by Be1epok** [comment]
> amd ? and what macOS version or linux distro are you using ?
amd64, linux ubuntu

**Comment by Be1epok** [comment]
question, how to use git pull, recently started using Linux

**Comment by edwin170** [comment]
gaster problem
