### ISSUE TITLE
cant downgrade other IOS version,just only downgrade 14.3

### ISSUE THREAD

**Issue by CrayonL** [edwin170/downr1n#57]

**Comment by CrayonL** [comment]
Other IOS version just cant loader,just IOS14.3 can boot the device

**Comment by CrayonL** [comment]
Other versions use . /downr1n.sh --downgrade An error occurs after Extracting filesystem form ipsw reaches 100 percent:  ERROR: Failed to read '/var/lib/lockdown/ffffffffffffffffffffffffffffffffffffffff.plist': No such file or directory，this error also occurs at the 'send filesystem now' stage

**Comment by edwin170** [comment]
/var/lib/lockdown/ffffffffffffffffffffffffffffffffffffffff.plist uh, that's normal bro hardware problem ? well idk
