### ISSUE TITLE
Stuck in DFU after downgrading 

### ISSUE THREAD

**Issue by lansysart** [edwin170/downr1n#59]
Hello, i try downloading iphone 7 from 15.7.9 to 14.8, or 14.3.(trying both)

Using linux distributions Ubuntu 22.04 LTS

After restored, scripts say - restore successfully.
Then i try use —boot option, and get nothing..
PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SETUP

and got looped(out of script like on above) … wait about 10-20m
stuck on dfu…than restore to 15.7.9…

**Comment by edwin170** [comment]
> Hello, i try downloading iphone 7 from 15.7.9 to 14.8, or 14.3.(trying both)
> 
> Using linux distributions Ubuntu 22.04 LTS
> 
> After restored, scripts say - restore successfully. Then i try use —boot option, and get nothing.. PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: RESET ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: SPRAY ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8010 Found the USB handle. Stage: SETUP
> 
> and got looped(out of script like on above) … wait about 10-20m stuck on dfu…than restore to 15.7.9…

that's normal, https://github.com/edwin170/downr1n#issues-putting-device-in-pwndfu-mode read this please

**Comment by lansysart** [comment]
Thx for help. It works.
