### ISSUE TITLE
Ipad stuck in dfu

### ISSUE THREAD

**Issue by klutzyT** [edwin170/downr1n#6]
I have an ipad air 2 and when i used downr1n it got stuck in dfu and now anything i try to get it out isnt working and downr1n said it worked successfully is there a fix for this or is my ipad bricked?

**Comment by Aditya20110** [comment]
Bro i dont know. But in sunst0rm also this happens with me i dont know what is happening after restore successful? Shit

**Comment by Aditya20110** [comment]
Hey bro use palera1n dfu helper

**Comment by Denisboi** [comment]
@klutzyT What do you get when you enter: "sudo ./downr1n.sh --boot"?

**Comment by klutzyT** [comment]
@Denisboi  It gets stuck on. “Booting device” and doesn’t go any further than that

**Comment by klutzyT** [comment]
I ended up restoring in iTunes and that fixed it thanks for everyone for your help!
