### ISSUE TITLE
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by joneschrisan** [edwin170/downr1n#60]
"SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats" after "extracting kernel"

The whole thing seems to have crashed now, been hanging for about half an hour.

Running Kali Linux 6.3.0 64 bit, base is Debian 6.3.7

**Comment by joneschrisan** [comment]
iPhone 6s attempting to downgrade to 14.5.1 if that make any difference

**Comment by edwin170** [comment]
https://github.com/dualra1n/dualra1n/issues/74

**Comment by PreferredegeT** [comment]
> [dualra1n/dualra1n#74](https://github.com/dualra1n/dualra1n/issues/74)

pyimg4 is latest and problem still remains，now idevice stuck at RamDisk

**Comment by PreferredegeT** [comment]
progress dead after
    ［*］Dumped SHSH
    ［*］extracting kernel ...
and defined for # happens

how to deal with it？

**Comment by edwin170** [comment]
> > [dualra1n/dualra1n#74](https://github.com/dualra1n/dualra1n/issues/74)
> 
> pyimg4 is latest and problem still remains，now idevice stuck at RamDisk

hi @m1stadev, any idea about this bro ?

**Comment by edwin170** [comment]
> progress dead after ［_］Dumped SHSH ［_］extracting kernel ... and defined for # happens
> 
> how to deal with it？

try with this command: python3 -m pip install pyimg4[compression]

**Comment by rdkkl5** [comment]
i solved this problem with downgrade python 3.10 to python 3.9

**Comment by Potatolover1243** [comment]
> i solved this problem with downgrade python 3.10 to python 3.9

how did you do this?

**Comment by rdkkl5** [comment]
> > i solved this problem with downgrade python 3.10 to python 3.9
> 
> how did you do this?
> 
> I'm on linux btw

Remove python 3.10 and install 3.9
It was the only thing that solved this problem for me
