### ISSUE TITLE
help dfu mode not booting iphone 7 plus liunx 20.04

### ISSUE THREAD

**Issue by zezehacke** [edwin170/downr1n#64]
hello i have this iphone 7 plus after doing it and downgrading to 14.8 i cant boot it up the power + sound button also when i try to run the command --boot it gives me this error [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
 for anything i do and i also tryed to re downgrade but it still gives the same error and jailbreak but im thinking that the iphone is dead and also its it dfu mode

**Comment by edwin170** [comment]
> hello i have this iphone 7 plus after doing it and downgrading to 14.8 i cant boot it up the power + sound button also when i try to run the command --boot it gives me this error [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> CPID: 0x8010
> Found the USB handle.
> Stage: PATCH
> ret: true
> for anything i do and i also tryed to re downgrade but it still gives the same error and jailbreak but im thinking that the iphone is dead and also its it dfu mode

your device is in false dfu mode, First: execute sudo ./binaries/$(uname)/gaster pwn, if that start to loop (like never finish) Force reboot when the loop stop please press home button (or volume down) and stop gaster by pressing ctrl + c in your computer and after 10 second execute the command again

**Comment by zezehacke** [comment]
hi so i did that and it dose not work i tryed like 15-20 times it still spams and i did it after 10 secs and it still spams the error

**Comment by edwin170** [comment]
> hi so i did that and it dose not work i tryed like 15-20 times it still spams and i did it after 10 secs and it still spams the error

we need a video tutorial fr, well please restore with iTunes and if you want use dualra1n. dualra1n is a dual boot you are going to have iOS 15 with iOS 14.8 tethered, https://github.com/dualra1n/dualra1n
