### ISSUE TITLE
busystate 0

### ISSUE THREAD

**Issue by OttoOu** [edwin170/downr1n#67]
hello, I got the following issue while running the --downgrade, And it's stuck on "Mounting filesystems".

device: iPhone SE iOS 12.2

000167.803994 wlan0.A[31] handleAdjustBusy@1551:AdjustBusy timeout in 120000 ms!

**Comment by edwin170** [comment]
> hello, I got the following issue while running the --downgrade, And it's stuck on "Mounting filesystems".
> 
> device: iPhone SE iOS 12.2
> 
> 000167.803994 wlan0.A[31] handleAdjustBusy@1551:AdjustBusy timeout in 120000 ms!

12.2 ? this is only for 13.4 upper

**Comment by OttoOu** [comment]
xD...

so, i just want know there is anyway i can boot images lower than 13.4?

**Comment by edwin170** [comment]
> xD...
> 
> so, i just want know there is anyway i can boot images lower than 13.4?

as it needs to communicate with the sep when it is creating the data partition iirc, I guess you won't be able to go lower than 13.4  sadly

**Comment by OttoOu** [comment]
> > xD...
> > so, i just want know there is anyway i can boot images lower than 13.4?
> 
> as it needs to communicate with the sep when it is creating the data partition iirc, I guess you won't be able to go lower than 13.4 sadly

okay... thanks for the answer :D
