### ISSUE TITLE
Failed to get apnonce from device

### ISSUE THREAD

**Issue by OttoOu** [edwin170/downr1n#69]
[WARNING] BUG WORKAROUND recompressing images with bvx2 makes them not boot for some reason. Skipping compression
Repacking patched iBSS as IMG4
Repacking patched iBEC as IMG4
Sending iBSS (1415555 bytes)...
[==================================================] 100.0%
ERROR: Device is in an invalid state
Booting iBSS, waiting for device to disconnect...
Booting iBSS, waiting for device to reconnect...
ApNonce pre-hax:
INFO: device serial number is FD6W46KXJCM2
Getting ApNonce failed
Cleaning up...
[exception]:
what=Failed to get apnonce from device!
code=50790468
line=775
file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp
commit count=308
commit sha  =9554c0068dc50e141872ced5da2bd95baa595805
Done: restoring failed!

if you are on linux please try above command if futurerestore failed
if futurerestore didn't finish succesfully please try to run (with sudo or without) this command: /Users/otto/ios/downr1n/binaries/Darwin/futurerestore -t blobs/iPhone10,5-13.4.shsh2 --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --latest-baseband ipsw//iPhone_5.5_P3_13.4_17E255_Restore.ipsw
if futurerestore restore sucess, you can boot using  --boot

========================

Hello，today i try to downgrade my iphone 7 plus  from ios 16.7.2 to ios 13.4，i got the following error when “Reboot into recovery mode”

And, when i type the suggestion command in command line with sudo, i got another error:

========================
Found device in Recovery mode
Device already in recovery mode
Cleaning up...
[exception]:
what=--use-pwndfu was specified, but device found in recovery mode!
code=61734980
line=942
file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp
commit count=308
commit sha  =9554c0068dc50e141872ced5da2bd95baa595805
Done: restoring failed!

=========================

How can i resolve it? pls let me know~

**Comment by edwin170** [comment]
> [WARNING] BUG WORKAROUND recompressing images with bvx2 makes them not boot for some reason. Skipping compression Repacking patched iBSS as IMG4 Repacking patched iBEC as IMG4 Sending iBSS (1415555 bytes)... [==================================================] 100.0% ERROR: Device is in an invalid state Booting iBSS, waiting for device to disconnect... Booting iBSS, waiting for device to reconnect... ApNonce pre-hax: INFO: device serial number is FD6W46KXJCM2 Getting ApNonce failed Cleaning up... [exception]: what=Failed to get apnonce from device! code=50790468 line=775 file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp commit count=308 commit sha =9554c0068dc50e141872ced5da2bd95baa595805 Done: restoring failed!
> 
> if you are on linux please try above command if futurerestore failed if futurerestore didn't finish succesfully please try to run (with sudo or without) this command: /Users/otto/ios/downr1n/binaries/Darwin/futurerestore -t blobs/iPhone10,5-13.4.shsh2 --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --latest-baseband ipsw//iPhone_5.5_P3_13.4_17E255_Restore.ipsw if futurerestore restore sucess, you can boot using --boot
> 
> ========================
> 
> Hello，today i try to downgrade my iphone 7 plus from ios 16.7.2 to ios 13.4，i got the following error when “Reboot into recovery mode”
> 
> And, when i type the suggestion command in command line with sudo, i got another error:
> 
> ======================== Found device in Recovery mode Device already in recovery mode Cleaning up... [exception]: what=--use-pwndfu was specified, but device found in recovery mode! code=61734980 line=942 file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp commit count=308 commit sha =9554c0068dc50e141872ced5da2bd95baa595805 Done: restoring failed!
> 
> =========================
> 
> How can i resolve it? pls let me know~

is this an iPhone 8 or 7 ?

**Comment by OttoOu** [comment]
> > > > # [WARNING] BUG WORKAROUND recompressing images with bvx2 makes them not boot for some reason. Skipping compression Repacking patched iBSS as IMG4 Repacking patched iBEC as IMG4 Sending iBSS (1415555 bytes)... [==================================================] 100.0% ERROR: Device is in an invalid state Booting iBSS, waiting for device to disconnect... Booting iBSS, waiting for device to reconnect... ApNonce pre-hax: INFO: device serial number is FD6W46KXJCM2 Getting ApNonce failed Cleaning up... [exception]: what=Failed to get apnonce from device! code=50790468 line=775 file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp commit count=308 commit sha =9554c0068dc50e141872ced5da2bd95baa595805 Done: restoring failed!
> > > > if you are on linux please try above command if futurerestore failed if futurerestore didn't finish succesfully please try to run (with sudo or without) this command: /Users/otto/ios/downr1n/binaries/Darwin/futurerestore -t blobs/iPhone10,5-13.4.shsh2 --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --latest-baseband ipsw//iPhone_5.5_P3_13.4_17E255_Restore.ipsw if futurerestore restore sucess, you can boot using --boot
> > > > # Hello，today i try to downgrade my iphone 7 plus from ios 16.7.2 to ios 13.4，i got the following error when “Reboot into recovery mode”
> > > > And, when i type the suggestion command in command line with sudo, i got another error:
> > > > ======================== Found device in Recovery mode Device already in recovery mode Cleaning up... [exception]: what=--use-pwndfu was specified, but device found in recovery mode! code=61734980 line=942 file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp commit count=308 commit sha =9554c0068dc50e141872ced5da2bd95baa595805 Done: restoring failed!
> > > > How can i resolve it? pls let me know~
> > > 
> > > 
> > > is this an iPhone 8 or 7 ?
> > 
> > 
> > sorry, iphone 8 plus
> 
> a11 devices you only can downgrade to iOS 14.3 upper

okay,thank you~

**Comment by xhhxbg** [comment]
> > > > # [WARNING] BUG WORKAROUND recompressing images with bvx2 makes them not boot for some reason. Skipping compression Repacking patched iBSS as IMG4 Repacking patched iBEC as IMG4 Sending iBSS (1415555 bytes)... [==================================================] 100.0% ERROR: Device is in an invalid state Booting iBSS, waiting for device to disconnect... Booting iBSS, waiting for device to reconnect... ApNonce pre-hax: INFO: device serial number is FD6W46KXJCM2 Getting ApNonce failed Cleaning up... [exception]: what=Failed to get apnonce from device! code=50790468 line=775 file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp commit count=308 commit sha =9554c0068dc50e141872ced5da2bd95baa595805 Done: restoring failed!
> > > > if you are on linux please try above command if futurerestore failed if futurerestore didn't finish succesfully please try to run (with sudo or without) this command: /Users/otto/ios/downr1n/binaries/Darwin/futurerestore -t blobs/iPhone10,5-13.4.shsh2 --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --latest-baseband ipsw//iPhone_5.5_P3_13.4_17E255_Restore.ipsw if futurerestore restore sucess, you can boot using --boot
> > > > # Hello，today i try to downgrade my iphone 7 plus from ios 16.7.2 to ios 13.4，i got the following error when “Reboot into recovery mode”
> > > > And, when i type the suggestion command in command line with sudo, i got another error:
> > > > ======================== Found device in Recovery mode Device already in recovery mode Cleaning up... [exception]: what=--use-pwndfu was specified, but device found in recovery mode! code=61734980 line=942 file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp commit count=308 commit sha =9554c0068dc50e141872ced5da2bd95baa595805 Done: restoring failed!
> > > > How can i resolve it? pls let me know~
> > > 
> > > 
> > > is this an iPhone 8 or 7 ?
> > 
> > 
> > sorry, iphone 8 plus
> 
> a11 devices you only can downgrade to iOS 14.3 upper

My ipad mini 4 occered the same error while downgrading to IOS 13.6, how can i solve it?

**Comment by edwin170** [comment]
> > > > > # [WARNING] BUG WORKAROUND recompressing images with bvx2 makes them not boot for some reason. Skipping compression Repacking patched iBSS as IMG4 Repacking patched iBEC as IMG4 Sending iBSS (1415555 bytes)... [==================================================] 100.0% ERROR: Device is in an invalid state Booting iBSS, waiting for device to disconnect... Booting iBSS, waiting for device to reconnect... ApNonce pre-hax: INFO: device serial number is FD6W46KXJCM2 Getting ApNonce failed Cleaning up... [exception]: what=Failed to get apnonce from device! code=50790468 line=775 file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp commit count=308 commit sha =9554c0068dc50e141872ced5da2bd95baa595805 Done: restoring failed!
> > > > > if you are on linux please try above command if futurerestore failed if futurerestore didn't finish succesfully please try to run (with sudo or without) this command: /Users/otto/ios/downr1n/binaries/Darwin/futurerestore -t blobs/iPhone10,5-13.4.shsh2 --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --latest-baseband ipsw//iPhone_5.5_P3_13.4_17E255_Restore.ipsw if futurerestore restore sucess, you can boot using --boot
> > > > > # Hello，today i try to downgrade my iphone 7 plus from ios 16.7.2 to ios 13.4，i got the following error when “Reboot into recovery mode”
> > > > > And, when i type the suggestion command in command line with sudo, i got another error:
> > > > > ======================== Found device in Recovery mode Device already in recovery mode Cleaning up... [exception]: what=--use-pwndfu was specified, but device found in recovery mode! code=61734980 line=942 file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp commit count=308 commit sha =9554c0068dc50e141872ced5da2bd95baa595805 Done: restoring failed!
> > > > > How can i resolve it? pls let me know~
> > > > 
> > > > 
> > > > is this an iPhone 8 or 7 ?
> > > 
> > > 
> > > sorry, iphone 8 plus
> > 
> > 
> > a11 devices you only can downgrade to iOS 14.3 upper
> 
> My ipad mini 4 occered the same error while downgrading to IOS 13.6, how can i solve it?

try with 14.3 upper
