### ISSUE TITLE
iBoot64Patcher corrupted

### ISSUE THREAD

**Issue by RiberWang** [edwin170/downr1n#71]
./downr1n.sh: 第 1205 行：18249 Killed: 9               "$dir"/iBoot64Patcher work/iBSS.dec work/iBSS.patched > /dev/null

macOS 12.6.5

**Comment by RiberWang** [comment]
“iBoot64Patcher”已损坏，无法打开。 您应该将它移到废纸篓。
What should I do next?

**Comment by edwin170** [comment]
> open terminal and input `sudo spctl --master-disable`
> 
> I try it, setting show any source

Don't do that, it is insecure
