### ISSUE TITLE
You answered NO. so using the 14.8. [*] Downloading ipsw, it may take few minutes. curl: (6) Could not resolve host: null

### ISSUE THREAD

**Issue by Potatolover1243** [edwin170/downr1n#72]
You answered NO. so using the 14.8.
[*] Downloading ipsw, it may take few minutes.
curl: (6) Could not resolve host: null

**Comment by edwin170** [comment]
@sasa8810 hi

**Comment by edwin170** [comment]
> I dont think this is the downloader issue

ik, i just wanted to know if you know something about this error. but seems like potato fixed it
