### ISSUE TITLE
RuntimeError: pyliblzfse not installed, cannot use LZFSE compression

### ISSUE THREAD

**Issue by Potatolover1243** [edwin170/downr1n#74]
RuntimeError: pyliblzfse not installed, cannot use LZFSE compression

**Comment by Potatolover1243** [comment]
python3 -m pip install pyimg4[compression] and no this doesnt work for me

**Comment by Potatolover1243** [comment]
i do that and it just repeats it

**Comment by edwin170** [comment]
> i do that and it just repeats it

linux ?

**Comment by Potatolover1243** [comment]
> > i do that and it just repeats it
> 
> linux ?

Kali Linux

**Comment by edwin170** [comment]
> > > i do that and it just repeats it
> > 
> > 
> > linux ?
> 
> Kali Linux

try to downgrade your python to python 3.8

**Comment by Potatolover1243** [comment]
> > > > i do that and it just repeats it
> > > 
> > > 
> > > linux ?
> > 
> > 
> > Kali Linux
> 
> try to downgrade your python to python 3.8

can i uss pyenv to do this?

**Comment by edwin170** [comment]
> > > > > i do that and it just repeats it
> > > > 
> > > > 
> > > > linux ?
> > > 
> > > 
> > > Kali Linux
> > 
> > 
> > try to downgrade your python to python 3.8
> 
> can i uss pyenv to do this?

am not sure
