### ISSUE TITLE
restoring failed!

### ISSUE THREAD

**Issue by RiberWang** [edwin170/downr1n#77]
failed verification with error:
[exception]:
what=verification failed!
code=84279308
line=1286
file=img4tool.cpp
commit count=197
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f
[WARNING] NOT VALIDATING SHSH BLOBS IM4M!
[Error] BuildIdentity selected for restore does not match APTicket

BuildIdentity selected for restore:
BuildNumber : 18A373
BuildTrain : Azul
DeviceClass : n66map
FDRSupport : YES
MobileDeviceMinVersion : 1253
RestoreBehavior : Erase
Variant : Customer Erase Install (IPSW)

BuildIdentity is valid for the APTicket:
IM4M is not valid for any restore within the Buildmanifest
This APTicket can't be used for restoring this firmware
[WARNING] NOT VALIDATING SHSH BLOBS!
Variant: Customer Erase Install (IPSW)
This restore will erase all device data.
Device found in DFU Mode.
Getting firmware keys for: n66map
Cleaning up...
[exception]:
what=getting keys failed with error: 14745615 (failed to get FirmwareJson from Server). Are keys publicly available?
code=41680964
line=636
file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp
commit count=308
commit sha  =9554c0068dc50e141872ced5da2bd95baa595805
Done: restoring failed!
if you are on linux please try above command if futurerestore failed
if futurerestore didn't finish succesfully please try to run (with sudo or without) this command: /Users/riber/Desktop/downr1n/binaries/Darwin/futurerestore -t blobs/iPhone8,2-14.0.shsh2 --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --latest-baseband ipsw/iPhone_5.5_14.0_18A373_Restore.ipsw
if futurerestore restore sucess, you can boot using  --boot

**Comment by RiberWang** [comment]
Try again always show error!
BuildIdentity is valid for the APTicket:
IM4M is not valid for any restore within the Buildmanifest
This APTicket can't be used for restoring this firmware
[WARNING] NOT VALIDATING SHSH BLOBS!
Variant: Customer Erase Install (IPSW)
This restore will erase all device data.
Device found in DFU Mode.
Getting firmware keys for: n66map
Cleaning up...
[exception]:
what=getting keys failed with error: 14745615 (failed to get FirmwareJson from Server). Are keys publicly available?
code=41680964
line=636
file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp
commit count=308
commit sha  =9554c0068dc50e141872ced5da2bd95baa595805
Done: restoring failed!

**Comment by edwin170** [comment]
https://github.com/edwin170/downr1n#fix-some-problems

**Comment by edwin170** [comment]
read

**Comment by Nethra1n** [comment]
use sudo ./downr1n.sh --downgrade [ios} but add flag --keyServer and active wikiproxy & if you installed it
