### ISSUE TITLE
Is it possible to tethered "upgrade" to a newer but not signed firmware?

### ISSUE THREAD

**Issue by i1itione** [edwin170/downr1n#78]
I made my iPad Pro 2 (checkm8 compatible) got stuck into recovery mode (I've tried "irecovery -n" but not work) due to failed DelayOTA to 16.6 from 13.7, and I only have two shsh files for this device, which are 13.7 and 16.6. I tried using futurerestore to recover this device but no luck, I am still trying to find a solution to fix it but avoid to upgrade to the latest iOS version via iTunes.

**Comment by edwin170** [comment]
> I made my iPad Pro 2 (checkm8 compatible) got stuck into recovery mode (I've tried "irecovery -n" but not work) due to failed DelayOTA to 16.6 from 13.7, and I only have two shsh files for this device, which are 13.7 and 16.6. I tried using futurerestore to recover this device but no luck, I am still trying to find a solution to fix it but avoid to upgrade to the latest iOS version via iTunes.

there is not much solution
