### ISSUE TITLE
what=can't init, no device found

### ISSUE THREAD

**Issue by FireIceUwU** [edwin170/downr1n#82]
Archlinux, Python 3.11.6, iPhone 6s
```
[*] Patching the kernel
[*] Patching the kernel to restore using futurerestore
[*] Patching devicetree
[*] Patching the restored_external and asr, and saving them into the ramdisk ...
'work/devicetree.img4' -> 'boot/iPhone8,1/devicetree.img4'
'work/iBEC.img4' -> 'boot/iPhone8,1/iBEC.img4'
'work/iBSS.img4' -> 'boot/iPhone8,1/iBSS.img4'
'work/kernelcache.img4' -> 'boot/iPhone8,1/kernelcache.img4'
'work/trustcache.img4' -> 'boot/iPhone8,1/trustcache.img4'
[*] Sucess Patching the boot files
[*] Checking if the llb was already replaced
[*] Patching the llb in the ipsw to avoid false dfu mode
[=] Hi, please i need that you write the ios version that this device is on or the version of the ios that it was on (if this device is already downgraded), most of the time is the lastest version of ios. write 0 if you want to skip this (it is not recommended to skip this as this can avoid false dfu mode)
Version detected!. we are gonna use 15.2.1
[*] LLB downloaded correctly
[*] putting this LLB into the ipsw
        zip warning: Local Version Needed To Extract does not match CD: Firmware/
        zip warning: Local Version Needed To Extract does not match CD: Firmware/AOP/
        zip warning: Local Version Needed To Extract does not match CD: Firmware/all_flash/
updating: Firmware/all_flash/LLB.n71m.RELEASE.im4p (deflated 0%)
        zip warning: Local Version Needed To Extract does not match CD: Firmware/dfu/
        zip warning: Local Version Needed To Extract does not match CD: Firmware/usr/
        zip warning: Local Version Needed To Extract does not match CD: Firmware/usr/local/
  adding: Firmware/all_flash//LLB.n71m.RELEASE.im4p (deflated 0%)
[*] Replaced LLB suscessfully
[*] Executing futurerestore ...
Press ENTER to continue with futurerestore, your device will start to restoring <-
Version: v2.0.0-test(9554c0068dc50e141872ced5da2bd95baa595805-308)
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
libipatcher version: 0.88-1e855d70c84419014e363bdbcaead7b145fe3e1f-RELEASE
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes
Checking for updates...
Futurerestore is up to date!
futurerestore: failed with exception:
[exception]:
what=can't init, no device found

code=20840493
line=318
file=/tmp/Builder/repos/futurerestore/src/main.cpp
commit count=308
commit sha  =9554c0068dc50e141872ced5da2bd95baa595805
if futurerestore failed you can try execute the command below
if futurerestore didn't finish succesfully please try to run (with sudo or without) this command: /home/contineon/downr1n/binaries/Linux/futurerestore -t blobs/iPhone8,1-13.7.shsh2 --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --latest-baseband ipsw/iPhone_4.7_13.7_17H35_Restore.ipsw
if futurerestore restore sucess, you can boot using  --boot
```

**Comment by edwin170** [comment]
> Archlinux, Python 3.11.6, iPhone 6s
> 
> ```
> [*] Patching the kernel
> [*] Patching the kernel to restore using futurerestore
> [*] Patching devicetree
> [*] Patching the restored_external and asr, and saving them into the ramdisk ...
> 'work/devicetree.img4' -> 'boot/iPhone8,1/devicetree.img4'
> 'work/iBEC.img4' -> 'boot/iPhone8,1/iBEC.img4'
> 'work/iBSS.img4' -> 'boot/iPhone8,1/iBSS.img4'
> 'work/kernelcache.img4' -> 'boot/iPhone8,1/kernelcache.img4'
> 'work/trustcache.img4' -> 'boot/iPhone8,1/trustcache.img4'
> [*] Sucess Patching the boot files
> [*] Checking if the llb was already replaced
> [*] Patching the llb in the ipsw to avoid false dfu mode
> [=] Hi, please i need that you write the ios version that this device is on or the version of the ios that it was on (if this device is already downgraded), most of the time is the lastest version of ios. write 0 if you want to skip this (it is not recommended to skip this as this can avoid false dfu mode)
> Version detected!. we are gonna use 15.2.1
> [*] LLB downloaded correctly
> [*] putting this LLB into the ipsw
>         zip warning: Local Version Needed To Extract does not match CD: Firmware/
>         zip warning: Local Version Needed To Extract does not match CD: Firmware/AOP/
>         zip warning: Local Version Needed To Extract does not match CD: Firmware/all_flash/
> updating: Firmware/all_flash/LLB.n71m.RELEASE.im4p (deflated 0%)
>         zip warning: Local Version Needed To Extract does not match CD: Firmware/dfu/
>         zip warning: Local Version Needed To Extract does not match CD: Firmware/usr/
>         zip warning: Local Version Needed To Extract does not match CD: Firmware/usr/local/
>   adding: Firmware/all_flash//LLB.n71m.RELEASE.im4p (deflated 0%)
> [*] Replaced LLB suscessfully
> [*] Executing futurerestore ...
> Press ENTER to continue with futurerestore, your device will start to restoring <-
> Version: v2.0.0-test(9554c0068dc50e141872ced5da2bd95baa595805-308)
> img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
> libipatcher version: 0.88-1e855d70c84419014e363bdbcaead7b145fe3e1f-RELEASE
> Odysseus for 32-bit support: yes
> Odysseus for 64-bit support: yes
> Checking for updates...
> Futurerestore is up to date!
> futurerestore: failed with exception:
> [exception]:
> what=can't init, no device found
> 
> code=20840493
> line=318
> file=/tmp/Builder/repos/futurerestore/src/main.cpp
> commit count=308
> commit sha  =9554c0068dc50e141872ced5da2bd95baa595805
> if futurerestore failed you can try execute the command below
> if futurerestore didn't finish succesfully please try to run (with sudo or without) this command: /home/contineon/downr1n/binaries/Linux/futurerestore -t blobs/iPhone8,1-13.7.shsh2 --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --latest-baseband ipsw/iPhone_4.7_13.7_17H35_Restore.ipsw
> if futurerestore restore sucess, you can boot using  --boot
> ```

try execute this command in the terminal after the error happens, /home/contineon/downr1n/binaries/Linux/futurerestore -t blobs/iPhone8,1-13.7.shsh2 --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --latest-baseband ipsw/iPhone_4.7_13.7_17H35_Restore.ipsw
