### ISSUE TITLE
Stuck on pwning

### ISSUE THREAD

**Issue by Narcoughtics02** [edwin170/downr1n#85]
[](![image](https://github.com/edwin170/downr1n/assets/155335546/04bfcc1e-c346-4ea2-a44a-f7df4b4a3344))

**Comment by roy-heinrich** [comment]
how did you fix this? im using iphone 6s+ downgraded to ios 14.8. flash was succesful but it is now stuck at Pwning device. force restart doesnt work.

**Comment by Narcoughtics** [comment]
> how did you fix this? im using iphone 6s+ downgraded to ios 14.8. flash was succesful but it is now stuck at Pwning device. force restart doesnt work.

Boot into dfu mode, if that doesn’t work run gaster “binaries/linux/gaster pwn” is what worked for me since I’m on Linux but not sure of your OS

**Comment by roy-heinrich** [comment]
i also use linux but i will try some other time
