### ISSUE TITLE
Trouble Installing Dependencies

### ISSUE THREAD

**Issue by Visualwit** [edwin170/downr1n#87]
I run the command under "Installing Dependencies" but I get an error: zsh: no matches found: pyimg4[compression].

**Comment by edwin170** [comment]
> I run the command under "Installing Dependencies" but I get an error: zsh: no matches found: pyimg4[compression].

execute python3 -m pip install pyimg4 on the terminal

**Comment by Visualwit** [comment]
Thanks!
