### ISSUE TITLE
iPhone6s iOS15.8->14.8 ERROR: Unable to connect to device

### ISSUE THREAD

**Issue by Cregin** [edwin170/downr1n#89]
./downr1n.sh --downgrade 14.8
[*] Command ran: ./downr1n.sh --downgrade 14.8
downr1n | Version 3.0
Created by edwin, thanks palera1, and all people creator of path file boot

[*] Waiting for devices
[*] Detected DFU mode device
[*] Waiting for devices
[*] Detected DFU mode device
[*] Getting device info...
Detected cpid, your cpid is 0x8000
Detected model, your model is n71ap
Detected deviceid, your deviceid is iPhone8,1
[-] we found ipsw/iPhone_4.7_14.8_18H17_Restore.ipsw, do you want to use it ? please write, yes or no
yes
ipsw/iPhone_4.7_14.8_18H17_Restore.ipsw
[*] Checking if the ipsw is for your device
[*] Checking ipsw version
[*] Extracting ipsw, hang on please ...
[*] Got extract the IPSW successfully
[*] Creating ramdisk
[-] Ramdisk is already created so SKIPPING ...
[*] Booting ramdisk
[/] We couldn't get the ipsw curl. we will proceed with -k option with curl
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8000 CPRV:20 CPFM:03 SCEP:01 BDID:04 ECID:000002B44E240D2C IBFL:1C SRTG:[iBoot-2234.0.0.3.3]
Found the USB handle.
Stage: RESET
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8000 CPRV:20 CPFM:03 SCEP:01 BDID:04 ECID:000002B44E240D2C IBFL:1C SRTG:[iBoot-2234.0.0.3.3]
Found the USB handle.
Stage: SETUP
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8000 CPRV:20 CPFM:03 SCEP:01 BDID:04 ECID:000002B44E240D2C IBFL:1C SRTG:[iBoot-2234.0.0.3.3]
Found the USB handle.
Stage: PATCH
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8000 CPRV:20 CPFM:03 SCEP:01 BDID:04 ECID:000002B44E240D2C IBFL:1C SRTG:[iBoot-2234.0.0.3.3] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
ERROR: Unable to connect to device
[-] An error occurred

**Comment by edwin170** [comment]
rm -rf ramdisk/boot

**Comment by Cregin** [comment]
Delete ramdisk/boot and try again, still the same problem

**Comment by Cregin** [comment]
[/] We couldn't get the ipsw curl. we will proceed with -k option with curl

**Comment by Cregin** [comment]
./downr1n.sh --downgrade 14.8
[*] Command ran: ./downr1n.sh --downgrade 14.8
downr1n | Version 3.0
Created by edwin, thanks palera1, and all people creator of path file boot

[*] Waiting for devices
[*] Detected DFU mode device
[*] Waiting for devices
[*] Detected DFU mode device
[*] Getting device info...
Detected cpid, your cpid is 0x8000
Detected model, your model is n71ap
Detected deviceid, your deviceid is iPhone8,1
./downr1n.sh: line 696: [: ipsw/iPhone_4.7_14.7_18G69_Restore.ipsw: unary operator expected
[-] we found ipsw/iPhone_4.7_14.8_18H17_Restore.ipsw, do you want to use it ? please write, yes or no
yes
ipsw/iPhone_4.7_14.8_18H17_Restore.ipsw
[*] Checking if the ipsw is for your device
[*] Checking ipsw version
[*] Extracting ipsw, hang on please ...
[*] Got extract the IPSW successfully
[*] Creating ramdisk

After a while, the phone automatically turns on🤣
