### ISSUE TITLE
error when inflating caster√

### ISSUE THREAD

**Issue by gakemaster150** [edwin170/downr1n#9]
mv: rename gaster to /Users/clark/Desktop/ok/binaries/Darwin/: No such file or directory)

does this on both of my MacBooks one on 10.13 one on 10.15

**Comment by dualra1n** [comment]
> mv: rename gaster to /Users/clark/Desktop/ok/binaries/Darwin/: No such file or directory)
> 
> does this on both of my MacBooks one on 10.13 one on 10.15

git pull and try again downr1n
