### ISSUE TITLE
Cant get something  downloading the lib 

### ISSUE THREAD

**Issue by K1ym** [edwin170/downr1n#90]
```
ERROR downloading the ilb please check the ios version and write it again. if this error
happens a lot of time please use 0 to skip lib
```
wikiproxy running。。。。

**Comment by edwin170** [comment]
> ```
> ERROR downloading the ilb please check the ios version and write it again. if this error
> happens a lot of time please use 0 to skip lib
> ```
> 
> 
>     
>   
> 
> wikiproxy running。。。。

use --keyServer instead of wikiproxy

**Comment by K1ym** [comment]
> > ```
> > ERROR downloading the ilb please check the ios version and write it again. if this error
> > happens a lot of time please use 0 to skip lib
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > wikiproxy running。。。。
> 
> use --keyServer instead of wikiproxy

thanks its worked
