### ISSUE TITLE
TypeError: function missing required argument 'initial_buffer_values' (pos 2)

### ISSUE THREAD

**Issue by herefor-vega8** [edwin170/downr1n#91]
Hi,
I am trying to downgrade iPhone 6s from 15.7.9 to 14.2 using downr1n.
However I get this error every single time I try it.t
![Screenshot_2024-01-27_12-26-36](https://github.com/edwin170/downr1n/assets/152514683/29274860-6198-46dc-86d1-742fdc202942)
I have no clue of what to do since, no one had this problem when I checked issues section of this repo.
Thanks

**Comment by edwin170** [comment]
in an attempt to simplify for anyone having the issue of SystemError: initial_buffer_values macro must be defined for '#' formats, please try the following 3 commands:

sudo pip uninstall lzss
sudo git clone https://github.com/m1stadev/pylzss && cd pylzss
sudo python3 setup.py install

and then re-run dualra1n,

**Comment by herefor-vega8** [comment]
Hi,
I have tried the above commands but no success. Shows the same error.

**Comment by edwin170** [comment]
> initial_buffer_values
is it showing th same error initial_buffer_values ?

**Comment by herefor-vega8** [comment]
> > initial_buffer_values
> > is it showing th same error initial_buffer_values ?

Yes

**Comment by edwin170** [comment]
> sudo pip uninstall lzss sudo git clone https://github.com/m1stadev/pylzss && cd pylzss sudo python3 setup.py install
> 
> and then re-run dualra1n,

sudo pzthon3 -m pip uninstall lzss
sudo git clone https://github.com/m1stadev/pylzss && cd pylzss
sudo python3 setup.py install

and then re-run dualra1n, this is a new commands please try it if you want to fix it

**Comment by herefor-vega8** [comment]
Tried the above, but still doesnt work. Shows the same error.

**Comment by herefor-vega8** [comment]
![Uploading Screenshot_2024-01-31_21-32-00.png…]()

**Comment by herefor-vega8** [comment]
![Screenshot_2024-01-31_21-32-00](https://github.com/edwin170/downr1n/assets/152514683/24592686-f7f2-4791-8e4c-a1f2be42f100)

Take a look.

**Comment by edwin170** [comment]
> ![Screenshot_2024-01-31_21-32-00](https://private-user-images.githubusercontent.com/152514683/301227306-24592686-f7f2-4791-8e4c-a1f2be42f100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTc1MDAsIm5iZiI6MTcwNjcxNzIwMCwicGF0aCI6Ii8xNTI1MTQ2ODMvMzAxMjI3MzA2LTI0NTkyNjg2LWY3ZjItNDc5MS04ZTRjLWExZjJiZTQyZjEwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxNjA2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjkwYzI3Zjk3YzYwMmEzMmVkNTYzNzkzN2YzZTk4NGY2ZmRmNWNmNmM0MDFkMTFkZjBhNGEwZTVmMTkzMzg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2jlMDw_u2KlCzyJ8PmODWnOASo4LFpy_8s0U6gMreng)
> 
> Take a look.

only execute sudo python3 -m pip uninstall lzss, and then execute downr1n again

**Comment by edwin170** [comment]
if it doesn't work check your distro

**Comment by edwin170** [comment]
> Changed distro and after running all required commands it works. But got a new error. Please look into this: ![Screenshot_2024-01-31_23-36-00](https://private-user-images.githubusercontent.com/152514683/301504936-44462a66-24fa-42a6-95dc-12a2d2ae9f03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTExOTAsIm5iZiI6MTcwNjc5MDg5MCwicGF0aCI6Ii8xNTI1MTQ2ODMvMzAxNTA0OTM2LTQ0NDYyYTY2LTI0ZmEtNDJhNi05NWRjLTEyYTJkMmFlOWYwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxMjM0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzM5ODcxMjJkMzU5YTQwOWEzYzRlNmZhZGFiNWYyNDJmNzU1M2M4ZTgzMzQzZDJjNWYxNWZjODdkNTY3MzAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WOI8ytiPWkU7wgevcZ5UXx6G-kHz2XPT7o9a3Lf_Rio)

try without sudo

**Comment by herefor-vega8** [comment]
Tried it still got the same error. Any other fix.

**Comment by edwin170** [comment]
> Tried it still got the same error. Any other fix.

if you have much storage, you could use dualra1n

**Comment by herefor-vega8** [comment]
No, don't have much. That is the reason Im using this. Is there a fix or something? Or do I give up?

**Comment by edwin170** [comment]
> No, don't have much. That is the reason Im using this. Is there a fix or something? Or do I give up?

if you are on iOS 15 below please use dualra1n with --downgrade argument instead of --dualboot argument

**Comment by herefor-vega8** [comment]
Im on 15.7.9

**Comment by edwin170** [comment]
https://github.com/dualra1n/dualra1n.git then you can use it. put the your .ipsw file into ipsw/ dir, then execute ./dualboot.sh --downgrade 14.3 (or the vers to downgrade).

**Comment by edwin170** [comment]
fixed, execute sudo python3.9 -m pip uninstall pylzss lzss, and then downr1n command again
