### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Alriceee** [edwin170/downr1n#92]
after getting past the TypeError: function missing required argument 'inital_buffer_values' (pos 2), everything goes normally and then i get this error: Segmentation fault (core dumped)

_this error is when i get to the future restore part_

**Comment by Alriceee** [comment]
_forgot to post the full log but here:_

isaiah@isaiah-IdeaPad-3-15ITL05:~/downr1n$ ./downr1n.sh --downgrade 14.3
You have to run this as root on Linux.
Please type your password
[*] Command ran: sudo ./downr1n.sh --downgrade 14.3
[22:58:55.302][3] usbmuxd v1.1.1 starting up
[22:58:55.302][3] Using libusb 1.0.25
[22:58:55.305][3] Initialization complete
downr1n | Version 3.0
Created by edwin, thanks palera1, and all people creator of path file boot

[*] Waiting for devices
[*] Detected DFU mode device
[*] Waiting for devices
[*] Detected DFU mode device
[*] Getting device info...
Detected cpid, your cpid is 0x8010
Detected model, your model is d101ap
Detected deviceid, your deviceid is iPhone9,3
[-] we found ipsw/iPhone_4.7_P3_14.3_18C66_Restore.ipsw, do you want to use it ? please write, yes or no
yes
ipsw/iPhone_4.7_P3_14.3_18C66_Restore.ipsw
[*] Checking if the ipsw is for your device
[*] Checking ipsw version
[*] Extracting ipsw, hang on please ...
[*] Got extract the IPSW successfully
[*] Creating ramdisk
[-] Ramdisk is already created so SKIPPING ...
[*] Booting ramdisk
[/] We couldn't get the ipsw curl. we will proceed with -k option with curl
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Waiting for the ramdisk to finish booting
bind(): Address in use
Error creating socket for listen port 2222: Address in use
libusb: warning [op_get_configuration] device unconfigured
libusb: error [op_get_active_config_descriptor] device unconfigured
[22:59:47.877][3] Could not get old configuration descriptor for device 3-89: LIBUSB_ERROR_NOT_FOUND
[22:59:47.887][3] Connecting to new device on location 0x30059 as ID 1
[22:59:47.931][3] Connected to v2.0 device 1 on location 0x30059 with serial number ramdisk tool Sep 18 2022 20:14:43
[22:59:47.932][2] device_control_input: Got unhandled payload type 5
[22:59:48.437][2] device_control_input: Got unhandled payload type 5
[*] Mounting filesystems ...
[*] Dumpped SHSH
[*] Checking device version
the version that the device is currently in is 15.8
[*] extracting kernel ...
[*] extracted
Reboot into recovery mode ...
[23:00:37.534][3] Removed device 1 on location 0x30059
[*] To get into DFU mode, you will be guided through 2 steps:
[*] Press any key when ready for DFU mode
Get ready (0)
Release side button, but keep holding volume down (9)
Release side button, but keep holding volume down (2)
[*] Device entered DFU!
[* ]Patching some boot files...
[*] Finished moving the boot files to work
[*] Decrypthing ibss and iboot
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[*] Patching the kernel
[*] Patching the kernel to restore using futurerestore
[*] Patching devicetree
[*] Patching the restored_external and asr, and saving them into the ramdisk ...
'work/devicetree.img4' -> 'boot/iPhone9,3/devicetree.img4'
'work/iBEC.img4' -> 'boot/iPhone9,3/iBEC.img4'
'work/iBSS.img4' -> 'boot/iPhone9,3/iBSS.img4'
'work/kernelcache.img4' -> 'boot/iPhone9,3/kernelcache.img4'
'work/trustcache.img4' -> 'boot/iPhone9,3/trustcache.img4'
[*] Sucess Patching the boot files
[*] Checking if the llb was already replaced
[*] Executing futurerestore ...
Press ENTER to continue with futurerestore, your device will start to restoring <-
Version: v2.0.0(36879969be71d56af062aa99be5f28ee482a12bc-309)
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
libipatcher version: 0.91-cb10d973d0af78cc55020d4cf1187c28fad0f2a0-RELEASE
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes
Checking for updates...
Futurerestore is up to date!
futurerestore: failed with exception:
[exception]:
what=can't init, no device found

code=20840493
line=318
file=/tmp/Builder/repos/futurerestore/src/main.cpp
commit count=309
commit sha  =36879969be71d56af062aa99be5f28ee482a12bc
if futurerestore failed you can try execute the command below
if futurerestore didn't finish succesfully please try to run (with sudo or without) this command: /home/isaiah/downr1n/binaries/Linux/futurerestore -t blobs/iPhone9,3-14.3.shsh2 --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --latest-baseband ipsw/iPhone_4.7_P3_14.3_18C66_Restore.ipsw
if futurerestore restore sucess, you can boot using  --boot

**Comment by Alriceee** [comment]
isaiah@isaiah-IdeaPad-3-15ITL05:~/downr1n$ /home/isaiah/downr1n/binaries/Linux/futurerestore -t blobs/iPhone9,3-14.3.shsh2 --use-pwndfu --skip-blob --rdsk work/rdsk.im4p --rkrn work/krnl.im4p --latest-sep --latest-baseband ipsw/iPhone_4.7_P3_14.3_18C66_Restore.ipsw
Version: v2.0.0(36879969be71d56af062aa99be5f28ee482a12bc-309)
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
libipatcher version: 0.91-cb10d973d0af78cc55020d4cf1187c28fad0f2a0-RELEASE
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes
Checking for updates...
Futurerestore is up to date!
[INFO] 64-bit device detected
futurerestore init done
reading signing ticket blobs/iPhone9,3-14.3.shsh2 is done
User specified to use latest signed SEP
Cached /tmp/futurerestore/sep.im4p not found, downloading a new one.
Downloading SEP
_loading bs that i removed so github wouldn't compain (basically just [======#>]_
Checking if SEP is being signed...
Sending TSS request attempt 1... response successfully received
SEP is being signed!
User specified to use latest signed baseband
Downloading Baseband
_loading bs that i removed so github wouldn't compain (basically just [======#>]_
Checking if Baseband is being signed...
Sending TSS request attempt 1... response successfully received
Baseband is being signed!
Downloading the latest firmware components...
Finished downloading the latest firmware components!
Found device in DFU mode
requesting to get into pwnRecovery later
Found device in DFU mode
Identified device as d101ap, iPhone9,3
Extracting BuildManifest from iPSW
Product version: 14.3
Product build: 18C66 Major: 18
Device supports Image4: true
checking if the APTicket is valid for this restore...
Verified ECID in APTicket matches the device's ECID
checking if the APTicket is valid for this restore...
Verified ECID in APTicket matches the device's ECID
[IMG4TOOL] checking buildidentity 0:
[IMG4TOOL] checking buildidentity matches board ... YES
[IMG4TOOL] checking buildidentity has all required hashes:
[IMG4TOOL] checking hash for "AOP"                     OK (untrusted)
[IMG4TOOL] checking hash for "Ap,SystemVolumeCanonicalMetadata"BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "AppleLogo"               BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BasebandFirmware"        IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "BatteryCharging0"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryCharging1"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryFull"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryLow0"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryLow1"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryPlugin"           BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "DeviceTree"              BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Homer"                   OK (untrusted)
[IMG4TOOL] checking hash for "KernelCache"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "LLB"                     BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Liquid"                  BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "OS"                      BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RecoveryMode"            BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreDeviceTree"       BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreKernelCache"      BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreLogo"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreRamDisk"          BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreSEP"              BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreTrustCache"       BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "SEP"                     BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "StaticTrustCache"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "SystemVolume"            BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "ftap"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "ftsp"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "iBEC"                    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "iBSS"                    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "iBoot"                   BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "rfta"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "rfts"                    IGN (no digest in BuildManifest)

failed verification with error:
[exception]:
what=verification failed!
code=84279308
line=1286
file=img4tool.cpp
commit count=197
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f
[IMG4TOOL] checking buildidentity 1:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 2:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 3:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 4:
[IMG4TOOL] checking buildidentity matches board ... YES
[IMG4TOOL] checking buildidentity has all required hashes:
[IMG4TOOL] checking hash for "AOP"                     OK (untrusted)
[IMG4TOOL] checking hash for "Ap,SystemVolumeCanonicalMetadata"BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "AppleLogo"               BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BasebandFirmware"        IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "BatteryCharging0"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryCharging1"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryFull"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryLow0"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryLow1"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryPlugin"           BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "DeviceTree"              BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Homer"                   OK (untrusted)
[IMG4TOOL] checking hash for "KernelCache"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "LLB"                     BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Liquid"                  BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "OS"                      BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RecoveryMode"            BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreDeviceTree"       BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreKernelCache"      BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreLogo"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreRamDisk"          BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreSEP"              BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreTrustCache"       BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "SEP"                     BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "StaticTrustCache"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "SystemVolume"            BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "ftap"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "ftsp"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "iBEC"                    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "iBSS"                    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "iBoot"                   BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "rfta"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "rfts"                    IGN (no digest in BuildManifest)

failed verification with error:
[exception]:
what=verification failed!
code=84279308
line=1286
file=img4tool.cpp
commit count=197
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f
[IMG4TOOL] checking buildidentity 5:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 6:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 7:
[IMG4TOOL] checking buildidentity matches board ... NO
[WARNING] NOT VALIDATING SHSH BLOBS IM4M!
[Error] BuildIdentity selected for restore does not match APTicket

BuildIdentity selected for restore:
BuildNumber : 18C66
BuildTrain : AzulC
DeviceClass : d101ap
FDRSupport : YES
MobileDeviceMinVersion : 1253
RestoreBehavior : Erase
Variant : Customer Erase Install (IPSW)

BuildIdentity is valid for the APTicket:
IM4M is not valid for any restore within the Buildmanifest
This APTicket can't be used for restoring this firmware
[WARNING] NOT VALIDATING SHSH BLOBS!
Variant: Customer Erase Install (IPSW)
This restore will erase all device data.
Device found in DFU Mode.
Getting firmware keys for: d101ap
Patching iBSS
Extracting iBSS.d10.RELEASE.im4p (Firmware/dfu/iBSS.d10.RELEASE.im4p)...
payload decrypted
iBoot64Patch: Staring iBoot64Patch!
iOS 14 iBoot detected!
iBoot64Patch: Inited ibootpatchfinder64!
iBoot64Patch: Added sigpatches!
iBoot64Patch: Added unlock nvram patch!
iBoot64Patch: Added freshnonce patch!
iBoot64Patch: has_kernel_load is false!
iBoot64Patch: Applying patch=0x1800c2bd4 : 000080d2
iBoot64Patch: Applying patch=0x1800c2c20 : 000080d2
iBoot64Patch: Applying patch=0x1800b3928 : 000080d2c0035fd6
iBoot64Patch: Applying patch=0x1800b3978 : 000080d2c0035fd6
iBoot64Patch: Applying patch=0x1800f0b50 : 000080d2c0035fd6
iBoot64Patch: Applying patch=0x1800c86fc : 1f2003d5
iBoot64Patch: Patches applied!
Patching iBEC
Extracting iBEC.d10.RELEASE.im4p (Firmware/dfu/iBEC.d10.RELEASE.im4p)...
payload decrypted
iBoot64Patch: Staring iBoot64Patch!
iOS 14 iBoot detected!
iBoot64Patch: Inited ibootpatchfinder64!
iBoot64Patch: Added sigpatches!
iBoot64Patch: Added unlock nvram patch!
iBoot64Patch: Added freshnonce patch!
iBoot64Patch: has_kernel_load is true!
iBoot64Patch: Added debugenabled patch!
iBoot64Patch: Added bootarg patch!
iBoot64Patch: Applying patch=0x1800c2bd4 : 000080d2
iBoot64Patch: Applying patch=0x1800c2c20 : 000080d2
iBoot64Patch: Applying patch=0x1800b3928 : 000080d2c0035fd6
iBoot64Patch: Applying patch=0x1800b3978 : 000080d2c0035fd6
iBoot64Patch: Applying patch=0x1800f0b50 : 000080d2c0035fd6
iBoot64Patch: Applying patch=0x1800c86fc : 1f2003d5
iBoot64Patch: Applying patch=0x1800c456c : 200080d2
iBoot64Patch: Applying patch=0x1800c59e8 : a9153230
iBoot64Patch: Applying patch=0x180129c9d : 72643d6d6430206e616e642d656e61626c652d7265666f726d61743d307831202d76202d726573746f72652064656275673d30783230313465206b65657073796d733d30783120616d66693d3078666620616d66695f616c6c6f775f616e795f7369676e61747572653d30783120616d66695f6765745f6f75745f6f665f6d795f7761793d3078312063735f656e666f7263656d656e745f64697361626c653d30783100
iBoot64Patch: Applying patch=0x1800c59f4 : f30309aa
iBoot64Patch: Applying patch=0x1800c5ae4 : d30d3230
iBoot64Patch: Patches applied!
Repacking patched iBSS as IMG4
Repacking patched iBEC as IMG4
Sending iBSS (522513 bytes)...
[==================================================] 100.0%
Booting iBSS, waiting for device to disconnect...
Booting iBSS, waiting for device to reconnect...
ApNonce pre-hax:
INFO: device serial number is F17V20XRHG7N
Getting ApNonce in recovery mode... 69 ac 42 ff 14 58 4e 1b af c8 cf 90 e3 f3 bf b5 70 73 06 3c 84 ae 7f f8 73 8e 4e 8b 21 43 7d c9 
Sending iBEC (522513 bytes)...
[==================================================] 100.0%
Booting iBEC, waiting for device to disconnect...
Booting iBEC, waiting for device to reconnect...
APNonce from device already matches IM4M nonce, no need for extra hax...
Successfully set nonce generator: 0x2e5d158e959c1669
Extracting filesystem from iPSW
Segmentation fault (core dumped)

**Comment by edwin170** [comment]
> i mean is close to a terabyte enough?

more than 16 gb it is very good to use dualra1n

**Comment by edwin170** [comment]
https://github.com/dualra1n/dualra1n

**Comment by edwin170** [comment]
> i mean is close to a terabyte enough?

yes it is good, more than 10 gb free is good

**Comment by Alriceee** [comment]
Then what else causes that to happen?

**Comment by edwin170** [comment]
> Then what else causes that to happen?
> 
> Edit: i'm using ubuntu 22.04

tbh idk, how many ram does your pc have ?

**Comment by Alriceee** [comment]
> > Then what else causes that to happen?
> > Edit: i'm using ubuntu 22.04
> 
> tbh idk, how many ram does your pc have ?

16 gb of ram

**Comment by Alriceee** [comment]
sooo..trying again and i'm getting this: 



[=] Hi, please i need that you write the ios version that this device is on or the version of the ios that it was on (if this device is already downgraded), most of the time is the lastest version of ios. write 0 if you want to skip this (it is not recommended to skip this as this can avoid false dfu mode)
Version detected!. we are gonna use 
[-] ERROR downloading the llb please check the ios version and write it again. if this error happens a lot of time please use 0 to skip llb
