### ISSUE TITLE
lỗi Done: restoring failed!

### ISSUE THREAD

**Issue by linhbg1998** [edwin170/downr1n#94]
Checking if Baseband is being signed...
Sending TSS request attempt 1... response successfully received
Baseband is being signed!
Downloading the latest firmware components...
Finished downloading the latest firmware components!
Found device in DFU mode
requesting to get into pwnRecovery later
Found device in DFU mode
Identified device as d111ap, iPhone9,4
Extracting BuildManifest from iPSW
Product version: 14.5
Product build: 18E199 Major: 18
Device supports Image4: true
checking if the APTicket is valid for this restore...
Verified ECID in APTicket matches the device's ECID
checking if the APTicket is valid for this restore...
Verified ECID in APTicket matches the device's ECID
[IMG4TOOL] checking buildidentity 0:
[IMG4TOOL] checking buildidentity matches board ... YES
[IMG4TOOL] checking buildidentity has all required hashes:
[IMG4TOOL] checking hash for "AOP"                     OK (untrusted)
[IMG4TOOL] checking hash for "Ap,SystemVolumeCanonicalMetadata"BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "AppleLogo"               BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BasebandFirmware"        IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "BatteryCharging0"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryCharging1"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryFull"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryLow0"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryLow1"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryPlugin"           BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "DeviceTree"              BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Homer"                   OK (untrusted)
[IMG4TOOL] checking hash for "KernelCache"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "LLB"                     BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Liquid"                  BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "OS"                      BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RecoveryMode"            BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreDeviceTree"       BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreKernelCache"      BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreLogo"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreRamDisk"          BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreSEP"              BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreTrustCache"       BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "SEP"                     BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "StaticTrustCache"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "SystemVolume"            BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "ftap"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "ftsp"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "iBEC"                    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "iBSS"                    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "iBoot"                   BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "rfta"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "rfts"                    IGN (no digest in BuildManifest)

failed verification with error:
[exception]:
what=verification failed!
code=84279308
line=1286
file=img4tool.cpp
commit count=197
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f
[IMG4TOOL] checking buildidentity 1:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 2:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 3:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 4:
[IMG4TOOL] checking buildidentity matches board ... YES
[IMG4TOOL] checking buildidentity has all required hashes:
[IMG4TOOL] checking hash for "AOP"                     OK (untrusted)
[IMG4TOOL] checking hash for "Ap,SystemVolumeCanonicalMetadata"BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "AppleLogo"               BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BasebandFirmware"        IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "BatteryCharging0"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryCharging1"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryFull"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryLow0"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryLow1"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "BatteryPlugin"           BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "DeviceTree"              BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Homer"                   OK (untrusted)
[IMG4TOOL] checking hash for "KernelCache"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "LLB"                     BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Liquid"                  BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "OS"                      BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RecoveryMode"            BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreDeviceTree"       BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreKernelCache"      BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreLogo"             BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreRamDisk"          BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreSEP"              BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "RestoreTrustCache"       BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "SEP"                     BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "StaticTrustCache"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "SystemVolume"            BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "ftap"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "ftsp"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "iBEC"                    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "iBSS"                    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "iBoot"                   BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "rfta"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "rfts"                    IGN (no digest in BuildManifest)

failed verification with error:
[exception]:
what=verification failed!
code=84279308
line=1286
file=img4tool.cpp
commit count=197
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f
[IMG4TOOL] checking buildidentity 5:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 6:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 7:
[IMG4TOOL] checking buildidentity matches board ... NO
[WARNING] NOT VALIDATING SHSH BLOBS IM4M!
[Error] BuildIdentity selected for restore does not match APTicket

BuildIdentity selected for restore:
BuildNumber : 18E199
BuildTrain : AzulE
DeviceClass : d111ap
FDRSupport : YES
MobileDeviceMinVersion : 1253.100.1
RestoreBehavior : Erase
Variant : Customer Erase Install (IPSW)

BuildIdentity is valid for the APTicket:
IM4M is not valid for any restore within the Buildmanifest
This APTicket can't be used for restoring this firmware
[WARNING] NOT VALIDATING SHSH BLOBS!
Variant: Customer Erase Install (IPSW)
This restore will erase all device data.
Device found in DFU Mode.
Sending iBSS (522642 bytes)...
[==================================================] 100.0%
Booting iBSS, waiting for device to disconnect...
Booting iBSS, waiting for device to reconnect...
ApNonce pre-hax:
INFO: device serial number is DX3XW3F3HG06
Getting ApNonce in recovery mode... af 86 67 e4 30 7a b1 d8 0b 57 3e c9 13 31 04 c9 7c cb 2a f4 97 e9 41 b1 28 6d af 57 40 1c e4 5f 
Sending iBEC (522642 bytes)...
[==================================================] 100.0%
ERROR: Could not read data (-256). Aborting.
Booting iBEC, waiting for device to disconnect...
Booting iBEC, waiting for device to reconnect...
APNonce from device already matches IM4M nonce, no need for extra hax...
Successfully set nonce generator: 0xa100e274f0dd5b32
Using cached filesystem from 'ipsw/iPhone_5.5_P3_14.5_18E199_Restore/038-45251-252.dmg'
Getting SepNonce in recovery mode... cc af 1a 4b 0d c2 26 fb 1c 49 ad 04 5b 56 af d8 1c d4 b1 ed 
Getting ApNonce in recovery mode... af 86 67 e4 30 7a b1 d8 0b 57 3e c9 13 31 04 c9 7c cb 2a f4 97 e9 41 b1 28 6d af 57 40 1c e4 5f 
[WARNING] Setting bgcolor to green! If you don't see a green screen, then your device didn't boot iBEC correctly
Recovery Mode Environment:
iBoot build-version=iBoot-6723.102.4
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@3x~iphone.im4p (Firmware/all_flash/applelogo@3x~iphone.im4p)...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (20264 bytes)...
ramdisk-size=0x20000000
1337 CUSTOM RAMDISK!
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (105211269 bytes)...
Extracting 038-44812-292.dmg.trustcache (Firmware/038-44812-292.dmg.trustcache)...
Personalizing IMG4 component RestoreTrustCache...
Sending RestoreTrustCache (11860 bytes)...
Extracting DeviceTree.d111ap.im4p (Firmware/all_flash/DeviceTree.d111ap.im4p)...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (36739 bytes)...
Extracting sep-firmware.d111.RELEASE.im4p (Firmware/all_flash/sep-firmware.d111.RELEASE.im4p)...
Personalizing IMG4 component RestoreSEP...
Sending RestoreSEP (1387604 bytes)...
1337 CUSTOM KERNEL!
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (20235929 bytes)...
getting SEP ticket
Trying to fetch new SHSH blob
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Connecting now...
Connected to com.apple.mobile.restored, version 15
Device ffffffffffffffffffffffffffffffff00000012 has successfully entered restore mode
Hardware Information:
BoardID: 14
ChipID: 32784
UniqueChipID: 2537883639480358
ProductionMode: true
Starting Reverse Proxy
ReverseProxy[Ctrl]: (status=1) Ready
Checkpoint 1621 complete with code 0
Checkpoint 1540 complete with code 0
Checkpoint 1679 complete with code 0
Checkpoint 1544 complete with code 0
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Checkpoint 1547 complete with code 0
Waiting for NAND (28)
Checkpoint 1549 complete with code 0
Updating NAND Firmware (58)
Checkpoint 1550 complete with code 0
Checkpoint 1551 complete with code 0
Checkpoint 1628 complete with code 0
Checkpoint 1552 complete with code 0
Checkpoint 1555 complete with code 0
Checkpoint 1662 complete with code 0
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.d11.RELEASE.im4p (Firmware/all_flash/LLB.d11.RELEASE.im4p)...
Personalizing IMG4 component LLB...
Extracting applelogo@3x~iphone.im4p (Firmware/all_flash/applelogo@3x~iphone.im4p)...
Personalizing IMG4 component AppleLogo...
Extracting batterycharging0@3x~iphone.im4p (Firmware/all_flash/batterycharging0@3x~iphone.im4p)...
Personalizing IMG4 component BatteryCharging0...
Extracting batterycharging1@3x~iphone.im4p (Firmware/all_flash/batterycharging1@3x~iphone.im4p)...
Personalizing IMG4 component BatteryCharging1...
Extracting batteryfull@3x~iphone.im4p (Firmware/all_flash/batteryfull@3x~iphone.im4p)...
Personalizing IMG4 component BatteryFull...
Extracting batterylow0@3x~iphone.im4p (Firmware/all_flash/batterylow0@3x~iphone.im4p)...
Personalizing IMG4 component BatteryLow0...
Extracting batterylow1@3x~iphone.im4p (Firmware/all_flash/batterylow1@3x~iphone.im4p)...
Personalizing IMG4 component BatteryLow1...
Extracting glyphplugin@1920~iphone-lightning.im4p (Firmware/all_flash/glyphplugin@1920~iphone-lightning.im4p)...
Personalizing IMG4 component BatteryPlugin...
Extracting DeviceTree.d111ap.im4p (Firmware/all_flash/DeviceTree.d111ap.im4p)...
Personalizing IMG4 component DeviceTree...
Extracting liquiddetect@1920~iphone-lightning.im4p (Firmware/all_flash/liquiddetect@1920~iphone-lightning.im4p)...
Personalizing IMG4 component Liquid...
Extracting recoverymode@1920~iphone-lightning.im4p (Firmware/all_flash/recoverymode@1920~iphone-lightning.im4p)...
Personalizing IMG4 component RecoveryMode...
Extracting iBoot.d11.RELEASE.im4p (Firmware/all_flash/iBoot.d11.RELEASE.im4p)...
Personalizing IMG4 component iBoot...
Personalizing IMG4 component RestoreSEP...
Personalizing IMG4 component SEP...
Sending NORData now...
Done sending NORData
Checkpoint 1545 complete with code 0
Checkpoint 1683 complete with code 0
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Checkpoint 1637 complete with code 0
Checkpoint 1556 complete with code 0
Checkpoint 1686 complete with code 0
Checkpoint 1620 complete with code 0
Checkpoint 1687 complete with code 0
Checkpoint 1557 complete with code 0
About to send FDR Trust data...
Sending FDR Trust data now...
Done sending FDR Trust Data
Checkpoint 1558 complete with code 0
Checkpoint 1559 complete with code 0
Checkpoint 1560 complete with code 0
Checking for uncollected logs (44)
Checkpoint 1561 complete with code 0
Checking for uncollected logs (44)
ReverseProxy[Ctrl]: (status=2) Terminated
Cleaning up...
[exception]:
what=ERROR: Unable to restore device

code=92995652
line=1419
file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp
commit count=309
commit sha  =36879969be71d56af062aa99be5f28ee482a12bc
Done: restoring failed!

**Comment by edwin170** [comment]
> Checking if Baseband is being signed... Sending TSS request attempt 1... response successfully received Baseband is being signed! Downloading the latest firmware components... Finished downloading the latest firmware components! Found device in DFU mode requesting to get into pwnRecovery later Found device in DFU mode Identified device as d111ap, iPhone9,4 Extracting BuildManifest from iPSW Product version: 14.5 Product build: 18E199 Major: 18 Device supports Image4: true checking if the APTicket is valid for this restore... Verified ECID in APTicket matches the device's ECID checking if the APTicket is valid for this restore... Verified ECID in APTicket matches the device's ECID [IMG4TOOL] checking buildidentity 0: [IMG4TOOL] checking buildidentity matches board ... YES [IMG4TOOL] checking buildidentity has all required hashes: [IMG4TOOL] checking hash for "AOP" OK (untrusted) [IMG4TOOL] checking hash for "Ap,SystemVolumeCanonicalMetadata"BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "AppleLogo" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BasebandFirmware" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "BatteryCharging0" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryCharging1" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryFull" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryLow0" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryLow1" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryPlugin" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "DeviceTree" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "Homer" OK (untrusted) [IMG4TOOL] checking hash for "KernelCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "LLB" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "Liquid" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "OS" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RecoveryMode" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreDeviceTree" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreKernelCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreLogo" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreRamDisk" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreSEP" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreTrustCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "SEP" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "StaticTrustCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "SystemVolume" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "ftap" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "ftsp" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "iBEC" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "iBSS" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "iBoot" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "rfta" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "rfts" IGN (no digest in BuildManifest)
> 
> failed verification with error: [exception]: what=verification failed! code=84279308 line=1286 file=img4tool.cpp commit count=197 commit sha =aca6cf005c94caf135023263cbb5c61a0081804f [IMG4TOOL] checking buildidentity 1: [IMG4TOOL] checking buildidentity matches board ... NO [IMG4TOOL] checking buildidentity 2: [IMG4TOOL] checking buildidentity matches board ... NO [IMG4TOOL] checking buildidentity 3: [IMG4TOOL] checking buildidentity matches board ... NO [IMG4TOOL] checking buildidentity 4: [IMG4TOOL] checking buildidentity matches board ... YES [IMG4TOOL] checking buildidentity has all required hashes: [IMG4TOOL] checking hash for "AOP" OK (untrusted) [IMG4TOOL] checking hash for "Ap,SystemVolumeCanonicalMetadata"BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "AppleLogo" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BasebandFirmware" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "BatteryCharging0" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryCharging1" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryFull" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryLow0" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryLow1" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "BatteryPlugin" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "DeviceTree" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "Homer" OK (untrusted) [IMG4TOOL] checking hash for "KernelCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "LLB" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "Liquid" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "OS" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RecoveryMode" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreDeviceTree" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreKernelCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreLogo" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreRamDisk" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreSEP" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "RestoreTrustCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "SEP" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "StaticTrustCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "SystemVolume" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "ftap" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "ftsp" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "iBEC" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "iBSS" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "iBoot" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "rfta" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "rfts" IGN (no digest in BuildManifest)
> 
> failed verification with error: [exception]: what=verification failed! code=84279308 line=1286 file=img4tool.cpp commit count=197 commit sha =aca6cf005c94caf135023263cbb5c61a0081804f [IMG4TOOL] checking buildidentity 5: [IMG4TOOL] checking buildidentity matches board ... NO [IMG4TOOL] checking buildidentity 6: [IMG4TOOL] checking buildidentity matches board ... NO [IMG4TOOL] checking buildidentity 7: [IMG4TOOL] checking buildidentity matches board ... NO [WARNING] NOT VALIDATING SHSH BLOBS IM4M! [Error] BuildIdentity selected for restore does not match APTicket
> 
> BuildIdentity selected for restore: BuildNumber : 18E199 BuildTrain : AzulE DeviceClass : d111ap FDRSupport : YES MobileDeviceMinVersion : 1253.100.1 RestoreBehavior : Erase Variant : Customer Erase Install (IPSW)
> 
> BuildIdentity is valid for the APTicket: IM4M is not valid for any restore within the Buildmanifest This APTicket can't be used for restoring this firmware [WARNING] NOT VALIDATING SHSH BLOBS! Variant: Customer Erase Install (IPSW) This restore will erase all device data. Device found in DFU Mode. Sending iBSS (522642 bytes)... [==================================================] 100.0% Booting iBSS, waiting for device to disconnect... Booting iBSS, waiting for device to reconnect... ApNonce pre-hax: INFO: device serial number is DX3XW3F3HG06 Getting ApNonce in recovery mode... af 86 67 e4 30 7a b1 d8 0b 57 3e c9 13 31 04 c9 7c cb 2a f4 97 e9 41 b1 28 6d af 57 40 1c e4 5f Sending iBEC (522642 bytes)... [==================================================] 100.0% ERROR: Could not read data (-256). Aborting. Booting iBEC, waiting for device to disconnect... Booting iBEC, waiting for device to reconnect... APNonce from device already matches IM4M nonce, no need for extra hax... Successfully set nonce generator: 0xa100e274f0dd5b32 Using cached filesystem from 'ipsw/iPhone_5.5_P3_14.5_18E199_Restore/038-45251-252.dmg' Getting SepNonce in recovery mode... cc af 1a 4b 0d c2 26 fb 1c 49 ad 04 5b 56 af d8 1c d4 b1 ed Getting ApNonce in recovery mode... af 86 67 e4 30 7a b1 d8 0b 57 3e c9 13 31 04 c9 7c cb 2a f4 97 e9 41 b1 28 6d af 57 40 1c e4 5f [WARNING] Setting bgcolor to green! If you don't see a green screen, then your device didn't boot iBEC correctly Recovery Mode Environment: iBoot build-version=iBoot-6723.102.4 iBoot build-style=RELEASE Sending RestoreLogo... Extracting applelogo@3x~iphone.im4p (Firmware/all_flash/applelogo@3x~iphone.im4p)... Personalizing IMG4 component RestoreLogo... Sending RestoreLogo (20264 bytes)... ramdisk-size=0x20000000 1337 CUSTOM RAMDISK! Personalizing IMG4 component RestoreRamDisk... Sending RestoreRamDisk (105211269 bytes)... Extracting 038-44812-292.dmg.trustcache (Firmware/038-44812-292.dmg.trustcache)... Personalizing IMG4 component RestoreTrustCache... Sending RestoreTrustCache (11860 bytes)... Extracting DeviceTree.d111ap.im4p (Firmware/all_flash/DeviceTree.d111ap.im4p)... Personalizing IMG4 component RestoreDeviceTree... Sending RestoreDeviceTree (36739 bytes)... Extracting sep-firmware.d111.RELEASE.im4p (Firmware/all_flash/sep-firmware.d111.RELEASE.im4p)... Personalizing IMG4 component RestoreSEP... Sending RestoreSEP (1387604 bytes)... 1337 CUSTOM KERNEL! Personalizing IMG4 component RestoreKernelCache... Sending RestoreKernelCache (20235929 bytes)... getting SEP ticket Trying to fetch new SHSH blob Sending TSS request attempt 1... response successfully received Received SHSH blobs About to restore device... Connecting now... Connected to com.apple.mobile.restored, version 15 Device ffffffffffffffffffffffffffffffff00000012 has successfully entered restore mode Hardware Information: BoardID: 14 ChipID: 32784 UniqueChipID: 2537883639480358 ProductionMode: true Starting Reverse Proxy ReverseProxy[Ctrl]: (status=1) Ready Checkpoint 1621 complete with code 0 Checkpoint 1540 complete with code 0 Checkpoint 1679 complete with code 0 Checkpoint 1544 complete with code 0 About to send RootTicket... Sending RootTicket now... Done sending RootTicket Checkpoint 1547 complete with code 0 Waiting for NAND (28) Checkpoint 1549 complete with code 0 Updating NAND Firmware (58) Checkpoint 1550 complete with code 0 Checkpoint 1551 complete with code 0 Checkpoint 1628 complete with code 0 Checkpoint 1552 complete with code 0 Checkpoint 1555 complete with code 0 Checkpoint 1662 complete with code 0 About to send NORData... Found firmware path Firmware/all_flash Getting firmware manifest from build identity Extracting LLB.d11.RELEASE.im4p (Firmware/all_flash/LLB.d11.RELEASE.im4p)... Personalizing IMG4 component LLB... Extracting applelogo@3x~iphone.im4p (Firmware/all_flash/applelogo@3x~iphone.im4p)... Personalizing IMG4 component AppleLogo... Extracting batterycharging0@3x~iphone.im4p (Firmware/all_flash/batterycharging0@3x~iphone.im4p)... Personalizing IMG4 component BatteryCharging0... Extracting batterycharging1@3x~iphone.im4p (Firmware/all_flash/batterycharging1@3x~iphone.im4p)... Personalizing IMG4 component BatteryCharging1... Extracting batteryfull@3x~iphone.im4p (Firmware/all_flash/batteryfull@3x~iphone.im4p)... Personalizing IMG4 component BatteryFull... Extracting batterylow0@3x~iphone.im4p (Firmware/all_flash/batterylow0@3x~iphone.im4p)... Personalizing IMG4 component BatteryLow0... Extracting batterylow1@3x~iphone.im4p (Firmware/all_flash/batterylow1@3x~iphone.im4p)... Personalizing IMG4 component BatteryLow1... Extracting glyphplugin@1920~iphone-lightning.im4p (Firmware/all_flash/glyphplugin@1920~iphone-lightning.im4p)... Personalizing IMG4 component BatteryPlugin... Extracting DeviceTree.d111ap.im4p (Firmware/all_flash/DeviceTree.d111ap.im4p)... Personalizing IMG4 component DeviceTree... Extracting liquiddetect@1920~iphone-lightning.im4p (Firmware/all_flash/liquiddetect@1920~iphone-lightning.im4p)... Personalizing IMG4 component Liquid... Extracting recoverymode@1920~iphone-lightning.im4p (Firmware/all_flash/recoverymode@1920~iphone-lightning.im4p)... Personalizing IMG4 component RecoveryMode... Extracting iBoot.d11.RELEASE.im4p (Firmware/all_flash/iBoot.d11.RELEASE.im4p)... Personalizing IMG4 component iBoot... Personalizing IMG4 component RestoreSEP... Personalizing IMG4 component SEP... Sending NORData now... Done sending NORData Checkpoint 1545 complete with code 0 Checkpoint 1683 complete with code 0 Unmounting filesystems (29) Unmounting filesystems (29) Unmounting filesystems (29) Unmounting filesystems (29) Unmounting filesystems (29) Unmounting filesystems (29) Checkpoint 1637 complete with code 0 Checkpoint 1556 complete with code 0 Checkpoint 1686 complete with code 0 Checkpoint 1620 complete with code 0 Checkpoint 1687 complete with code 0 Checkpoint 1557 complete with code 0 About to send FDR Trust data... Sending FDR Trust data now... Done sending FDR Trust Data Checkpoint 1558 complete with code 0 Checkpoint 1559 complete with code 0 Checkpoint 1560 complete with code 0 Checking for uncollected logs (44) Checkpoint 1561 complete with code 0 Checking for uncollected logs (44) ReverseProxy[Ctrl]: (status=2) Terminated Cleaning up... [exception]: what=ERROR: Unable to restore device
> 
> code=92995652 line=1419 file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp commit count=309 commit sha =36879969be71d56af062aa99be5f28ee482a12bc Done: restoring failed!

what device, on what ios it was and what ios are you trying to downgrade to ?

**Comment by edwin170** [comment]
> iPhone 7 plus GSM iOS 15.7 -->ios14.5

restore to lasteset version and try again
