### ISSUE TITLE
RESTORING FAILED!

### ISSUE THREAD

**Issue by gergerking18** [edwin170/downr1n#95]
Checking if Baseband is being signed...
Sending TSS request attempt 1... response successfully received
Baseband is being signed!
Downloading the latest firmware components...
Finished downloading the latest firmware components!
Found device in Recovery mode
Device already in recovery mode
Cleaning up...
[exception]:
what=--use-pwndfu was specified, but device found in recovery mode!
code=61734966
line=942
file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp
commit count=309
commit sha  =36879969be71d56af062aa99be5f28ee482a12bc
Done: restoring failed!

MY DEVICE IS IPHONE 6SPLUS TRYING TO DOWNGRADE TO 14.8 BIT THIS HAPPENS EVERTIME! please help me what is the problem

**Comment by edwin170** [comment]
> Checking if Baseband is being signed... Sending TSS request attempt 1... response successfully received Baseband is being signed! Downloading the latest firmware components... Finished downloading the latest firmware components! Found device in Recovery mode Device already in recovery mode Cleaning up... [exception]: what=--use-pwndfu was specified, but device found in recovery mode! code=61734966 line=942 file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp commit count=309 commit sha =36879969be71d56af062aa99be5f28ee482a12bc Done: restoring failed!
> 
> MY DEVICE IS IPHONE 6SPLUS TRYING TO DOWNGRADE TO 14.8 BIT THIS HAPPENS EVERTIME! please help me what is the problem

because you did the futurerestore command when the iPhone is on recovery mode and that is bad, it must be on dfu mode and pwned

**Comment by gergerking18** [comment]
> > Checking if Baseband is being signed... Sending TSS request attempt 1... response successfully received Baseband is being signed! Downloading the latest firmware components... Finished downloading the latest firmware components! Found device in Recovery mode Device already in recovery mode Cleaning up... [exception]: what=--use-pwndfu was specified, but device found in recovery mode! code=61734966 line=942 file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp commit count=309 commit sha =36879969be71d56af062aa99be5f28ee482a12bc Done: restoring failed!
> > MY DEVICE IS IPHONE 6SPLUS TRYING TO DOWNGRADE TO 14.8 BIT THIS HAPPENS EVERTIME! please help me what is the problem
>

**Comment by gergerking18** [comment]
[IMG4TOOL] checking hash for "SEP"                     BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "StaticTrustCache"        BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "SystemVolume"            BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "ftap"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "ftsp"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "iBEC"                    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "iBSS"                    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "iBoot"                   BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "rfta"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "rfts"                    IGN (no digest in BuildManifest)

failed verification with error:
[exception]:
what=verification failed!
code=84279308
line=1286
file=img4tool.cpp
commit count=197
commit sha  =aca6cf005c94caf135023263cbb5c61a0081804f
[WARNING] NOT VALIDATING SHSH BLOBS IM4M!
[Error] BuildIdentity selected for restore does not match APTicket

BuildIdentity selected for restore:
BuildNumber : 18H17
BuildTrain : AzulSecuritySky
DeviceClass : n66map
FDRSupport : YES
MobileDeviceMinVersion : 1253.100.1
RestoreBehavior : Erase
Variant : Customer Erase Install (IPSW)

BuildIdentity is valid for the APTicket:
IM4M is not valid for any restore within the Buildmanifest
This APTicket can't be used for restoring this firmware
[WARNING] NOT VALIDATING SHSH BLOBS!
Variant: Customer Erase Install (IPSW)
This restore will erase all device data.
Device found in DFU Mode.
Getting firmware keys for: n66map
Patching iBSS
Extracting iBSS.n66m.RELEASE.im4p (Firmware/dfu/iBSS.n66m.RELEASE.im4p)...
payload decrypted
iBoot64Patch: Staring iBoot64Patch!
iOS 14 iBoot detected!
iBoot64Patch: Inited ibootpatchfinder64!
iBoot64Patch: Added sigpatches!
iBoot64Patch: Added unlock nvram patch!
iBoot64Patch: Added freshnonce patch!
iBoot64Patch: has_kernel_load is false!
iBoot64Patch: Applying patch=0x18038ffc8 : 000080d2
iBoot64Patch: Applying patch=0x18039006c : 000080d2
iBoot64Patch: Patches applied!
Patching iBEC
Extracting iBEC.n66m.RELEASE.im4p (Firmware/dfu/iBEC.n66m.RELEASE.im4p)...
payload decrypted
iBoot64Patch: Staring iBoot64Patch!
iOS 14 iBoot detected!
iBoot64Patch: Inited ibootpatchfinder64!
iBoot64Patch: Added sigpatches!
iBoot64Patch: Added unlock nvram patch!
iBoot64Patch: Added freshnonce patch!
iBoot64Patch: has_kernel_load is true!
iBoot64Patch: Added debugenabled patch!
iBoot64Patch: Added bootarg patch!
iBoot64Patch: Applying patch=0x87000eed4 : 000080d2
iBoot64Patch: Applying patch=0x87000ef28 : 000080d2
iBoot64Patch: Applying patch=0x870003d64 : 000080d2c0035fd6
iBoot64Patch: Applying patch=0x870003db4 : 000080d2c0035fd6
iBoot64Patch: Applying patch=0x870032e7c : 000080d2c0035fd6
iBoot64Patch: Applying patch=0x8700147fc : 1f2003d5
iBoot64Patch: Applying patch=0x870010878 : 200080d2
iBoot64Patch: Applying patch=0x870011e88 : 7af62930
iBoot64Patch: Applying patch=0x870065d55 : 72643d6d6430206e616e642d656e61626c652d7265666f726d61743d307831202d76202d726573746f72652064656275673d30783230313465206b65657073796d733d30783120616d66693d3078666620616d66695f616c6c6f775f616e795f7369676e61747572653d30783120616d66695f6765745f6f75745f6f665f6d795f7761793d3078312063735f656e666f7263656d656e745f64697361626c653d30783100
iBoot64Patch: Patches applied!
Repacking patched iBSS as IMG4
Repacking patched iBEC as IMG4
Sending iBSS (244451 bytes)...
[==================================================] 100.0%
Booting iBSS, waiting for device to disconnect...
Cleaning up...
[exception]:
what=Device did not disconnect. Possibly invalid iBSS. Reset device and try again
code=45154358
line=689
file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp
commit count=309
commit sha  =36879969be71d56af062aa99be5f28ee482a12bc
Done: restoring failed!

i did what you said still the same..
any other suggestions?

**Comment by edwin170** [comment]
weird tbh, use dualra1n

**Comment by gergerking18** [comment]
yeah, i try it again and again for almost 40 times still the same result

**Comment by edwin170** [comment]
> yeah, i try it again and again for almost 40 times still the same result

what device? what ios is on and what iOS are you going to downgrade to ?

**Comment by gergerking18** [comment]
iphone 6splus version 15.8.1 trying to downgrade to 14.8

**Comment by gergerking18** [comment]
i'm trying your new suggestion! i hope now this works hahah

**Comment by edwin170** [comment]
> iphone 6splus version 15.8.1 trying to downgrade to 14.8

use dualra1n with --downgrade option

**Comment by auvio323** [comment]
> [IMG4TOOL] checking hash for "SEP" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "StaticTrustCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "SystemVolume" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "ftap" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "ftsp" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "iBEC" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "iBSS" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "iBoot" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "rfta" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "rfts" IGN (no digest in BuildManifest)
> 
> failed verification with error: [exception]: what=verification failed! code=84279308 line=1286 file=img4tool.cpp commit count=197 commit sha =aca6cf005c94caf135023263cbb5c61a0081804f [WARNING] NOT VALIDATING SHSH BLOBS IM4M! [Error] BuildIdentity selected for restore does not match APTicket
> 
> BuildIdentity selected for restore: BuildNumber : 18H17 BuildTrain : AzulSecuritySky DeviceClass : n66map FDRSupport : YES MobileDeviceMinVersion : 1253.100.1 RestoreBehavior : Erase Variant : Customer Erase Install (IPSW)
> 
> BuildIdentity is valid for the APTicket: IM4M is not valid for any restore within the Buildmanifest This APTicket can't be used for restoring this firmware [WARNING] NOT VALIDATING SHSH BLOBS! Variant: Customer Erase Install (IPSW) This restore will erase all device data. Device found in DFU Mode. Getting firmware keys for: n66map Patching iBSS Extracting iBSS.n66m.RELEASE.im4p (Firmware/dfu/iBSS.n66m.RELEASE.im4p)... payload decrypted iBoot64Patch: Staring iBoot64Patch! iOS 14 iBoot detected! iBoot64Patch: Inited ibootpatchfinder64! iBoot64Patch: Added sigpatches! iBoot64Patch: Added unlock nvram patch! iBoot64Patch: Added freshnonce patch! iBoot64Patch: has_kernel_load is false! iBoot64Patch: Applying patch=0x18038ffc8 : 000080d2 iBoot64Patch: Applying patch=0x18039006c : 000080d2 iBoot64Patch: Patches applied! Patching iBEC Extracting iBEC.n66m.RELEASE.im4p (Firmware/dfu/iBEC.n66m.RELEASE.im4p)... payload decrypted iBoot64Patch: Staring iBoot64Patch! iOS 14 iBoot detected! iBoot64Patch: Inited ibootpatchfinder64! iBoot64Patch: Added sigpatches! iBoot64Patch: Added unlock nvram patch! iBoot64Patch: Added freshnonce patch! iBoot64Patch: has_kernel_load is true! iBoot64Patch: Added debugenabled patch! iBoot64Patch: Added bootarg patch! iBoot64Patch: Applying patch=0x87000eed4 : 000080d2 iBoot64Patch: Applying patch=0x87000ef28 : 000080d2 iBoot64Patch: Applying patch=0x870003d64 : 000080d2c0035fd6 iBoot64Patch: Applying patch=0x870003db4 : 000080d2c0035fd6 iBoot64Patch: Applying patch=0x870032e7c : 000080d2c0035fd6 iBoot64Patch: Applying patch=0x8700147fc : 1f2003d5 iBoot64Patch: Applying patch=0x870010878 : 200080d2 iBoot64Patch: Applying patch=0x870011e88 : 7af62930 iBoot64Patch: Applying patch=0x870065d55 : 72643d6d6430206e616e642d656e61626c652d7265666f726d61743d307831202d76202d726573746f72652064656275673d30783230313465206b65657073796d733d30783120616d66693d3078666620616d66695f616c6c6f775f616e795f7369676e61747572653d30783120616d66695f6765745f6f75745f6f665f6d795f7761793d3078312063735f656e666f7263656d656e745f64697361626c653d30783100 iBoot64Patch: Patches applied! Repacking patched iBSS as IMG4 Repacking patched iBEC as IMG4 Sending iBSS (244451 bytes)... [==================================================] 100.0% Booting iBSS, waiting for device to disconnect... Cleaning up... [exception]: what=Device did not disconnect. Possibly invalid iBSS. Reset device and try again code=45154358 line=689 file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp commit count=309 commit sha =36879969be71d56af062aa99be5f28ee482a12bc Done: restoring failed!
> 
> i did what you said still the same.. any other suggestions?

I just got the same error, Im using iphone 8 with ios 16.7.5 trying to downgrade to ios 15.6.1. I am new to iphone jailbreak. I was told that ios 15 and 16 jailbreak is the same, and I did not know what shsh blob backup was yet, and my device was originally on 15.3.1. So i update to 16.7.5 and everything is working ok until I see that AltStore does not support 16.7.5, so I try this method to downgrade, and I get this issue.
I cant use dualra1n because my device is on 16.7.5. What can I do?

**Comment by edwin170** [comment]
> > [IMG4TOOL] checking hash for "SEP" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "StaticTrustCache" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "SystemVolume" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "ftap" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "ftsp" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "iBEC" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "iBSS" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "iBoot" BAD! (hash not found in im4m) [IMG4TOOL] checking hash for "rfta" IGN (no digest in BuildManifest) [IMG4TOOL] checking hash for "rfts" IGN (no digest in BuildManifest)
> > failed verification with error: [exception]: what=verification failed! code=84279308 line=1286 file=img4tool.cpp commit count=197 commit sha =aca6cf005c94caf135023263cbb5c61a0081804f [WARNING] NOT VALIDATING SHSH BLOBS IM4M! [Error] BuildIdentity selected for restore does not match APTicket
> > BuildIdentity selected for restore: BuildNumber : 18H17 BuildTrain : AzulSecuritySky DeviceClass : n66map FDRSupport : YES MobileDeviceMinVersion : 1253.100.1 RestoreBehavior : Erase Variant : Customer Erase Install (IPSW)
> > BuildIdentity is valid for the APTicket: IM4M is not valid for any restore within the Buildmanifest This APTicket can't be used for restoring this firmware [WARNING] NOT VALIDATING SHSH BLOBS! Variant: Customer Erase Install (IPSW) This restore will erase all device data. Device found in DFU Mode. Getting firmware keys for: n66map Patching iBSS Extracting iBSS.n66m.RELEASE.im4p (Firmware/dfu/iBSS.n66m.RELEASE.im4p)... payload decrypted iBoot64Patch: Staring iBoot64Patch! iOS 14 iBoot detected! iBoot64Patch: Inited ibootpatchfinder64! iBoot64Patch: Added sigpatches! iBoot64Patch: Added unlock nvram patch! iBoot64Patch: Added freshnonce patch! iBoot64Patch: has_kernel_load is false! iBoot64Patch: Applying patch=0x18038ffc8 : 000080d2 iBoot64Patch: Applying patch=0x18039006c : 000080d2 iBoot64Patch: Patches applied! Patching iBEC Extracting iBEC.n66m.RELEASE.im4p (Firmware/dfu/iBEC.n66m.RELEASE.im4p)... payload decrypted iBoot64Patch: Staring iBoot64Patch! iOS 14 iBoot detected! iBoot64Patch: Inited ibootpatchfinder64! iBoot64Patch: Added sigpatches! iBoot64Patch: Added unlock nvram patch! iBoot64Patch: Added freshnonce patch! iBoot64Patch: has_kernel_load is true! iBoot64Patch: Added debugenabled patch! iBoot64Patch: Added bootarg patch! iBoot64Patch: Applying patch=0x87000eed4 : 000080d2 iBoot64Patch: Applying patch=0x87000ef28 : 000080d2 iBoot64Patch: Applying patch=0x870003d64 : 000080d2c0035fd6 iBoot64Patch: Applying patch=0x870003db4 : 000080d2c0035fd6 iBoot64Patch: Applying patch=0x870032e7c : 000080d2c0035fd6 iBoot64Patch: Applying patch=0x8700147fc : 1f2003d5 iBoot64Patch: Applying patch=0x870010878 : 200080d2 iBoot64Patch: Applying patch=0x870011e88 : 7af62930 iBoot64Patch: Applying patch=0x870065d55 : 72643d6d6430206e616e642d656e61626c652d7265666f726d61743d307831202d76202d726573746f72652064656275673d30783230313465206b65657073796d733d30783120616d66693d3078666620616d66695f616c6c6f775f616e795f7369676e61747572653d30783120616d66695f6765745f6f75745f6f665f6d795f7761793d3078312063735f656e666f7263656d656e745f64697361626c653d30783100 iBoot64Patch: Patches applied! Repacking patched iBSS as IMG4 Repacking patched iBEC as IMG4 Sending iBSS (244451 bytes)... [==================================================] 100.0% Booting iBSS, waiting for device to disconnect... Cleaning up... [exception]: what=Device did not disconnect. Possibly invalid iBSS. Reset device and try again code=45154358 line=689 file=/tmp/Builder/repos/futurerestore/src/futurerestore.cpp commit count=309 commit sha =36879969be71d56af062aa99be5f28ee482a12bc Done: restoring failed!
> > i did what you said still the same.. any other suggestions?
> 
> I just got a similar error: `RestoreBehavior : Erase Variant : Customer Erase Install (IPSW)
> 
> BuildIdentity is valid for the APTicket: IM4M is not valid for any restore within the Buildmanifest This APTicket can't be used for restoring this firmware [WARNING] NOT VALIDATING SHSH BLOBS! Variant: Customer Erase Install (IPSW) This restore will erase all device data. Device found in DFU Mode. Sending iBSS (1422070 bytes)... [==================================================] 100.0% Booting iBSS, waiting for device to disconnect... Booting iBSS, waiting for device to reconnect... Cleaning up... [exception]: what=Device did not reconnect. Possibly invalid iBSS. Reset device and try again code=48824388 line=745 file=/Users/runner/work/futurerestore/futurerestore/src/futurerestore.cpp commit count=309 commit sha =36879969be71d56af062aa99be5f28ee482a12bc Done: restoring failed!`
> 
> Im using iphone 8 with ios 16.7.5 trying to downgrade to ios 15.6.1. I am new to iphone jailbreak. I was told that ios 15 and 16 jailbreak is the same, and I did not know what shsh blob backup was yet, and my device was originally on 15.3.1. So i update to 16.7.5 and everything is working ok until I see that AltStore does not support 16.7.5, so I try this method to downgrade, and I get this issue. I cant use dualra1n because my device is on 16.7.5. What can I do?

try a different iOS version like iOS 14

**Comment by auvio323** [comment]
I tried ios 14, first it didnt succeed, then i rebooted into dfu and it still didnt suceed and it gave some sort of error I frogot the output to, I didnt reboot and tried the command 1 more time, then it suceeded, then I tried doing ./downr1n --boot and it got suck at the last progress bar at 9.7%, and now its stuck in DFU,  I cant go to recovery screen or anything and i try some key combinations and its stuck in dfu still. I used 14.7.1 ipsw. Should i restore iTunes? How can i get out of DFU

**Comment by edwin170** [comment]
> I tried ios 14, first it didnt succeed, then i rebooted into dfu and it still didnt suceed and it gave some sort of error I frogot the output to, I didnt reboot and tried the command 1 more time, then it suceeded, then I tried doing ./downr1n --boot and it got suck at the last progress bar at 9.7%, and now its stuck in DFU,  I cant go to recovery screen or anything and i try some key combinations and its stuck in dfu still. I used 14.7.1 ipsw. Should i restore iTunes? How can i get out of DFU

What do you mean with it stuck on progress var at 9.7%?

**Comment by edwin170** [comment]
If you can't get it boot just restore it with iTunes and give up

**Comment by auvio323** [comment]
[*] Command ran: ./downr1n.sh --boot
downr1n | Version 3.0
Created by edwin, thanks palera1, and all people creator of path file boot

[*] Waiting for devices
[*] Detected DFU mode device
[*] Waiting for devices
[*] Detected DFU mode device
[*] Getting device info...
Detected cpid, your cpid is 0x8015
Detected model, your model is d20ap
Detected deviceid, your deviceid is iPhone10,1
[*] Pwning device
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:000C45C204D8E02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: RESET
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:000C45C204D8E02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SPRAY
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:000C45C204D8E02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: SETUP
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:000C45C204D8E02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Found the USB handle.
Stage: PATCH
ret: true
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:000C45C204D8E02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[*] Resetting DFU state
usb_timeout: 5
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[*] Booting device
[==================================================] 100.0%
[==================================================] 100.0%
Attempting to connect... 
opening device 05ac:1227 @ 0x14200000...
Setting to configuration 1
Setting to interface 0:0
Connected to iPhone10,1, model d20ap, cpid 0x8015, bdid 0x02
[==================================================] 100.0%Command completed successfully

[=====                                             ] 9.7%%

**Comment by edwin170** [comment]
> [*] Command ran: ./downr1n.sh --boot
> 
> downr1n | Version 3.0
> 
> Created by edwin, thanks palera1, and all people creator of path file boot
> 
> 
> 
> [*] Waiting for devices
> 
> [*] Detected DFU mode device
> 
> [*] Waiting for devices
> 
> [*] Detected DFU mode device
> 
> [*] Getting device info...
> 
> Detected cpid, your cpid is 0x8015
> 
> Detected model, your model is d20ap
> 
> Detected deviceid, your deviceid is iPhone10,1
> 
> [*] Pwning device
> 
> usb_timeout: 5
> 
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> 
> CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:000C45C204D8E02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
> 
> Found the USB handle.
> 
> Stage: RESET
> 
> ret: true
> 
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> 
> CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:000C45C204D8E02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
> 
> Found the USB handle.
> 
> Stage: SPRAY
> 
> ret: true
> 
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> 
> CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:000C45C204D8E02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
> 
> Found the USB handle.
> 
> Stage: SETUP
> 
> ret: true
> 
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> 
> CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:000C45C204D8E02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
> 
> Found the USB handle.
> 
> Stage: PATCH
> 
> ret: true
> 
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> 
> CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:02 ECID:000C45C204D8E02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[gaster]
> 
> Found the USB handle.
> 
> Now you can boot untrusted images.
> 
> [*] Resetting DFU state
> 
> usb_timeout: 5
> 
> [IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
> 
> Found the USB handle.
> 
> [*] Booting device
> 
> [==================================================] 100.0%
> 
> [==================================================] 100.0%
> 
> Attempting to connect... 
> 
> opening device 05ac:1227 @ 0x14200000...
> 
> Setting to configuration 1
> 
> Setting to interface 0:0
> 
> Connected to iPhone10,1, model d20ap, cpid 0x8015, bdid 0x02
> 
> [==================================================] 100.0%Command completed successfully
> 
> 
> 
> [=====                                             ] 9.7%%      

Restore it with iTunes

**Comment by auvio323** [comment]
Ok, it is restoring rn

**Comment by auvio323** [comment]
Im not sure why, but now it seems to work with Linux, and I have successfuly downgraded to 15.4.1. It doesnt seem to work with macOS.
However, my device has MDM lock and I used "MDMPatcher Universal" to bypass it on 16.7.5, but it is only temporary and it doesnt seem to work in tethered downgrade mode. Is there a way I can get past that screen? It shows Activation Failed every time I try to continue with the setup screen.

**Comment by Ran-Xing** [comment]
@auvio323 Have you ever tried a lower system?

**Comment by auvio323** [comment]
> @auvio323 Have you ever tried a lower system?

I don't understand your question

**Comment by edwin170** [comment]
> > @auvio323 Have you ever tried a lower system?
> 
> I don't understand your question

like iOS 14 ?

**Comment by Ran-Xing** [comment]
my ipad pro 9.7 can't restore

**Comment by edwin170** [comment]
> my ipad pro 9.7 can't restore

What do you mean exactly ?

**Comment by Ran-Xing** [comment]
My iPad Pro 9.7 cannot be downgraded

**Comment by edwin170** [comment]
> My iPad Pro 9.7 cannot be downgraded

Put it in the real dfu mode, then use iTunes to restore it
