### ISSUE TITLE
TypeError: function missing required argument 'initial_buffer_values' (pos 2)

### ISSUE THREAD

**Issue by alexeimarkov945** [edwin170/downr1n#98]
Please help me!
This is the log:
[*] Command ran: sudo ./downr1n.sh --downgrade 14.0
[21:13:08.413][3] usbmuxd v1.1.1 starting up
[21:13:08.414][3] Using libusb 1.0.25
[21:13:08.418][3] Initialization complete
[21:13:08.419][3] Connecting to new device on location 0x30021 as ID 1
[21:13:08.419][3] Connected to v2.0 device 1 on location 0x30021 with serial number ramdisk tool Sep 18 2022 20:14:43
downr1n | Version 3.0
Created by edwin, thanks palera1, and all people creator of path file boot

[*] Waiting for devices
[*] Detected ramdisk mode device
[*] Rebooting device in SSH Ramdisk
[21:13:09.426][2] device_control_input: Got unhandled payload type 5
[21:13:14.616][3] Removed device 1 on location 0x30021
[*] Waiting for device in recovery mode
[*] Waiting for devices
[*] Detected recovery mode device
[*] Getting device info...
Detected cpid, your cpid is 0x8003
Detected model, your model is n66map
Detected deviceid, your deviceid is iPhone8,2
[*] To get into DFU mode, you will be guided through 2 steps:
[*] Press any key when ready for DFU mode
Get ready (0)
Release power button, but keep holding home button (9)
Release power button, but keep holding home button (2)
[*] Device entered DFU!
[-] we found ipsw/iPhone_5.5_14.0_18A373_Restore.ipsw, do you want to use it ? please write, yes or no
yes
ipsw/iPhone_5.5_14.0_18A373_Restore.ipsw
[*] Checking if the ipsw is for your device
[*] Checking ipsw version
[*] Extracting ipsw, hang on please ...
[*] Got extract the IPSW successfully
[*] Creating ramdisk
[-] Ramdisk is already created so SKIPPING ...
[*] Booting ramdisk
[/] We couldn't get the ipsw curl. we will proceed with -k option with curl
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8003
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8003
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8003
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8003
Found the USB handle.
Now you can boot untrusted images.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Waiting for the ramdisk to finish booting
libusb: warning [op_get_configuration] device unconfigured
libusb: error [op_get_active_config_descriptor] device unconfigured
[21:14:23.888][3] Could not get old configuration descriptor for device 3-41: LIBUSB_ERROR_NOT_FOUND
[21:14:23.902][3] Connecting to new device on location 0x30029 as ID 2
[21:14:23.942][3] Connected to v2.0 device 2 on location 0x30029 with serial number ramdisk tool Sep 18 2022 20:14:43
[21:14:23.942][2] device_control_input: Got unhandled payload type 5
[21:14:24.850][2] device_control_input: Got unhandled payload type 5
Error connecting to device: No error information
[*] Mounting filesystems ...
[*] Dumpped SHSH
[*] Checking device version
the version that the device is currently in is 15.8
[*] extracting kernel ...
*The error:
**TypeError: function missing required argument 'initial_buffer_values' (pos 2)**

**Comment by edwin170** [comment]
> Please help me! This is the log: [*] Command ran: sudo ./downr1n.sh --downgrade 14.0 [21:13:08.413][3] usbmuxd v1.1.1 starting up [21:13:08.414][3] Using libusb 1.0.25 [21:13:08.418][3] Initialization complete [21:13:08.419][3] Connecting to new device on location 0x30021 as ID 1 [21:13:08.419][3] Connected to v2.0 device 1 on location 0x30021 with serial number ramdisk tool Sep 18 2022 20:14:43 downr1n | Version 3.0 Created by edwin, thanks palera1, and all people creator of path file boot
> 
> [_] Waiting for devices [_] Detected ramdisk mode device [_] Rebooting device in SSH Ramdisk [21:13:09.426][2] device_control_input: Got unhandled payload type 5 [21:13:14.616][3] Removed device 1 on location 0x30021 [_] Waiting for device in recovery mode [_] Waiting for devices [_] Detected recovery mode device [_] Getting device info... Detected cpid, your cpid is 0x8003 Detected model, your model is n66map Detected deviceid, your deviceid is iPhone8,2 [_] To get into DFU mode, you will be guided through 2 steps: [_] Press any key when ready for DFU mode Get ready (0) Release power button, but keep holding home button (9) Release power button, but keep holding home button (2) [_] Device entered DFU! [-] we found ipsw/iPhone_5.5_14.0_18A373_Restore.ipsw, do you want to use it ? please write, yes or no yes ipsw/iPhone_5.5_14.0_18A373_Restore.ipsw [_] Checking if the ipsw is for your device [_] Checking ipsw version [_] Extracting ipsw, hang on please ... [_] Got extract the IPSW successfully [_] Creating ramdisk [-] Ramdisk is already created so SKIPPING ... [_] Booting ramdisk [/] We couldn't get the ipsw curl. we will proceed with -k option with curl usb_timeout: 5 [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8003 Found the USB handle. Stage: RESET ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8003 Found the USB handle. Stage: SETUP ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8003 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8003 Found the USB handle. Now you can boot untrusted images. usb_timeout: 5 [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 Found the USB handle. [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [_] Waiting for the ramdisk to finish booting libusb: warning [op_get_configuration] device unconfigured libusb: error [op_get_active_config_descriptor] device unconfigured [21:14:23.888][3] Could not get old configuration descriptor for device 3-41: LIBUSB_ERROR_NOT_FOUND [21:14:23.902][3] Connecting to new device on location 0x30029 as ID 2 [21:14:23.942][3] Connected to v2.0 device 2 on location 0x30029 with serial number ramdisk tool Sep 18 2022 20:14:43 [21:14:23.942][2] device_control_input: Got unhandled payload type 5 [21:14:24.850][2] device_control_input: Got unhandled payload type 5 Error connecting to device: No error information [_] Mounting filesystems ... [_] Dumpped SHSH [_] Checking device version the version that the device is currently in is 15.8 [*] extracting kernel ... *The error: **TypeError: function missing required argument 'initial_buffer_values' (pos 2)**

python3 -m pip uninstall pylzss lzss

**Comment by alexeimarkov945** [comment]
> > Please help me! This is the log: [*] Command ran: sudo ./downr1n.sh --downgrade 14.0 [21:13:08.413][3] usbmuxd v1.1.1 starting up [21:13:08.414][3] Using libusb 1.0.25 [21:13:08.418][3] Initialization complete [21:13:08.419][3] Connecting to new device on location 0x30021 as ID 1 [21:13:08.419][3] Connected to v2.0 device 1 on location 0x30021 with serial number ramdisk tool Sep 18 2022 20:14:43 downr1n | Version 3.0 Created by edwin, thanks palera1, and all people creator of path file boot
> > [_] Waiting for devices [_] Detected ramdisk mode device [_] Rebooting device in SSH Ramdisk [21:13:09.426][2] device_control_input: Got unhandled payload type 5 [21:13:14.616][3] Removed device 1 on location 0x30021 [_] Waiting for device in recovery mode [_] Waiting for devices [_] Detected recovery mode device [_] Getting device info... Detected cpid, your cpid is 0x8003 Detected model, your model is n66map Detected deviceid, your deviceid is iPhone8,2 [_] To get into DFU mode, you will be guided through 2 steps: [_] Press any key when ready for DFU mode Get ready (0) Release power button, but keep holding home button (9) Release power button, but keep holding home button (2) [_] Device entered DFU! [-] we found ipsw/iPhone_5.5_14.0_18A373_Restore.ipsw, do you want to use it ? please write, yes or no yes ipsw/iPhone_5.5_14.0_18A373_Restore.ipsw [_] Checking if the ipsw is for your device [_] Checking ipsw version [_] Extracting ipsw, hang on please ... [_] Got extract the IPSW successfully [_] Creating ramdisk [-] Ramdisk is already created so SKIPPING ... [_] Booting ramdisk [/] We couldn't get the ipsw curl. we will proceed with -k option with curl usb_timeout: 5 [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8003 Found the USB handle. Stage: RESET ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8003 Found the USB handle. Stage: SETUP ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8003 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8003 Found the USB handle. Now you can boot untrusted images. usb_timeout: 5 [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 Found the USB handle. [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [_] Waiting for the ramdisk to finish booting libusb: warning [op_get_configuration] device unconfigured libusb: error [op_get_active_config_descriptor] device unconfigured [21:14:23.888][3] Could not get old configuration descriptor for device 3-41: LIBUSB_ERROR_NOT_FOUND [21:14:23.902][3] Connecting to new device on location 0x30029 as ID 2 [21:14:23.942][3] Connected to v2.0 device 2 on location 0x30029 with serial number ramdisk tool Sep 18 2022 20:14:43 [21:14:23.942][2] device_control_input: Got unhandled payload type 5 [21:14:24.850][2] device_control_input: Got unhandled payload type 5 Error connecting to device: No error information [_] Mounting filesystems ... [_] Dumpped SHSH [_] Checking device version the version that the device is currently in is 15.8 [*] extracting kernel ... *The error: **TypeError: function missing required argument 'initial_buffer_values' (pos 2)**
> 
> python3 -m pip uninstall pylzss lzss

Thank you. I will try it
